### ISSUE TITLE
Non JSON output for some integration tests

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#1002]
## Description

Integration tests running on AKS with `arm64` can fail because a non JSON message is printed.

## Impact

The integration test fails.

## Environment and steps to reproduce

Example for [`execsnoop`](https://github.com/kinvolk/inspektor-gadget/actions/runs/3157606929/jobs/5140732791#step:9:426):

```
        ***"node":"aks-nodepool1-24915329-vmss000000","namespace":"test-execsnoop-1217338277375591049","pod":"test-pod","container":"test-pod","type":"normal","pid":31403,"ppid":31073,"pcomm":"sleep","mountnsid":4026532783***
        Trace completed on node "aks-nodepool1-24915329-vmss000000"
        Trace completed on node "aks-nodepool1-24915329-vmss000001"
        Trace completed on node "aks-nodepool1-24915329-vmss000002"
        
    command.go:440: invalid command output(StartExecsnoopGadget): verifying output with custom function: unmarshaling line "Trace completed on node \"aks-nodepool1-24915329-vmss000000\"": invalid character 'T' looking for beginning of value
```

The faulty message is ["Trace completed on node"](https://github.com/kinvolk/inspektor-gadget/blob/3e9dd95366423b4ec28019fe78d7aa95fdfd2c83/cmd/kubectl-gadget/utils/trace.go#L1020).

## Expected behavior

Only JSON output should be printed

## Additional information

I am sadly not able to reproduce outside of the CI...

**Comment by mauriciovasquezbernal** [comment]
For sure those messages shouldn't be printed to stdout. Maybe we can just print them to stderr until we find a better way to handle this situation? 

> I am sadly not able to reproduce outside of the CI...

Which architecture are you running kubectl-gadget in? I think it can be a race condition on kubectl-gadget:
- genericStreams() creates a goroutine to get the streams of the tracer on each node. It also installs a sig handler on SIGINT
- sigHandler() installs a handler in SIGINT and calls DeleteTrace() and then os.Exit() when this signal is triggered

I seems to me the logic around those two channel on the same signal is racy and for that reason the message is only printed some times.
