### ISSUE TITLE
[RFE] Consoleanimation generation (`.gif`) should have a uniform size of the console

### ISSUE THREAD

**Issue by burak-ok** [inspektor-gadget/inspektor-gadget#1031]
## Current situation

Many of the `.gif` console animations have different `width` and `height`

## Impact

When browsing through the manuals and guids it looks cluttered when all the animations have different sizes.
Furthermore when Browsers are automatically rescaling the `.gif` animation, the textsize could change and readability suffers.

Also the contributor shouldn't have to think about the `width` and `height` of its own console so much when generating the animations

## Ideal future situation

When generating the animations, the width and height should be set globally somewhere (probably in the `Makefile`)
Maybe the height should remain variable, but there sould be standards for short, long, ... console windows.

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/1039.
