### ISSUE TITLE
Regression for inspektor-gadget:v0.9.1 : "Error: timeout waiting for condition on node"

### ISSUE THREAD

**Issue by ledroide** [inspektor-gadget/inspektor-gadget#1043]
Hello,
I have deployed successfully the DaemonSet with kubectl-gadget v9.0.1, pods run fine, no error in logs : 
```bash
$ kubectl gadget version
v0.9.1

$ kubectl gadget deploy --debug
[...]
7/7 gadget pod(s) ready
Inspektor Gadget successfully deployed
```

When using image ghcr.io/kinvolk/inspektor-gadget:v0.9.1 : 
```bash
$ kubectl gadget advise network-policy monitor -n iam --output ./temp/networktrace.log
Recording events into file "-"...
Error: timeout waiting for condition on node "frd3kq-k8s03"
Error: timeout waiting for condition on node "frd3kq-k8s04"
Error: timeout waiting for condition on node "frd3kq-k8s01g"
```
... and nothing more comes after this error.

Same error without output file.
Tried also : 
```bash
$ kubectl gadget trace tcp --namespace iam
NODE                           NAMESPACE                      POD                            CONTAINER                      T PID     COMM             IP SADDR                  DADDR                  SPORT DPORT
Error: timeout waiting for condition on node "frd3kq-k8s01g"
Error: timeout waiting for condition on node "frd3kq-k8s04"
Error: timeout waiting for condition on node "frd3kq-k8s03"
```
Tried with fixed (see #940) plugin : 
```bash
$ /usr/local/bin/kubectl-gadget-OLD version
v0.8.0-49-g3af35cb
$ /usr/local/bin/kubectl-gadget-OLD trace tcp --namespace iam
NODE             NAMESPACE        POD                            CONTAINER        T  PID     COMM             IP  SADDR            DADDR            SPORT   DPORT   
Error: timeout waiting for condition on node "frd3kq-k8s04"
Error: timeout waiting for condition on node "frd3kq-k8s03"
Error: timeout waiting for condition on node "frd3kq-k8s01g"
```

But when I roll back to previous image  (as fixed previously for issue  #940) : 
```bash
$ kubectl gadget deploy --image ghcr.io/mauriciovasquezbernal/inspektor-gadget:mauricio-owner-reference-lazy
```
```
NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE   CONTAINERS   IMAGES                                                                         SELECTOR
daemonset.apps/gadget   9         9         9       9            9           kubernetes.io/os=linux   53m   gadget       ghcr.io/mauriciovasquezbernal/inspektor-gadget:mauricio-owner-reference-lazy   k8s-app=gadget
```
Once pods are started, using plugin v9.0.1 and the older image for DaemonSet, it works : 
```bash
$ kubectl gadget version
v0.9.1

$ kubectl gadget trace tcp --namespace iam
NODE                           NAMESPACE                      POD                            CONTAINER                      T PID     COMM             IP SADDR                  DADDR                  SPORT DPORT
frd3kq-k8s04                   iam                            login-ui-579599c4df-hlrcm      nginx-exporter                 A 3916348 nginx-prometheu  6  ::ffff:10.233.101.70   ::ffff:10.233.120.2    9113  46012
frd3kq-k8s03                   iam                            protection-6669cc756f-gm6b9    protection                     X 2644632 http-nio-8081-P  6  ::ffff:10.233.85.62    ::ffff:10.150.236.3    8081  47362
frd3kq-k8s01g                  iam                            nats-8658595587-j4qzk          metrics                        A 2007482 prometheus-nats  6  ::ffff:10.233.121.85   ::ffff:10.150.236.1    7777  36216
frd3kq-k8s01g                  iam                            nats-8658595587-j4qzk          nats
[...]

$ kubectl gadget advise network-policy monitor -n iam
Recording events into file "-"...{"node":"frd3kq-k8s04","namespace":"iam","pod":"committee-68f764bdfc-hmzjf","type":"err","message":"failed to attach tracer: failed to open raw socket: no such file or directory"}
{"node":"frd3kq-k8s01g","namespace":"iam","pod":"database-5bc55486d9-hsnfz","type":"debug","message":"tracer attached"}
{"node":"frd3kq-k8s01g","namespace":"iam","pod":"marking-ui-766b45cb54-fbrbg","type":"debug","message":"tracer attached"}
[...]
```

**Comment by mauriciovasquezbernal** [comment]
I'm not sure it's related with https://github.com/inspektor-gadget/inspektor-gadget/issues/940. 

Could you please try the following to be sure the main/latest version is broken?

1. Download and install the latest version of kubectl-gadget (https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/install.md#compile-from-source)
2. Deploy it to the cluster using its default image (`ghcr.io/inspektor-gadget/inspektor-gadget:latest`)
3. Does it get installed to the cluster without issues?
4. Try to run some gadgets `kubectl gadget trace tcp --namespace iam`
5. Does it work? If not, could you please provide the logs from the cluster? (`kubectl -n gadget logs k8s-app=gadget`).

**Comment by mauriciovasquezbernal** [comment]
> Obviously it's not related. I use these patched versions because they work since weeks and because they fix the issue #940, that is the only reason.

Ah, I was confused because you're linking to it here. 

> I will try next week to rebuild the plugin

That would help a lot. I'm trying to look at the changes we introduced after https://github.com/inspektor-gadget/inspektor-gadget/commit/65d7497456304589fa010e7a45f12af54b165ccb but I don't see anything obvious that could be causing issues.

This could be also related to https://github.com/inspektor-gadget/inspektor-gadget/issues/559.

**Comment by ledroide** [comment]
Hello @eiffel-fl and @mauriciovasquezbernal .
Today I cannot reproduce the issue after setting back image ghcr.io/kinvolk/inspektor-gadget:v0.9.1 for daemonset/gadget
I am absolutely sure to have been able to reproduce the same issue many times three days ago.
The behavior was very clear when setting this image v0.9.1, then the older one, then this new one, then the older one.
I have no doubt about it.
My guess is a bug that only appears for v0.9.1 in race conditions when the cluster resources are high - and that was the case on Friday.
I'll try again the next days, and will collect more logs when it happens again.

**Comment by ledroide** [comment]
@eiffel-fl : After upgrading recently to ghcr.io/kinvolk/inspektor-gadget:v0.10.0 , I did not experience this issue again.
It it happens however sometime, I will open a new issue item.
Thanks !
