### ISSUE TITLE
[RFE] Use a proper name for INSPEKTOR_GADGET_VERSION

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#1061]
As discussed https://github.com/inspektor-gadget/inspektor-gadget/pull/977#discussion_r977658453, the name `INSPEKTOR_GADGET_VERSION` is wrong/misleading. We need to use a proper name for it.

**Comment by moki1202** [comment]
@blanquicet does `KUBECTL_GADGET_VERSION` sound like a good replacement ?

**Comment by mauriciovasquezbernal** [comment]
I'd say we can rid of this. Providing the kubectl-gadget information the gadget pod could be misleading. It's possible to deploy Inspektor Gadget with a kubectl-gadget version and use it with another, so I don't think we should be providing this information at all.

**Comment by moki1202** [comment]
I'll open a PR soon.
