### ISSUE TITLE
[RFE] Use K8s API directly instead of exec kubectl ...

### ISSUE THREAD

**Issue by burak-ok** [inspektor-gadget/inspektor-gadget#1112]
## Current situation

At least in `integration/command.go` we are calling `kubectl` for new pods, waiting on something, gathering information, etc...
We should use the k8s API directly

See https://github.com/inspektor-gadget/inspektor-gadget/pull/1091#discussion_r1014264671

**Comment by mauriciovasquezbernal** [comment]
We realized it doesn't make sense to implement it. It's too much work for little benefit. Closing.
