### ISSUE TITLE
Support arbitrary Enrichers

### ISSUE THREAD

**Issue by johananl** [inspektor-gadget/inspektor-gadget#1122]
Enrichers allow adding data in user space to an event which was generated by the kernel. A classic example is adding node and pod information from the k8s API.

Right now we have one kind of Enricher which seems to be used by most gadgets:

https://github.com/inspektor-gadget/inspektor-gadget/blob/41c387e688cfbf339bc0b4953979fc15cf23d863/pkg/gadgets/helpers.go#L39-L43

https://github.com/inspektor-gadget/inspektor-gadget/blob/41c387e688cfbf339bc0b4953979fc15cf23d863/pkg/container-collection/container-collection.go#L303-L312

We also have one gadget - the network tracing gadget - which doesn't use the Enricher above and instead implements its own Enricher:

https://github.com/inspektor-gadget/inspektor-gadget/blob/41c387e688cfbf339bc0b4953979fc15cf23d863/pkg/gadget-collection/gadgets/trace/network/enricher.go#L32-L36

The custom Enricher used by the network tracing gadget **implements its own logic** for enriching the event with node and pod information, thus duplicating the logic already present in the generic Enricher. This is not ideal.

In addition, some gadgets may need to enrich events with custom data **in addition** to the data added to the event by the generic Enricher, not instead of it. Right now there is no obvious way of doing that AFAICT.

Therefore, I suggest we consider refactoring Enricher handling so that gadgets can register (or explicitly call) an arbitrary number of Enrichers. This way, for example, a gadget could leverage the generic Enricher for adding node and pod info to the event, and then use another custom Enricher for adding additional data. A concrete example I've encountered is the need for enriching an event with **k8s volume information** in addition to node and pod information.

**Comment by mauriciovasquezbernal** [comment]
First of all, I want to clarify that there are two different things that are called enrichers:
1. All the logic to get the information about a container using the K8s and different container runtimes APIs (mostly implemented [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/container-collection/options.go)
2. An interface used by tracers to add information to an event generated by the kernel. (Implemented [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/41c387e688cfbf339bc0b4953979fc15cf23d863/pkg/gadgets/helpers.go#L39-L43))

Regarding the ones mentioned in (1), I think it makes sense to add other kinds, like enriching by containerID as mentioned in https://github.com/inspektor-gadget/inspektor-gadget/pull/1103#discussion_r1017992952. We can rename the current [Enrich()](https://github.com/inspektor-gadget/inspektor-gadget/blob/41c387e688cfbf339bc0b4953979fc15cf23d863/pkg/gadgets/helpers.go#L42) method to EnrichByMntnsID and add a new EnrichByContainerID, then each gadget could decide which one to call based on the information they have available. (Some gadgets have mount ns id, others container ID and so on). 

About the second kind of enrichment, currently we try to completely enrich the container, however it's not optimal as many of the enriched data are never used. My point, is it worth it to try to implement conditional enrichers at this time? Maybe it's some early-optimization and the gains are minimal? (IMO to unblock the work from @johananl you could add the needed fields in the container struct and enrich it all the times, then we can decide if we need to optimize it). What do you all think?

**Comment by blanquicet** [comment]
Hi @johananl, trying to add the network-graph trace gadget to `local-gadget`, I noticed what you said here:

> The custom Enricher used by the network tracing gadget implements its own logic for enriching the event with node and pod information, thus duplicating the logic already present in the generic Enricher. This is not ideal.
>

It means that each consumer of the tracer (Inspektor-Gadget, `local-gadget` and a potential 3rd-party app like Headlamp) must implement this enrichment on its own. Therefore, I propose moving the enrichment inside the tracer itself by adding a new enricher [EnrichByNetNs](https://github.com/inspektor-gadget/inspektor-gadget/pull/1156/commits/3d3b688e7c450c44ed24d4b78e42ca08189196fe) in PR https://github.com/inspektor-gadget/inspektor-gadget/pull/1156. Even though it enriches the events again only with the Kubernetes metadata and not arbitrary data as you need, it tries to address the first part of the issue you mentioned in the description of this issue 🙂

**Comment by johananl** [comment]
Cool, thanks @blanquicet. I guess I could try the same approach with the gadget I'm working on, and hopefully find a way to get the missing data.

**Comment by mauriciovasquezbernal** [comment]
I think it's fixed by the new operators approach. Operators are registered at startup and can enrich events with whatever information they have, for instance, there is an [`KubeIPResolver`](https://github.com/inspektor-gadget/inspektor-gadget/blob/v0.18.1/pkg/operators/kubeipresolver/kubeipresolver.go) operator that enriches IP addresses with Kubernetes related data.

@flyth what do you think about this?
@johananl do you think a new operator will work for you use case?

**Comment by mauriciovasquezbernal** [comment]
I definitely think it's covered by Operators. Closing. Please reopen if this is not the case.

**Comment by johananl** [comment]
Sorry @mauriciovasquezbernal, haven't had time to recheck this yet. Will report back if I think there is still a problem. Thanks!
