### ISSUE TITLE
[RFE] ig: Create integration test for non-Kubernetes containers

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#1124]
## Current situation

https://github.com/inspektor-gadget/inspektor-gadget/pull/946 introduced integration tests for ig using Kubernetes containers. However, we are missing tests for non-Kubernetes containers. 

## Implementation options

We could reuse the helpers already implemented [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/local-gadget-manager/local-gadget-manager_test.go) for Docker.

**Comment by mqasimsarfraz** [comment]
One other implementation option I was thinking was to use `docker`, `ctr` and `crictl` cli(s) for `docker`, `containerd` and `cri-o` runtimes respectively in tests. We need to add helpers for all of them, making it easy to write tests for non-Kubernetes containers. What do you say?

**Comment by blanquicet** [comment]
> One other implementation option I was thinking was to use `docker`, `ctr` and `crictl` cli(s) for `docker`, `containerd` and `cri-o` runtimes respectively in tests. We need to add helpers for all of them, making it easy to write tests for non-Kubernetes containers. What do you say?

I'm not sure for the `cri-o`, but yest, I had the same idea. I think you could start with `docker` as we already have the helper functions, e.g. [runTestContainer](https://github.com/inspektor-gadget/inspektor-gadget/blob/9bea312fa20a111ffbea514569ae5e572d532996/pkg/local-gadget-manager/local-gadget-manager_test.go#L75).

Do you want to start working on this?

**Comment by blanquicet** [comment]
> > One other implementation option I was thinking was to use `docker`, `ctr` and `crictl` cli(s) for `docker`, `containerd` and `cri-o` runtimes respectively in tests. We need to add helpers for all of them, making it easy to write tests for non-Kubernetes containers. What do you say?
> 
> I'm not sure for the `cri-o`, but yes, I had the same idea. I think you could start with `docker` as we already have the helper functions, e.g. [runTestContainer](https://github.com/inspektor-gadget/inspektor-gadget/blob/9bea312fa20a111ffbea514569ae5e572d532996/pkg/local-gadget-manager/local-gadget-manager_test.go#L75).

I apologize, I didn't read well. You were proposing using the CLI, not the API. Mmmm I am not sure, I think in this case, using the API doesn't seem that difficult like for Kubernetes (https://github.com/inspektor-gadget/inspektor-gadget/issues/1112 -> https://github.com/inspektor-gadget/inspektor-gadget/pull/1116), and the API provides some advantages from my point of view: (1) It is more flexible when we need special container configuration (e.g. [seccomp profiles](https://github.com/inspektor-gadget/inspektor-gadget/blob/9bea312fa20a111ffbea514569ae5e572d532996/pkg/local-gadget-manager/local-gadget-manager_test.go#L91-L93)), and (2) it doesn't require the CLI to be installed in the system. On the other side, implementing the CLI approach _should_ be easier as we already have the infrastructure to run commands.

I would like to know what other folks think about this.

**Comment by burak-ok** [comment]
I am also generally leaning towards using the API instead of the CLI.
Additionally to @blanquicet 's points there is also the advantage that we do not need to parse the (maybe unstable) output of the CLI for results.

But as it can be seen in my Draft PR #1116, it can also sometimes be cumbersome to use the API instead of the CLI.

`fmt.Sprintf("kubectl wait pod --for condition=ready -n %s %s", namespace, podname)` vs 60 lines of code (https://github.com/inspektor-gadget/inspektor-gadget/pull/1116/commits/5d54b6ba43fe78820b009a64b3278827bcddd1fd)

**Comment by mqasimsarfraz** [comment]
> I'm more for using the API, but I would like to know what other folks think about this.

Based on the [discussion](https://kubernetes.slack.com/archives/CSYL75LF6/p1669119705250229) and ^, I believe it makes sense to go forward with API approach. 

> Do you want to start working on this?
Yeah, I wanted to add at least one non-Kubernetes containers test for each runtime. Should I go ahead with that?

**Comment by mqasimsarfraz** [comment]
Completed by #1162

**Comment by blanquicet** [comment]
Reopening this issue to track missing tests:

- advise:
	- [ ] seccomp-profile
- audit:
	- [ ] seccomp
- profile:
	- [ ] block-io
	- [ ] cpu
- snapshot:
	- [ ] process
- top:
	- [ ] block-io
	- [ ] ebpf
	- [ ] file
	- [ ] tcp 
- trace:
	- [ ] bind
	- [ ] capabilities
	- [ ] dns
	- [ ] exec
	- [ ] fsslower
	- [ ] mount
	- [ ] network (https://github.com/inspektor-gadget/inspektor-gadget/pull/1156)
	- [ ] oomkill
	- [ ] open
	- [ ] signal
	- [ ] sni
	- [ ] tcp
	- [ ] tcpconnect
- [ ] traceloop

In addition, we need to make the tests runnable with docker and containerd without rewriting them twice but passing a parameter as we do for Kubernetes tests:

```bash
$ sudo local-gadget-non-k8s-integration.test -test.v -integration -container-runtime {docker|containerd}
```

**Comment by mqasimsarfraz** [comment]
> In addition, we need to make the tests runnable with docker and containerd without rewriting them twice but passing a parameter as we do for Kubernetes tests:
> 
> ```shell
> $ sudo local-gadget-non-k8s-integration.test -test.v -integration -container-runtime {docker|containerd}
> ```
+1 I wanted to do that once we plan to support `containerd` I had something like [this](https://github.com/inspektor-gadget/inspektor-gadget/commit/a4fbf6ff0c3a5e32fce47bbe446c7fd66c936eab) in my mind. What do you say?

**Comment by blanquicet** [comment]
> I had something like [this](https://github.com/inspektor-gadget/inspektor-gadget/commit/a4fbf6ff0c3a5e32fce47bbe446c7fd66c936eab) in my mind. What do you say?
>
That's exactly what was in my mind! 🚀 ... Please sync with @burak-ok given that he is working on containerd support and testing in container-utils package.

**Comment by mauriciovasquezbernal** [comment]
#2867 was completed and [gadgets](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/gadgets) are using it to test on both k8s and non-k8s containers. We can mark this as completed.
