### ISSUE TITLE
[RFC] Remove local-gadget CR-based implementation (interactive mode)

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#1125]
This issue proposes removing the local-gadget CR-based implementation (`local-gadget interactive`) and only keeping trace implementation (`local-gadget snapshot|trace|...`).

Pros of CR-based implementation:

1. It is really useful because it allows us to support new gadgets in local contexts easily. However, we have improved the code so that integrating new gadgets on local-gadget without using the CR is now quite simple. Examples: https://github.com/inspektor-gadget/inspektor-gadget/pull/1099/commits/6d0a2e156a65380e3264cb5b02ffd60318b438f5, https://github.com/inspektor-gadget/inspektor-gadget/pull/1053/commits/09858c5ba583a146570b41c9713cc5d35ad8f9c5.
2. Tests are pretty fast: [`local-gadget-manager_test.go`](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/local-gadget-manager/local-gadget-manager_test.go). Nevertheless, this is something we can also do for non-CR-based mode. We can easily reuse the logic and helpers already created. I created an issue for this: [#1124](https://github.com/inspektor-gadget/inspektor-gadget/issues/1124).

Cons of CR-based implementation:
1. The implementation is based on a Kubernetes concept (CR) that makes no sense for the local-gadget context.
2. Point (1) forced us to add specific logic in the Inspektor-Gadget CRcode to support the local-gadget use-case, which adds complexity that we can avoid by using the tracers directly without passing through the CR code (gadget-collection package). Some examples:
	- Support non-Kubernetes use-case within the code that manages Kubernetes CR (?): [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/41c387e688cfbf339bc0b4953979fc15cf23d863/pkg/gadget-collection/gadgets/trace/network/enricher.go#L39-L44).
	- Specific logic for local-gadget in seccomp-profile advisor. For instance, [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/41c387e688cfbf339bc0b4953979fc15cf23d863/pkg/gadget-collection/gadgets/advise/seccomp/gadget.go#L284-L298) and [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/41c387e688cfbf339bc0b4953979fc15cf23d863/pkg/gadget-collection/gadgets/advise/seccomp/gadget.go#L386-L392).
3. The list-containers command and the gadget events for non-Kubernetes gadgets show wrong information: namespace=`default` and podname=`<containername>`. It is confusing for users.
4. I have been working on [this](https://github.com/inspektor-gadget/inspektor-gadget/pull/999) PR to add the Kubernetes metadata: namespace, pod and container. Now, given that the Kubernetes container name is different than the runtime container name for Docker, they need to be kept separately. It implies that we need to be able to filter the gadget events by both container names. However, given that the CR-based implementation uses the [`gadgetv1alpha1.ContainerFilter`](https://github.com/inspektor-gadget/inspektor-gadget/blob/v0.10.0/pkg/apis/gadget/v1alpha1/types.go#L69), how can we filter by runtime container name (for instance, a non-kuberntes container)? I am sure we could find a tricky way to do it. But again, we will continue adding code for managing local-gadget (sometimes non-Kubernetes containers) within a Kubernetes-specific code (all the CR management).
5. We have almost all gadgets the non-CR-based implementation with respect to the CR-based implementation. There are only three gadgets (audit/seccomp, advise/seccomp-profile and top/ebpf). This epic task is tracked by [#861](https://github.com/inspektor-gadget/inspektor-gadget/issues/861).

What do you think? Any other pros/cons or comments in general?

**Comment by mauriciovasquezbernal** [comment]
IMO interactive mode made sense at the beginning to quickly implement support for other gadgets in local-gadget, but now that we're using the tracers directly I don't see any reason to keep it. I think the maintenance overhead is too much and it'll slow us.
