### ISSUE TITLE
[RFE] Manage special events in the same way in all gadgets

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#1130]
## Current situation

As discussed [here](https://github.com/inspektor-gadget/inspektor-gadget/pull/796#discussion_r949431381):
> `eventtypes.Event` is used to carry **messages** from the tracer to the client. Each time a gadget produces output it's marshaled into a structure that contains this type, then it's unmarshaled on the client and according to the kind of gadget it could be printed to the screen (trace, snapshot), or saved for future processing (top). I think the `Event` name is misleading, as this is actually used for gadgets that are not event based, like snapshot. 
>

In addition, we are not using `eventtypes.Event` for all the gadgets. It leads to not being able to manage the special events (errors and warnings) in a common place for all the gadgets. PR https://github.com/inspektor-gadget/inspektor-gadget/pull/796 was an attempt, but it was too tricky and not clean enough.

## Proposal

@mauriciovasquezbernal's proposal:

I see that `eventtypes.Event` is like an "message header" that indicates the kind of event and some debugging information. I'm thinking to rework this in a different way:

1. Rename Event to `DataHeader` and remove `CommonData` from it, leaving only the type and message.
2. Modify types of different gadgets to embed this structure within their types. 
   - Tracers on their Event types (as currently done, they'll have to add CommonData since it's not on eventtypes.Event anymore)
   - Toppers on their "[Event](https://github.com/kinvolk/inspektor-gadget/blob/120ffd1b1ff12012ab7ca1ee6f93b2fea18843de/pkg/gadgets/top/file/types/types.go#L75)" (to be renamed?) type too
   - Profilers on their [Report](https://github.com/kinvolk/inspektor-gadget/blob/120ffd1b1ff12012ab7ca1ee6f93b2fea18843de/pkg/gadgets/profile/cpu/types/types.go#L26) type
   - I think snapshotters should define a new type that wraps the current event:
```golang
type Event struct {
  eventtypes.DataHeader

  Processes/Sockets []Process/Socket
}

type Process/Socket struct {̣ <-- current Event type
```

3. We can know handle the special event in the same way in all gadgets. (Their "Event" have the same header).

**Comment by mauriciovasquezbernal** [comment]
@blanquicet I'd propose to close this one as it's not relevant anymore with image-based gadgets. WDYT?

**Comment by blanquicet** [comment]
Closing as per previous comment.
