### ISSUE TITLE
[RFE] Clarify or align the JSON output with the Column output

### ISSUE THREAD

**Issue by burak-ok** [inspektor-gadget/inspektor-gadget#1146]
## Current situation

On some gadgets the output value differs when using the JSON output instead of the column output.

Example: `top tcp`
```go
IPVersion int    `json:"ipversion,omitempty" column:"ip,width:2,fixed"`
//....
cols.MustSetExtractor("family", func(stats *Stats) (ret string) {
		if stats.Family == syscall.AF_INET {
			return "4"
		}
		return "6"
	})
```

## Impact

It is quite confusing when switching between these two outputs.

## Ideal future situation

The two outputs are somehow aligned with each other or have a clear and valid reason to differ.
Adding units or joining arrays are probably valid reasons to increase the UX.
On others we should discuss how we proceed with them

## Additional information

Every gadget which has custom extractors:

- `top` gadgets
  - `block-io` columns
    - [ ] ``Write      bool   `json:"write,omitempty" column:"r/w,maxWidth:3"` ``
      - Transforms to `W` or `R`
  - `ebpf` columns
    - [ ] ``Pids               []*PidInfo `json:"pids,omitempty" column:"pid"` ``
      - Prints only the first pid
    - [ ] ``CurrentRuntime     int64      `json:"currentRuntime,omitempty" column:"runtime,order:1001,align:right"` ``
      - Does conversion + unit printing through `time.Duration`
    - [ ] ``CumulativeRuntime  int64      `json:"cumulRuntime,omitempty" column:"cumulruntime,order:1003,hide"` ``
      - Does conversion + unit printing through `time.Duration`
    - [ ] ``TotalRuntime       int64      `json:"totalRuntime,omitempty" column:"totalruntime,order:1005,align:right,hide"` ``
      - Does conversion + unit printing through `time.Duration`
    - [ ] ``MapMemory          uint64     `json:"mapMemory,omitempty" column:"mapmemory,order:1007,align:right"` ``
      - Does conversion + unit printing through units.BytesSize`
  - `file` columns
    - [ ] ``ReadBytes  uint64 `json:"rbytes,omitempty" column:"r_kb"` ``
      - Converts to KB through divison by `1024`. No units printed. At least the column name has a suffix `_kb`
    - [ ] ``WriteBytes uint64 `json:"wbytes,omitempty" column:"w_kb"` ``
      - Converts to KB through divison by `1024`. No units printed. At least the column name has a suffix `_kb`
    - [ ] ``FileType   byte   `json:"fileType,omitempty" column:"T,maxWidth:1"` // R = Regular File, S = Socket, O = Other ``
      - Converts the byte to a string
  - `tcp` columns
    - [ ] ``Family    uint16 `json:"family,omitempty" column:"ip,maxWidth:2"` ``
      - Prints `4` when `Family == syscall.AF_INET`, else `6`
    - [ ] ``Sent      uint64 `json:"sent,omitempty" column:"sent,order:1002"` ``
      - Converts to KB through divison by `1024`. No units printed. No suffix `_kb`
    - [ ] ``Received  uint64 `json:"received,omitempty" column:"recv,order:1003"` ``
      - Converts to KB through divison by `1024`. No units printed. No suffix `_kb`
- `trace` gadgets
  - `exec` columns
    - [ ] ``Args      []string `json:"args,omitempty" column:"args,width:40"` ``
      - Does a `Join(Args, " ")`
  - `mount` columns
    - [ ] ``Flags     []string `json:"flags,omitempty" column:"flags,width:24,hide"` ``
      - Does a `Join(Flags, " | ")`
  - `tcp` columns
    - [ ] ``Operation string `json:"operation,omitempty" column:"t,width:1,fixed"` ``
      - Maps `"accept" => "A"`, `"connect" => "C"`, `"close" => "X"`, `"unknown" => "U"` and everything else to `"U"`

**Comment by alban** [comment]
Reopen.

In the builtin dns gadget, we have the following json output:
```json
"pktType":"HOST"
```

But this field can be selected with a different CLI flag: `--filter=type:HOST`

See:
https://github.com/inspektor-gadget/inspektor-gadget/blob/v0.27.0/pkg/gadgets/trace/dns/types/dns.go#L54

**Comment by mauriciovasquezbernal** [comment]
With image based gadgets the same field name is used for both outputs, columns and json, so I don't think this issue is relevant anymore.
