### ISSUE TITLE
[RFE] Tracing network connections and aggregated statistics

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1164]
## Current situation

We have the following gadgets that can list network connections:
* [tcpdump](https://github.com/inspektor-gadget/inspektor-gadget/pull/1097) (not merged yet). This can trace all packets but too intensive to trace everything all the time.
* [tcp trace gadget](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/guides/trace/tcp.md): only tcp, and does not aggregate events.
* [network gadget](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/guides/trace/network.md). This aggregates connections but does not gives statistics and some data is missing (source IP, process names).

## Impact

There are no ideal gadgets to analyse all network connections (udp + tcp) with enough metadata (process names, packet counts, byte counts, source IP) and with low performance impact to enable all the time.

## Ideal future situation

It would be good to have something intermediate. It would need to have the following metadata:
- process: uid, pid, ppid, comm, exe, cwd
- network protocol
- local ip
- remote ip
- remote port
- remote pod / service
- container metadata (container id, pod name & namespace)
- container image (see also #1310)
- packet count, byte count

## Implementation options

Network packet capture would not give the process metadata directly.

**Comment by mauriciovasquezbernal** [comment]
We need to scope this better to understand the purpose of this issue.

**Comment by mauriciovasquezbernal** [comment]
@alban I' wondering what format should this gadget present the information? I see that the `top tcp` is very similar to what you described here:

```bash
CONTAINER                               PID         COMM             IP LOCAL                 REMOTE                SENT                  RECV                
mycontainer                             90482       wget             4  172.17.0.3:47282      159.89.192.182:80     0B                    27.65MiB 
```
