### ISSUE TITLE
[EPIC] docs: Improve structure 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1184]
This issue tracks a documentation restructuring for Inspektor Gadget. Image-based gadgets are now the first focus of Inspektor Gadget and the documentation doesn't reflect it very clearly. There is also some ongoing work on different PRs and issues but we need to define the structure to keep it aligned. 

# Related Issues

- #2151
- #2374
- #2727

# Proposal 

This is a proposal for the documentation structure of Inspektor Gadget

### Readme
- Badges
- Quick Intro
- Link to website

### Contributing
- setup dev environment
- tests
- ...

## Website

Published on https://www.inspektor-gadget.io/docs
Docs stored in https://github.com/inspektor-gadget/inspektor-gadget/tree/main/docs

### Intro 

Landing page of https://www.inspektor-gadget.io/docs

- What is Inspektor Gadget? (Intro) 
- gif demo (single or multiple gadgets TBD)
- Briefly describe the core concepts (then add link to full documentation)
  - Gadgets
  - Enrichment 
  - Filtering 
  - APIs 
- Environments where it can work (introduction with few details)
  - Kubernetes (kubectl-gadget) 
  - linux hosts (ig)
 - Links to:
   - requirements
   - architecture
   - contributing

### Getting started 
- Installing on Kubernetes
- Installing on Linux
- Installing on Mac? 
- Using a Gadget

### Core concepts

(#3229)

- Gadgets 
  - Link "official-gadgets"
- Architecture 
- Operators
  - Concept
  - Initialization ("optional" behavior)
  - Existing operators (bpf, wasm, btfgen, localmanager, kubemanager, etc)
- Enrichment 
- User space processing 
- Data Export
  - Prometheus 
  
### Components / Binaries 
- kubectl-gadget
- ig 
- gadgetctl

### (Official) Gadgets

Documentation for the gadgets we provide. Related #2727 and #2374

- Gadget description: What the gadget does, what information it provides, etc. 
- Running the gadget (ig and kubectl-gadget?)
- Gadget parameters
- Kernel requirements

### API 

(#3250)
 
How to use Inspektor Gadget from an API 

- Golang API (examples already present in https://github.com/inspektor-gadget/inspektor-gadget/tree/main/examples/gadgets)
- gRPC API (some things in https://github.com/inspektor-gadget/inspektor-gadget/tree/main/examples/gadgets/grpc/custom_operator)

### Gadget Developers

(#3208)

This section covers the documentation for folks that want to write gadgets.

- Getting started: Quick link that explains how to create a gadget from: https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/devel/hello-world-gadget.md
- API
  - For ebpf programs (e.g. gadget_socket_lookup)
  - For wasm programs
- OCI format?
- Gadget metadata
- image build command
  - IG_SOURCE_PATH for in-tree gadgets
- Testing 

### Legacy 

(#3228)

There are still things we need to support for a while, so I'd suggest to move then to a legacy folder

- built-in gadgets
- trace crd

## TBD

- Where to put CLI docs like https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/core-concepts/images.md?

**Comment by alban** [comment]
I added a wish list of reference documentation in #2151.
