### ISSUE TITLE
Allow to deploy gadget differently on different nodes

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#125]
The `kubectl deploy` options apply to all the nodes in the cluster. If the node has different nodes types it could be a problem because the option could not be valid for all of them.

This issue proposes to:
- Allow to have different `runc-hooks-mode` per node.
- Allow to mark some nodes to avoid deploying IG there.

A possible implementation could be to define these options by annotation in the nodes.

**Comment by marga-kinvolk** [comment]
I'm not sure if this falls under the same umbrella or not, but while testing IG out, I noticed that if a new node is spawned after the gadget pods were deployed, the new node doesn't get a gadget pod.

**Comment by marga-kinvolk** [comment]
Mauricio, you added this to 0.6.0, is there a reason why this issue is particularly relevant now?

**Comment by mauriciovasquezbernal** [comment]
I added it because of the original name "Improve multi-node cluster support". 
I was thinking to:
- Check scalability 
- Check what happens when some nodes are not ready?

**Comment by marga-kinvolk** [comment]
Ah, well, "improve" is almost never a good title for an issue, as we usually never finish improving things and it ends up being a catch-all issue that can never be closed.

Regarding scalability, there's #519. Regarding nodes not being ready, I guess we should file a separate issue, as this one isn't it.

**Comment by mauriciovasquezbernal** [comment]
I created https://github.com/kinvolk/inspektor-gadget/issues/632 with the problem I faced some days ago. 

Regarding this issue, I think the part about avoid deploying IG in some nodes could be useful. I imagine there are cases where users want to deploy to some specific nodes or avoid deploying to specific ones. I think it can be implemented while reworking the deploy command -> https://github.com/kinvolk/inspektor-gadget/issues/123.

**Comment by mauriciovasquezbernal** [comment]
Perhaps we can implement something simple like letting the user specify the labels to use for the node selector, i.e. deploy Inspektor Gadget only on nodes with some labels. But maybe it's too complicated and in those cases the user should modify the yaml manifest directly.

**Comment by mauriciovasquezbernal** [comment]
> Allow to have different runc-hooks-mode per node.

We're trying to keep this as hide as possible from users, do in the time being we won't implement an option to specify different values for different nodes. 

> Allow to mark some nodes to avoid deploying IG there.

https://github.com/inspektor-gadget/inspektor-gadget/pull/1187 fixes it.

Closing this.
