### ISSUE TITLE
[RFE] ci: Run local-gadget Kubernetes integration tests on AKS

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#1273]
## Current situation

Currently, local-gadget Kubernetes integration tests are run on Minikube with all the available runtimes: docker, cri-o, containerd. However, they are not running on AKS.

## Implementation options

An option to copy the `local-gadget` binary into the node could use the same approach of [`kubectl-node-shell`](https://github.com/kvaps/kubectl-node-shell) or use it directly (?). Then, to run it, we could still use again `kubectl-node-shell` or [`az`](https://learn.microsoft.com/en-us/cli/azure/vmss/run-command?view=azure-cli-latest#az-vmss-run-command-invoke) or [`kubectl-az`](https://github.com/Azure/kubectl-az).

**Comment by mauriciovasquezbernal** [comment]
What about implementing this by testing the azure kernerls in https://github.com/inspektor-gadget/inspektor-gadget/issues/1343?

**Comment by blanquicet** [comment]
> What about implementing this by testing the azure kernerls in #1343?

In terms of backward compatibility I think we should. In this way, if users are using an old cluster or they create it using an specific Kubernetes version like `az aks create -g MyResourceGroup -n MyManagedCluster --kubernetes-version <some-specific-version>`, we can be sure we support most of them (or even all 🙂).

However, we should have to keep an eye on the updates AKS does, because the idea is to support it out-of-box. So, if users just do `az aks create -g MyResourceGroup -n MyManagedCluster` which will use a default version, we must support it. And the only way to be sure we do it, is to use that same command and leave it uses the default version, don't you think?
