### ISSUE TITLE
[RFE] Filter containers by container image + Enrich events by container image

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1310]
## Current situation

Users can filter containers with the following selectors:
- `--node`
- `--namespace`
- `--podname`
- `--containername`

But they cannot filter by container image.

Additionally, events are enriched with node, namespace, pod, container but not with the container image.

## Impact

Sometimes a micro service application uses several Kubernetes deployments with the same image and it is not possible to get events from all of them.

Example: https://github.com/microservices-demo/microservices-demo/tree/master/deploy/kubernetes/manifests
This has several deployments with the `mongo` image

If we notice that `mongo` has an issue but we don't know yet which  namespace, pod or deployment it is, it would be useful to have a `--image` filter.

Additionally, reporting container images in events has been requested by users in #1164.

```
$ kubectl gadget trace exec -A -o custom-columns=node,namespace,pod,container,image,comm,pid
Error: creating parser: invalid columns: image
```

## Ideal future situation

Implement `--image=` to most gadgets where it makes sense.

There should be a way to match both `busybox`, `library/busybox`, `busybox:1.35`. It could be done with Golang's [regexp](https://pkg.go.dev/regexp) or [glob](https://pkg.go.dev/github.com/gobwas/glob).

Additionally, we can add the image in events:
```
$ ./kubectl-gadget trace exec -A -o custom-columns=container,image
CONTAINER  IMAGE
busybox    busybox:latest
```

## Implementation options

The different backends for the container-collection packages need to feed the container image:

* WithContainerRuntimeEnrichment
  * CRI-O starts OCI containers with the following annotation:
    * "io.kubernetes.cri-o.ImageName": "k8s.gcr.io/coredns/coredns:v1.8.6"
    * See pkg/container-utils/oci-annotations/resolver_crio.go
  * containerd starts OCI containers with the following annotation:
    * "io.kubernetes.cri.image-name": "k8s.gcr.io/coredns/coredns:v1.8.6"
    * See pkg/container-utils/oci-annotations/resolver_containerd.go
* WithPodInformer
  * The pod spec contains a `image` field.

`ContainerSelectorMatches()` needs to be updated to support images.

## Additional information

Sysdig can filter events based on the container image with the `%container.image` filter.

**Comment by alban** [comment]
Additional requirements for this feature request:
1. There should be fields for both the image tag and the image digest
2. We should be able to filter by prefix, for example filter all container image with the prefix "localhost:5000/".

The filter by prefix is is now possible with `--filter` and using the regular expression feature:
```
$ ./ig trace exec -h
...
  -F, --filter strings         Filter rules
                                 A filter can match any column using the following syntax
                                   columnName:value       - matches, if the content of columnName equals exactly value
                                   columnName:!value      - matches, if the content of columnName does not equal exactly value
                                   columnName:>=value     - matches, if the content of columnName is greater or equal to the value
                                   columnName:~value      - matches, if the content of columnName matches the regular expression 'value'
                                                            see [https://github.com/google/re2/wiki/Syntax] for more information on the syntax
```

But this filter is currently done in userspace.

Filtering on the container name is already done in eBPF, it should be possible to do the filtering for the image name in eBPF as well (no need to do regexp in eBPF, we just need to update the filtering eBPF map like we do for container names).

**Comment by claudiamarcubina** [comment]
Working on it. Current status:
|            | Initial containers | New containers |
|------------|--------------------|----------------|
| containerd | ?                  | WIP            |
| cri-o      | ?                  | WIP            |
| docker     | ?                  | ?              |

**Comment by claudiamarcubina** [comment]
Current status:

#### In review: 

- #1682 : added `ImageName` to events 

#### To be done:

- [ ] add imageDigest to events
- [ ] implement filtering

**Comment by alban** [comment]
I tested filtering with:
```
$ sudo -E ./ig trace exec -F 'runtime.containerImageName:busybox'
```
It works fine.

It is done in userspace. Filtering in ebpf for performance optimization could be part of #2068.

**Comment by claudiamarcubina** [comment]
Closing. Moved the blocker to new issue: #2273
