### ISSUE TITLE
[RFE] IG mode with static configuration with static tracers

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1401]
## Current situation

* IG is deployed automatically with `kubectl deploy` or manually with the yaml provided by `kubectl deploy`; either way it contains the DaemonSet, the Trace CRD and other RBAC configuration.
* The set of tracers to use is defined dynamically with either the Trace CR (or possibly later with other APIs: gRPC or kubectl-exec API, see work in progress [PR#1396](https://github.com/inspektor-gadget/inspektor-gadget/pull/1396)); either way, it is dynamic and it needs a process to act as a client to the API.

## Impact

The dynamic definition of tracers is fine for some use cases (quick debugging session) but not when users want to permanently enable some gadgets (exporting data in a file or in a Prometheus metrics endpoint).

We run in the following problems with the current setup:
* When deploying the set of yamls from IG, we also need a component deploying the Trace CRs or implementing the gRPC client.
* When a new node is added to the cluster (or when a node is rebooted), we need a client to enable the traces on the new node dynamically
* CRD are not namespaced in Kubernetes, so it is impossible to deploy IG twice with different static configuration

## Ideal future situation

In addition to the current dynamic configuration of tracers via CRD or other gRPC API, we should have a way to deploy Inspektor Gadget statically, with a static tracers.

## Implementation options

* The gadget pod spec has an environment variable to enable or disable CRD. This would control a parameter to gadgettracermanager. It would be enabled by default to keep the current mode but allow users to disable it and deploy IG with static tracers.
* A ConfigMap contains the list of tracers (for example enabling the trace dns gadget with the Prometheus output). The ConfigMap can be mounted in the gadget pod and gadgettracermanager is started with `--static-tracers=/etc/gadget/static-tracers.yaml`
* Optionally: `kubectl gadget deploy` could have additional options:
  * --trace-controller=false
  * --static-tracers=./my-static-tracers.yaml
  * --namespace=gadget2

## Additional information

* https://github.com/inspektor-gadget/inspektor-gadget/pull/1396
* Previous discussion about static configuration https://github.com/inspektor-gadget/inspektor-gadget/issues/673#issuecomment-1184069295
* Prometheus output https://github.com/inspektor-gadget/inspektor-gadget/pull/1384

cc @flyth

**Comment by mauriciovasquezbernal** [comment]
Related https://github.com/inspektor-gadget/inspektor-gadget/issues/1932

**Comment by mauriciovasquezbernal** [comment]
There is a new issue with more information in #2492. I'll close this one, feel free to add information to the new issue in case something is missing.
