### ISSUE TITLE
Implement initial support for `bpftrace`

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1432]
From #1342 

Implement support to run bpftrace scripts on the cluster. This initial support consists on running the bpftrace binary and showing the output to the user.

```bash
# run on a single node 
$ kubectl gadget bpftrace --node foo -e `tracepoint...`

# run on multiple nodes 
$ kubectl gadget bpftrace -e `tracepoint...`
```

This phase doesn't provide any support for filtering nor enriching data by namespace/pod/container etc.

**Comment by blixtra** [comment]
I don't think we should call this gadget "bpftrace". The reason for this is that while we want to have compatibility with `bpftrace`, I don't think this will be sufficient for our needs. We already know we will need to add enrichment for containers and kubernetes. I think as we build this out we will find further things that we should add which takes us further from `bpftrace`

My proposal is that we call this gadget "script". When one calls this gadget with a single line script or file with a ".bt" extension which needs no enrichment then we only need `bpftrace`. But if it's run with a single line script or a file with an ".ig" extension which does need enrichment then we are no longer `bpftrace`-compatible.

But I think the real fun is what we may be able to do on top of all this by extending the scripting. That still needs brainstorming, though.
