### ISSUE TITLE
[RFE] Trace exec: additional fields: cwd, exepath, tty, sid, gid, loginuid

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1490]
## Current situation

The trace exec gadget already has the following fields:
```
$ ig trace exec -h
...
Available columns:
  args
  comm
  container
  mntns
  pid
  ppid
  ret
  timestamp
  uid
```

But it does not have the following columns:
- container (separate issue for this: [#1310](https://github.com/inspektor-gadget/inspektor-gadget/issues/1310))
  - container id (IG has this field internally but it is not exposed to the user yet)
  - image tag
  - image digest
- process info
  - [x] cwd (#1700)
  - [x] exepath
  - [x] tty (not needed)
  - [x] sid (#1705)
- user info
  - [x] gid (#1666)
  - [x] loginuid (#1704)

sysdig provides those fields but not Inspektor Gadget.

## Impact

The context around the exec events are not detailed enough for some of our users.

## Ideal future situation

- All of the additional fields are added.
- Some of the fields can be generic and should be available in all trace gadgets.

## Implementation options

Some of the fields can be straightforward to get in eBPF.

sysdig gets the `cwd` by keeping track of the directory for all processes in a eBPF map and using a kprobe on chdir to update that map.

## Additional information

[ Please Add any information that does not fit into any of the above sections here ]

**Comment by mauriciovasquezbernal** [comment]
I tried to check how easy it's to get the different fields:

- [sid](https://github.com/inspektor-gadget/inspektor-gadget/blob/d192da3b4ce9de65584e82726d9299406e790828/pkg/arm64/vmlinux/vmlinux.h#L1035-L1036)
- gid through the `bpf_get_current_uid_gid` heper
- [loginuid](https://github.com/inspektor-gadget/inspektor-gadget/blob/d192da3b4ce9de65584e82726d9299406e790828/pkg/arm64/vmlinux/vmlinux.h#L1034-L1035) 
- `exepath` is `pathname` in execve, it's currently read in args[0]. 
- `cwd`: we can use task -> [fs](https://github.com/inspektor-gadget/inspektor-gadget/blob/d192da3b4ce9de65584e82726d9299406e790828/pkg/arm64/vmlinux/vmlinux.h#L1019-L1020) ->{[root, pwd](https://github.com/inspektor-gadget/inspektor-gadget/blob/d192da3b4ce9de65584e82726d9299406e790828/pkg/arm64/vmlinux/vmlinux.h#L7749)}. However we need to investigate how to translate `struct path` to a string, perhaps `bpf_d_path` can be used.
- `tty`: It seems to me it's the most difficult one. Perhaps task -> [files](https://github.com/inspektor-gadget/inspektor-gadget/blob/d192da3b4ce9de65584e82726d9299406e790828/pkg/arm64/vmlinux/vmlinux.h#L1021) and somehow from it derive the file associated to fd0 and it's path. In this case the same issue as above, regarding  struct path -> string conversion, is still valid.

**Comment by alban** [comment]
> tty: It seems to me it's the most difficult one. Perhaps task -> [files](https://github.com/inspektor-gadget/inspektor-gadget/blob/d192da3b4ce9de65584e82726d9299406e790828/pkg/arm64/vmlinux/vmlinux.h#L1021) and somehow from it derive the file associated to fd0 and its path. In this case the same issue as above, regarding struct path -> string conversion, is still valid.


Falco defines the tty as follows:
> proc.tty	UINT32	The controlling terminal of the process. 0 for processes without a terminal.

and it is available via: `task->signal->tty->index` (see [extract_from_kernel.h#L630-L661](https://github.com/falcosecurity/libs/blob/d1f550a596b2f04db7b5853bb92c68baeeae8cb1/driver/modern_bpf/helpers/extract/extract_from_kernel.h#L630-L661))

@johananl @mauriciovasquezbernal
