### ISSUE TITLE
Support CRI `v1` and `v1alpha` at the same time

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1507]
#1392 switched the CRI api from `v1alpha2` to `v1`, however it created an issue (#1484) as containerd v1.5 doesn't support `v1`, #1485 reverted it back to `v1alpha2` to support containerd v1.5. 

Different runtimes removed (or are removing) support for v1alpha (https://github.com/inspektor-gadget/inspektor-gadget/pull/1485#issuecomment-1494116963), hence we should make Inspektor Gadget compatible with both versions. containerd and cri-o support(ed) both versions at the same time https://github.com/cri-o/cri-o/pull/4408 & https://github.com/containerd/containerd/pull/5619, hence I think this is doable from a technical point of view.

**Comment by mqasimsarfraz** [comment]
In case we want to bump the k8s.io/cri-api to >= v0.26.0 we need to copy cri-api v1alpha2 locally as done [here](https://github.com/containerd/containerd/pull/7656). In case we want to support v1alpha2 for longer period ?

**Comment by mauriciovasquezbernal** [comment]
IMO we need to continue supporting v1alpha2 for a long period. If the solution you proposed above is not too difficult I'd suggest to implement this now to be able to update the k8s.io/cri-api version.

**Comment by mqasimsarfraz** [comment]
> IMO we need to continue supporting v1alpha2 for a long period. If the solution you proposed above is not too difficult I'd suggest to implement this now to be able to update the k8s.io/cri-api version.

The proposed solution shouldn't be hard to implement. Makes sense to be able to update k8s.io/cri-api version. I reopened the issue to track it.
