### ISSUE TITLE
[RFE] Find a way to provide `bpftrace` for `arm64`

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#1530]
## Current situation

[ Please describe the current situation you would like to have improved ]

## Impact

[ Please describe the impact the lack of the feature requested is creating ]

## Ideal future situation

[ Please describe the future situation after the improvement was implemented ]

## Implementation options

[ Optional: please provide one or more options for implementing the feature requested ]

## Additional information

[ Please Add any information that does not fit into any of the above sections here ]

**Comment by mauriciovasquezbernal** [comment]
I made some progress in https://github.com/inspektor-gadget/bpftrace/commit/655f19550458c1f16e1acfd8ba2b891df6794779, feel free to take it if you think it's useful.

**Comment by mauriciovasquezbernal** [comment]
After 4 hours of cross compilation on my machine, I was able to push the image to https://hub.docker.com/repository/docker/mauriciovasquezbernal/bpftrace/general. I haven't try it out with Inspektor Gadget yet.

**Comment by mauriciovasquezbernal** [comment]
I tested it and works fine on arm64, the image I used is in https://hub.docker.com/repository/docker/mauriciovasquezbernal/gadget/. 

We need to think about the compilation time, specially for the llvm image since it takes  time is 4hours in my machine. I don't think it's suitable for github actions. 
-

**Comment by mauriciovasquezbernal** [comment]
I need to be more clear about my terminology. I used `docker buildx` with qemu to **emulate** the whole compilation on arm64.
