### ISSUE TITLE
gadgets: Standardize common info gadgets provide 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1567]
We should be sure that all gadgets provide the same common information (when technically possible for sure)

This is the list of common fields all gadgets should provide: ( ❓ indicates that it needs more discussion)

- Kubernetes 
  - ✅ node
  - ✅ namespace
  - ✅ pod 
  - ❓pod uuid
  - ✅ container name
  - ✅ containerID
  - ✅ container image (tag and digest according to https://github.com/inspektor-gadget/inspektor-gadget/issues/1310)
  - ❓pid1 of the container
- container runtime
  - ✅ runtime name 
  - ✅ container name
  - ✅ containerID
  - ✅ container image (same as above in k8s)
-  process related
   - ppid (#2645)
   - pid  
   - tid 
   - comm 
   - pcomm
   - user related
     - uid https://github.com/inspektor-gadget/inspektor-gadget/pull/1666
     - gid https://github.com/inspektor-gadget/inspektor-gadget/pull/1666

### Implementation options 

We could create some common data structures to reuse in the different gadgets (https://github.com/inspektor-gadget/inspektor-gadget/issues/250). Something like could work:
- K8sInfo
- ContainerInfo
- ProcessInfo
- UserInfo

**Comment by blixtra** [comment]
I think we should consider prioritizing this. We are getting adhoc requests from users to add a field here and there. It would be better to do this as part of a core set of data that we could add across the board.

**Comment by alban** [comment]
I updated the issue description above with ✅ (when implemented already) and ❓(when more discussion required).

There are two tasks in this issue:
1. Adding missing fields in some gadgets
2. Making group of fields in generic structs

Categories of fields:

* ✅ **Kubernetes** and **container runtime**: the implementation is already generic (and not per-gadget)
* 🚧 **process related**: this is currently per-gadget. fsnotify added a `struct process` (#3438) but the struct definition is so far in the fsnotify gadget and not for all gadgets. Before making it more generic, we need to fix the following:
  * #3459 
  * #3460
  * #2684

Regardless that the struct process is not generic, here is the current status of some fields for some gadgets:
-  ✅ implemented
- 🚧 work in progress
- ❌ not implemented
- ❓need to check current status

| gadget | ppid | pid | tid | pcomm | comm | uid/gid | cwd | exepath |
|---|---|---|---|---|---|---|---|---|
| builtin trace-dns | 🚧 #2684 | ✅ | ✅ | 🚧 #2684 | ✅ | 🚧 #2684 | 🚧 #2684 | 🚧 #2684 |
| builtin trace-network | ❌ | ✅ | ✅ | ❌ | ✅ | ❌ | ❌ | ❌ |
| builtin trace-exec | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ❓ |
| image-based trace_dns | 🚧 #2684 | ✅ | ✅ | 🚧 #2684 | ✅ | ✅ | ❌ | ❌ |
| image-based trace_exec | ✅ | ✅ | ❌ | ❌ | ✅ | ✅ (but without UidGidResolver) | ❌ | ❌ |
| image-based fsnotify | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ❌ | ❌ |

**Comment by mauriciovasquezbernal** [comment]
> we need to fix the following:

Why is https://github.com/inspektor-gadget/inspektor-gadget/issues/3460 a blocker for this?

I'd say we need to define the following structs:

```c
struct process {
	// Note it's probably not valid C syntax but you all get the idea. TODO:
	// Another possibility is to have a full process struct here again, but that
	// would create recursion issues. (and probably we don't want that all
	// information about the parent)
	struct parent {
		u32 pid;
		u32 comm;
		u32 tid; // ???
	};

	u32 pid;
	u32 tid;
	char comm[];

	char exepath[]; // optional?
	char cwd[]; // optional?
};

// TODO: should it be part of process?
struct user {
	// user and group names automatically enriched
	u32 id;
	u32 gid;
	u32 loginuid; // ??
	u32 sessionid; // ??
};
```

Then we should have functions to fill those structures  and remove all duplicated code from different gadgets. 

WDYT?

**Comment by alban** [comment]
> Why is #3460 a blocker for this?

You're right, it is not a blocker if you don't put the `mntns_id` inside your `struct process`.

> // TODO: should it be part of process?
> struct user {

I think that should be part of process, yes.

> Then we should have functions to fill those structures and remove all duplicated code from different gadgets.

That sounds good.
