### ISSUE TITLE
trace/mount: Not working for containers without SYS_ADMIN

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1589]
The `trace mount` is not working for containers that don't have the `SYS_ADMIN` capability. I'm opening this issue in this repo to track this but it's not related to Inspektor Gadget:

### Inspektor Gadget reproducer

Start the trace mount on a terminal

```bash
$ sudo ./ig trace mount
CONTAINER                         COMM             PID        TID        CALL
```

Run a container that executes `umount` (exact same thing happens with `mount`)

```bash
$ sudo docker run -ti --rm --cap-add SYS_ADMIN --name=admin ubuntu /bin/bash -c "umount /foo"
umount: /foo: no mount point specified.
```

The event is logged in the first terminal

```bash
CONTAINER                         COMM             PID        TID        CALL                                                                                 
admin                             umount           236605     236605     umount("/foo", ) = -2
```

Running the same container image without SYS_ADMIN doesn't log any event:

```bash
$ sudo docker run -ti --rm --name=standard ubuntu /bin/bash -c "umount /foo"
umount: /foo: must be superuser to unmount.
```

```bash
CONTAINER                         COMM             PID        TID        CALL                                                                                 
admin                             umount           236605     236605     umount("/foo", ) = -2
```

### bpftrace reproducer

After going deep, I found out that it's not related to Inspektor Gadget, for some weird reason the `sys_enter_umount` is not invoked for the container without SYS_ADMIN:

```bash
$ sudo bpftrace -e 'tracepoint:syscalls:sys_enter_umount /comm=="umount"/ { printf("enter umount\n"); } tracepoint:syscalls:sys_exit_umount /comm=="umount"/ { printf("exit umount\n"); }'
Attaching 2 probes...
```

```bash
$ sudo docker run -ti --rm --cap-add SYS_ADMIN --name=admin ubuntu /bin/bash -c "umount /foo"
umount: /foo: no mount point specified.
```

Both tracepoints are called in this case:

```bash
...
enter umount
exit umount
...
```

```bash
$ sudo docker run -ti --rm --name=standard ubuntu /bin/bash -c "umount /foo"
umount: /foo: must be superuser to unmount.
```

Only the sys_exit_umount is called in this case:

```bash
...
exit umount
...
```

I reproduced it in both, `6.2.0-060200-generic` and `5.15.0-58-generic` kernel versions on amd64.

**Comment by alban** [comment]
Can you strace the process? I think it runs stat() on "foo", or uses getuid(), it notices the problem and does not even try the mount/umount system call.

**Comment by mauriciovasquezbernal** [comment]
According to strace it does the syscall:

```bash
$ docker run -ti --rm --name=standard ubuntu /bin/bash -c "apt-get update && apt-get install strace -y && strace umount /foo"

...
umount2("/foo", 0)                      = -1 EPERM (Operation not permitted)
....

```

**Comment by mauriciovasquezbernal** [comment]
I don't have a 5.10 kernel available right now, I tried with `5.4.0-137-generic` and the issue is the same. I'm wondering now how I tested it on https://github.com/inspektor-gadget/inspektor-gadget/pull/1099.

**Comment by alban** [comment]
Try Docker with seccomp disabled. Docker configures seccomp without allowing mount when cap_sys_admin is not set. Then, it's blocked by seccomp before the tracepoint.

**Comment by alban** [comment]
The capabilities gadget should clarify that in the documentation so that users know they have to disable seccomp when trying to find the capabilities required by a container. It will become a problem on Kubernetes too when seccomp becomes enabled by default in new versions.

**Comment by mauriciovasquezbernal** [comment]
```bash
$ sudo docker run -ti --rm --security-opt=seccomp:unconfined --name=admin ubuntu /bin/bash -c "umount /foo"
umount: /foo: no mount point specified.
```
works fine. 

Now the point is: why the `sys_exit_umount` is tracepoint is triggered when using seccomp? If `sys_enter_umount` is not triggered I'd expect `sys_exit_umount` not to be triggered as well. Is this a standard behavior on the kernel?

**Comment by mauriciovasquezbernal** [comment]
I don't think that's the path as in this case the process in not being killed. 

I think this is the reason. In [`syscall_trace_enter`](https://elixir.bootlin.com/linux/v6.3/source/kernel/entry/common.c#L48), `trace_sys_enter` is called after `__secure_computing()`. On [`syscall_exit_work`](https://elixir.bootlin.com/linux/latest/source/kernel/entry/common.c#L228), `trace_sys_exit` is always called. I'm wondering if this behavior is correct, IIUC `ptrace` is called in both cases.
