### ISSUE TITLE
Container OciConfig field is nil for pods started before IG

### ISSUE THREAD

**Issue by johananl** [inspektor-gadget/inspektor-gadget#1613]
## Description

When tracing a pod which was started before GadgetTracerManager was started, the `Container.OciConfig` is nil:

https://github.com/inspektor-gadget/inspektor-gadget/blob/08056695b8cfc02698afcbd41add88acfac4d8cf/pkg/container-collection/containers.go#L42

When tracing a pod which was started after GadgetTracerManager was already running, `Container.OciConfig` is populated.

## Impact

I'm implementing an operator which relies on `OciConfig` for enriching events with k8s volume information.

## Environment and steps to reproduce

1. Print or log `Container.OciConfig` in an existing operator (or add a dummy operator which does the same).
2. Deploy a container, e.g. using `kubectl run nginx --image nginx`.
3. Deploy IG.
4. Run a trace which uses the operator from step 1 and watch the GadgetTracerManager logs. `OciConfig` is nil.

## Expected behavior

I expected `OciConfig` to not be nil.

## Additional information

From discussing this with @mqasimsarfraz it seems we're using different data structures for container information when operating on containers spawned prior to spawning the IG pod and containers spawned after IG. Sounds to me like this is a recipe for inconsistencies such as the one described in this issue. I wonder if it makes sense to consolidate the relevant logic.

**Comment by blanquicet** [comment]
IIRC, we haven't find any component from which we can retrieve the OciConfig information. However, in PR #1233, I noticed that Containerd is storing it, check [here](https://github.com/inspektor-gadget/inspektor-gadget/pull/1233#discussion_r1061419675). Maybe Docker does the same.

**Comment by mqasimsarfraz** [comment]
I am not sure if we can get `OciConfig` via runtime clients espcially `CRI` api doesn't seem to be offering anything related to that. I am thinking if we can somehow get the `runc` root for given runtime (containerd/cir-o) and then get config via it, similar to how `runc list` works. @alban thoughts on this?

**Comment by alban** [comment]
It would be better to use a proper API when available.

If not available or too difficult, I wonder about a hack like this: 

```bash
for pid in $(./ig list-containers -r docker -o json|jq '.[].pid') ; do
    ppid=$(ps -o ppid= -p $pid)
    cat /proc/$ppid/cwd/config.json
done
```

It takes the parent process (containerd-shim-runc-v2 in my case) and find the config.json in its current working directory.

**Comment by mqasimsarfraz** [comment]
> IIRC, we haven't find any way to retrieve the OciConfig information for already running containers. However, in PR #1233, I noticed that Containerd is storing it, check [here](https://github.com/inspektor-gadget/inspektor-gadget/pull/1233#discussion_r1061419675). Maybe Docker does the same.

We can probably use `contained` client with `moby` namespace to get containers spec running via docker. What do you think?
