### ISSUE TITLE
[RFE] profile/tcprtt: Allow filtering by remote and/or local ports

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#1614]
The profile tcprtt gadget was added in PR https://github.com/inspektor-gadget/inspektor-gadget/pull/1517, but it doesn't allow filtering by local and/or remote ports. Notice that the BPF code already supports it. This issue needs to: Add flags, tests and documentation.

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/1828.
