### ISSUE TITLE
`ig`: Provide container image

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1640]
We provide the `ig` binary and different packages to install it as release artifacts. However, we don't have any container image with this available. It can be useful for some folks that don't want to download a binary but just execute `docker run ...` to get it on their systems. 

The scope of this issue is: 
- [x] Build and publish `ig` as a container image. (If we can make it a distroless one, that'd be great)
- [x] Document how to run this image
  - [x] By using docker (--privileged or caps, required mounts, etc)

**Comment by mauriciovasquezbernal** [comment]
We are missing pushing this to the container repo and documenting how to use it.

**Comment by alban** [comment]
#1787 addresses part 1 of this issue.

**Comment by mauriciovasquezbernal** [comment]
Closing as https://github.com/inspektor-gadget/inspektor-gadget/pull/1809 is merged.
