### ISSUE TITLE
[RFE] Containerized Gadgets as the Primary Gadget Type

### ISSUE THREAD

**Issue by blixtra** [inspektor-gadget/inspektor-gadget#1669]
I'd like us to reconsider our approach to BYOB (Bring Your Own BPF) gadgets that we are taking in https://github.com/inspektor-gadget/inspektor-gadget/pull/1527. Moving forward, it would be best to make containerized gadgets the default mode of operation for IG, effectively turning what we've called "BYOB gadgets" into what we'll refer to as simply "gadgets" from now on. Builtin gadgets should be explicitly referred to as "builtin gadgets".

In the interest of this transition, I propose a series of changes:

* Instead of byob gadgets living under a category, we should make commands for building, pulling, pushing, and running top-level commands for IG itself.
* In cases where IG can infer the gadget type through convention, it should do so.
* All gadgets should provide a config file within their container. This config file will hold any metadata that IG needs to run the gadget properly.
* A mechanism for unit and integration tests should be designed and implemented

For the near future and possible from the start we need to consider the following.
* We should provide a mechanism for users to create a config file that defines the execution of multiple gadgets as a unit. This config file should also be able to specify the type of interface or export format to use for this unit.
* It's not clear yet if for some specific cases we need the gadgets to provide their own user space code

This issue serves as a stepping stone towards a future where containerized gadgets are the norm in IG.

**Comment by mauriciovasquezbernal** [comment]
The design document for this was merged https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/design/002-containerized-gadgets.md and https://github.com/inspektor-gadget/inspektor-gadget/issues/1929 tracks all the implementation tasks. I'll close this one.
