### ISSUE TITLE
[RFE] Add option to cache to file

### ISSUE THREAD

**Issue by blixtra** [inspektor-gadget/inspektor-gadget#1679]
Issue #1678 deals with making the length of the cache configurable beyond the default of 1024 events. Building on that idea, it would be great if we could offer the user the ability to cache the output to a file. This opens up the possibility of a much larger and more persistent cache.

`ig` would write to the file if the in-memory cache limit is reached and continue doing so until the events are fetched by the client.

**Comment by flyth** [comment]
IMHO, it would be better to add "exporters" for persistence - as an addition to the output mode we currently have. An exporter could for example be a local file writer, but also an external target, like a log server (either using syslog or some other protocol). We briefly talked about those options last week.

Personally, I don't think IG should handle more complex caching by itself.
So, if for example you want to always have the last 24h of logs, use the syslog exporter and configure log rotation. Or export to a Tempo, Logstash etc. and configure retention there.

**Comment by blixtra** [comment]
That sounds like a good idea. Then it seems like we should decide on a standard set of exporters we want to have as a project and have a well defined interface for that for others to add their own exporters. Prometheus and syslog would be a good start. Perhaps an OTel exporter, too.
