### ISSUE TITLE
socket enricher: Use single instance for multiple gadgets

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1695]
The socket enricher is used by some networking gadgets to get process information. Currently, each gadget run has its own instance of the enricher, which is not optimal. 

The scope of this issue is to improve this to only create a single instance of the enricher and share it among the different running gadgets. 

## Implementation Options

- Ref count in `NewSocketEnricher()` and `Close()`: Implement a ref count logic to only create the enricher when it's needed and only release it when there are not any more users.
- As an operator: I feel that this can be implemented as an operator too. However, I'm not sure operators are designed for this purpose. 

@flyth  do you think an operator is a good fit for this case?

**Comment by flyth** [comment]
> @flyth do you think an operator is a good fit for this case?

Absolutely! Everything that has a global (and optionally a per-gadget-run) scope, that multiple concurrently running gadgets can get information from, is IMHO a good fit as an operator - especially, if there are no other dependencies. If not everything fits directly, we should try to expand our operator design to make it work.

**Comment by alban** [comment]
The difference with other operators is that in the socket enricher, the events are not enricher in userspace but in the ebpf code. 

Currently, the gadget calls `NewSocketEnricher()` and `socketEnricher.SocketsMap()` to get the ebpf map to use in ebpf program.

In the operator model, the gadget could implement an interface with a method `SetSocketEnricherSocket(m *ebpf.Map)`. The operator would call this method when the interface is implemented. The operator would also need to know when the gadget is stopped to be able to stop the socket enricher when not needed.

**Comment by alban** [comment]
I also suggest this optimization for the socket enricher:
https://github.com/inspektor-gadget/inspektor-gadget/pull/1630#issuecomment-1578102124
