### ISSUE TITLE
Error performing kubectl gadget tcptop

### ISSUE THREAD

**Issue by grichardson661** [inspektor-gadget/inspektor-gadget#170]
**Description**

When attempting to grab the TCP flows no traffic is logged in the output.

**Impact**

Unable to grab the logs and troubleshoot traffic flows in my lab environment. 

**Environment and steps to reproduce**

1. **Set-up**: 
Running a self-managed kube cluster in AWS with the Calico CNI. Versions
Kubernetes version: kubeadm - 1.20.5-00, kubectl - 1.20.5-00, kubelet - 1.20.5-00, kubernetes-cni - 0.8.7-00
Calico CNI version: Client Version:    v3.18.1, Git commit:        911f383f, Cluster Version:   v3.18.1, Cluster Type:      
typha,kdd,k8s,operator,bgp,kubeadm
Kernel version: Linux ip-172-31-39-10.eu-west-1.compute.internal 5.4.0-1045-aws #47~18.04.1-Ubuntu SMP Tue Apr 13 15:58:14 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Docker version: 
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Dec 18 12:21:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Thu Dec 10 13:23:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.4
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:  

My application is hosted in the default namespace.

I installed Krew then kubectl krew install gadget.

Note - I can reach the application outside of the cluster which is hosted on the same pod/container i was running gadget tcptop against.

2. **Task**: I was running kubectl gadget tcptop --node ip-172-31-41-66 --podname my-lab-xxxx 
3. **Action(s)**: 
  a. kubectl gadget tcptop --node ip-172-31-41-66 --podname my-lab-xxxx 
4. **Error**: See attached screen shot (empty output) and the logs from the gadget pods.
![blank_output_gadget](https://user-images.githubusercontent.com/30794830/115877565-7ce1cd80-a43f-11eb-8231-0f3ea898e4ba.PNG)
[gadget-lplm8.txt](https://github.com/kinvolk/inspektor-gadget/files/6365574/gadget-lplm8.txt)
[gadget-k2d4b.txt](https://github.com/kinvolk/inspektor-gadget/files/6365575/gadget-k2d4b.txt)

**Expected behavior**
Traffic flows to be displayed in the output.

**Additional information**
Please add any information here that does not fit the above format.

**Comment by mauriciovasquezbernal** [comment]
@grichardson661 a lot of time has opened since you opened this PR, sorry for not replying before. This issue should be fixed in the latest releases, please reopen it if you still face problems.
