### ISSUE TITLE
NetworkPolicy monitor crashing

### ISSUE THREAD

**Issue by kuznetsov420** [inspektor-gadget/inspektor-gadget#175]
## Description
I've encountered the issue when NetworkPolicy monitor tool crashes after ~1hr work.

## Impact
I want to collect network trace logs e.g. for 1 day duration.

## Environment and steps to reproduce

1. **Set-up**: Azure AKS private cluster with 5 worker-nodes
2. **Task**: 
```
kubectl gadget network-policy monitor --namespaces <my comma-separeted namespace's list here> --output networktrace.log
```
3. **Action(s)**: 
```
Node aks-node-vmss000000 ready.
Node aks-node-vmss000001 ready.
Node aks-node-vmss000002 ready.
Node aks-node-vmss000003 ready.
Node aks-node-vmss000004 ready.
```
4. **Error**: 
```
Error detected: "Error running command: %!q(<nil>)\n"
```
Sometimes `gadget` pods restarting several times with error:
```
fatal error: concurrent map iteration and map write
```
## Expected behavior
Expected to get network trace logs for 1 day duration.

**Comment by alban** [comment]
@kuznetsov420 Thanks for the report. Did the gadget pod give additional error messages after "fatal error: concurrent map iteration and map write" such as Go file names and line numbers?

**Comment by kuznetsov420** [comment]
@alban thanks for response!
In addition to previous message, i've found couple messages like this:
```
fatal error: {"containerid":"docker://28223e0ba0b44b71d892983af5b062b2de0859d35516f5cd70ef6ae2fb6e088b","level":"debug","msg":"Sync/Add/Update for container","namespace":"__EDITED__","podkey":"__EDITED__/edbf-488339940215984129-d2mn5","podname":"edbf-488339940215984129-d2mn5","time":"2021-05-31T23:29:12Z"}
```
Later I've tried to redeploy gadget with env var `INSPEKTOR_GADGET_OPTION_TRACELOOP_LOGLEVEL=debug,json`, and restarted `kubectl gadget network-policy monitor` task, but didn't notice any other type of log messages.

**Comment by mauriciovasquezbernal** [comment]
A lot of things have changed in the project since this issue was opened. @kuznetsov420 any chance you can test this with the latest Inspektor Gadget version?

**Comment by mauriciovasquezbernal** [comment]
Closing this. Please feel free to reopen if you have more information to share.
