### ISSUE TITLE
gadgettracermanager: Consider removing cgroup support

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#178]
The gadget tracer manager supports two ways to keep track of tracers: cgroups and mount namespace. 

Currently we're mostly relying on the mount namespace as it works fine on almost all distributions. On the other hand, cgroups needs to be cgroups-v2 that is not available everywhere. 

@alban [mentioned](https://github.com/kinvolk/inspektor-gadget/pull/163#discussion_r646568553) the possibility of removing support for cgroups-v2 and relying only on mount namespace. 

The goal of this issue is to discover the implications of such change and make a decision on it.

**Comment by alban** [comment]
On a node with hybrid cgroup support, I got a nginx pod with those cgroups:
```
$ cat /proc/3985033/cgroup
11:perf_event:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
10:pids:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
9:blkio:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
8:memory:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
7:net_cls,net_prio:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
6:cpu,cpuacct:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
5:cpuset:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
4:hugetlb:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
3:freezer:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
2:devices:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
1:name=systemd:/kubepods/besteffort/podf85483ff-538f-49e8-961a-913fd85b8d7e/5327ff2973fe4c0b9b1508fbb4a63e7bec23a1ad9e5cd31bb9a6577e32b364b4
0::/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-3ce024e0-dd6f-40bc-80f6-723f37011102.scope
```

The v1 cgroups are in /kubepods but the v2 cgroup is still mixed in the containerd cgroup along with all other pods.

When cgroup v2 is enabled, it is still not easy to detect if it is actually used to separate different containers. So I think we should use the mnt namespace.

**Comment by marga-kinvolk** [comment]
Is this issue still relevant? If yes, what do we need to do to get rid of cgroups and just use the mnt namespace?

**Comment by mauriciovasquezbernal** [comment]
We're moved to use mount namespace everywhere. I think we're not relying on cgroups on any of our gadgets. However, I don't know if cgroup support in the gadget tracer manager should be removed, local-gadget (or systemd-gadget in the future) could make use of it.

**Comment by alban** [comment]
I removed cgroup support in https://github.com/kinvolk/inspektor-gadget/pull/581/files#diff-b244a5eb6305aed42a0fa72e3f8b34906f4df04d652cb7772a4dac2ed5e90eb5L68-L69

So the ebpf map with the cgroup info per tracer is not there anymore. But the ContainerDefinition struct still has the same info about cgroups as before.
