### ISSUE TITLE
Version skew warning message is not printed

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1795]
We printed a warning in case the kubectl-gadget and the gadget pod were not the same version when we're using custom resources to run gadgets:

https://github.com/inspektor-gadget/inspektor-gadget/blob/83dde7d1ea4e16c14118531a1acdaf92123ff723/cmd/kubectl-gadget/utils/trace.go#L185

However, this code path is not used anymore after https://github.com/inspektor-gadget/inspektor-gadget/pull/1396. We should implement that again to be sure we inform users.

## Implementation options

We already have a mechanism to send the deploy info from the gadget pods to kubectl-gadget

https://github.com/inspektor-gadget/inspektor-gadget/blob/83dde7d1ea4e16c14118531a1acdaf92123ff723/pkg/runtime/grpc/grpc-runtime.go#L80

We could include the gadget pod version there and print the warning around these lines 

https://github.com/inspektor-gadget/inspektor-gadget/blob/83dde7d1ea4e16c14118531a1acdaf92123ff723/pkg/runtime/grpc/grpc-runtime.go#L73-L84

There's an Version field in the proto definition

https://github.com/inspektor-gadget/inspektor-gadget/blob/83dde7d1ea4e16c14118531a1acdaf92123ff723/pkg/gadgettracermanager/api/gadgettracermanager.proto#L133

We can use that field for this purpose. However, in the server side it's not filled yet 

https://github.com/inspektor-gadget/inspektor-gadget/blob/83dde7d1ea4e16c14118531a1acdaf92123ff723/pkg/gadget-service/service.go#L76

~We can use the [`INSPEKTOR_GADGET_VERSION`](https://github.com/inspektor-gadget/inspektor-gadget/blob/83dde7d1ea4e16c14118531a1acdaf92123ff723/pkg/resources/manifests/deploy.yaml#L163) env variable to get it.~

Edit: Using `INSPEKTOR_GADGET_VERSION` doesn't work as it's actually set to the kubectl-gadget version. New options are:
- Introduce a [version variable](https://github.com/inspektor-gadget/inspektor-gadget/blob/20206557754ac01e1eecf5d0770e4e972afa0c3e/cmd/common/version.go#L24) in the [gadgetracermanager](https://github.com/inspektor-gadget/inspektor-gadget/blob/bf0836272a615a373f81934796dc24207ff92419/gadget-container/gadgettracermanager/main.go) as done in ig and kubectl-gadget
- Use the image tag as in the previous approach.

**Comment by moki1202** [comment]
@mauriciovasquezbernal @mqasimsarfraz  can we simply check whether the gadget version that we get from the env var equals `KubectlGadgetVersion` and log warning accordingly?

**Comment by mauriciovasquezbernal** [comment]
It turns out the [INSPEKTOR_GADGET_VERSION](https://github.com/inspektor-gadget/inspektor-gadget/blob/83dde7d1ea4e16c14118531a1acdaf92123ff723/pkg/resources/manifests/deploy.yaml#L163) env variable is totally wrong as it's calculated from kubectl-gadget, so it doesn't provide the real running version. 

I think the easiest way is to look at the image tag as it is done in the existing printVersionSkewWarning().

**Comment by moki1202** [comment]
@mauriciovasquezbernal Apologies. I didn't look into printVersionSkewWarning function completely. Now I see that it already checks the version from image and prints warning accordingly. Maybe I understood the issue wrong.

**Comment by mauriciovasquezbernal** [comment]
Nothing wrong on your side, it was my fault. I updated the PR's description to make it more clear.

**Comment by moki1202** [comment]
@mauriciovasquezbernal just a few more questions/doubt. As far as I understood, we need to log warning in the `InitDeployInfo` function and we could do that by adding a version field in the `DeployInfo` struct and populating it using the image tag just like in `kubectl-gadget`. I don't understand why we need to introduce version in `gadgetracermanager`.

**Comment by mauriciovasquezbernal** [comment]
Those are different ways of reaching the same goal. Ideally, there should be a version in `gadgetracermanager` as it could be potentially different than the version of the image. But in practice it doesn't happen, so we can base all this "version skew warning" logic on the image tag.

I suggest to use the "deploy info" structure as it already contains information about the deployment. We can have a "gadgetTag" or similar field there, and then we can compare it against the kubectl-gadget version and print a warning.

**Comment by moki1202** [comment]
understood! I'll open a PR soon.

**Comment by mauriciovasquezbernal** [comment]
Now that I think better, we need to have a version defined in the server side (gadgettracermanager) and (ig). Otherwise, this same logic based on the image tag doesn't work when ig is used in daemon mode with gadgetctl (see https://www.inspektor-gadget.io/docs/v0.24.0/ig/#using-ig-as-a-daemon). 

I think the easiest way is to define a new internal `version` package that has this, then it can be imported by the different components that need a version, like ig, kubectl-gadget and gadgettracer manager. Then the grpc runtime could use this to send the binary version on the GetInfo() method. 

https://github.com/inspektor-gadget/inspektor-gadget/blob/7780c497030609f48ebb62b3b910eae841b9985e/pkg/gadget-service/service.go#L84-L88

Be aware that there is a Version field on that structure, but that's designed to be the API version, so I think we need to add a new ServerVersion or similar field there. 

I hope this solution works, sorry for the back and forth.

**Comment by mauriciovasquezbernal** [comment]
I hacked something in https://github.com/inspektor-gadget/inspektor-gadget/commit/fe3ce186dcd6034045fad10e4cec9711ef9e1c2e. Feel free to use this as base for this your PR.
