### ISSUE TITLE
Deprecate and delete runc-fanotify in favour of container-hook

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1831]
runc-fanotify and container-hook are similar and share some code but have subtle differences. When making a change in one, we often need to update the other one and we risk forgetting.

I suggest to wait until September and then delete runc-fanotify if we have not found any issue with container-hook in various environments.

**Comment by alban** [comment]
Thanks @flyth for testing the ig container image (from this branch https://github.com/inspektor-gadget/inspektor-gadget/pull/1809#issuecomment-1633005357) on mac.

The container-hook package does not work on mac because of the lack of BTF: https://github.com/docker/for-mac/issues/6800.

The error message is as follow:

> Error: initializing manager: starting container fanotify: readPrivateDataFromFd: loading maps and programs: field IgFgetX: program ig_fget_x: apply CO-RE relocations: load kernel spec: no BTF found for kernel version 5.15.49-linuxkit: not supported

But runc-fanotify does not work either on mac, for different reasons (fanotify support in the kernel?), so that's not a regression.

**Comment by alban** [comment]
`container-hook` requires either a kernel with `CONFIG_DEBUG_INFO_BTF`, or a kernel supported by btfhub. `runc-fanotify` does not use BTF. So it depends if we want IG to keep compatibility with kernels without BTF nor btfhub support. Since current gadgets require either BTF or btfhub support, I think it does not make sense to keep `runc-fanotify` for the sake of old kernels that can't run our current gadgets anyway.

**Comment by blanquicet** [comment]
> Since current gadgets require either BTF or btfhub support, I think it does not make sense to keep runc-fanotify for the sake of old kernels that can't run our current gadgets anyway.
>
I agree.

**Comment by blanquicet** [comment]
@alban, this still need to be done. I think the time we define to remove it has passed. Is there any blocker that prevents us from removing it?

**Comment by alban** [comment]
No blockers from me :)

**Comment by blanquicet** [comment]
Ok, so I change the name of this issue and reopened it.
