### ISSUE TITLE
TestClose fails when other Docker containers run on the machine

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1832]
## Description

The unit test `TestClose` fails when other Docker containers run on the machine

## Impact

File descriptor leak: `ig` and `gadgettracermanager` have two file descriptors never closed for each initial container.

## Environment and steps to reproduce

Start a docker container in the background:
```
docker run -d -p 5000:5000 --restart=always --name registry registry:2
```
Run the TestClose test:
```
go test -test.v -exec sudo -run TestClose ./pkg/ig-manager/...
```
See the error:
```
=== RUN   TestClose
    ig-manager_test.go:119: After 20 attempts, fd leaked:
        0: /dev/null
        1: pipe:[2658229]
        2: pipe:[2658229]
        4: anon_inode:[eventpoll]
        5: pipe:[2665117]
        6: pipe:[2665117]
        
        0: /dev/null
        1: pipe:[2658229]
        2: pipe:[2658229]
        24: mnt:[4026535441]
        25: net:[4026535445]
        26: mnt:[4026535441]
        27: net:[4026535445]
        28: mnt:[4026533836]
        29: net:[4026534233]
        30: mnt:[4026535441]
        31: net:[4026535445]
        32: mnt:[4026534944]
        33: net:[4026534948]
        34: mnt:[4026533836]
        35: net:[4026534233]
        36: mnt:[4026533274]
        37: net:[4026533278]
        38: mnt:[4026535441]
        39: net:[4026535445]
        4: anon_inode:[eventpoll]
        40: mnt:[4026534944]
        41: net:[4026534948]
        42: mnt:[4026533836]
        43: net:[4026534233]
        44: mnt:[4026533274]
        45: net:[4026533278]
        48: mnt:[4026534944]
        49: net:[4026534948]
        5: pipe:[2665117]
        50: mnt:[4026533836]
        51: net:[4026534233]
        52: mnt:[4026533274]
        53: net:[4026533278]
        56: mnt:[4026534944]
        57: net:[4026534948]
        6: pipe:[2665117]
        60: mnt:[4026533274]
        61: net:[4026533278]
--- FAIL: TestClose (6.30s)
FAIL
FAIL	github.com/inspektor-gadget/inspektor-gadget/pkg/ig-manager	6.327s
FAIL
```

## Expected behavior

The test should not fail even if the machine has some containers running unrelated to the tests.

## Additional information

The enricher from WithTracerCollection() is called twice for all initial containers from docker.

https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/container-collection/container-collection.go#L123

Just before calling cc.AddContainer(), we call the enricher callbacks. And inside the AddContainer() function, we also call the enricher callbacks

See discussion https://kubernetes.slack.com/archives/CSYL75LF6/p1688582111577469

TODO:
- [ ] Don't call the enricher twice
- [ ] Add a test like TestClose but with one docker container running in the background
- [ ] WithTracerCollection, test if the mntNsFd is already initialize and overwritten. In that case, panic.

**Comment by mqasimsarfraz** [comment]
I don't know if the failure I saw [here](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5687846974/job/15416833784#step:6:2763) is related but happened only once and doesn't occur on re-trigger. Just wanted to document it.
