### ISSUE TITLE
Inspektor Gadget is not able to determine container runtime socket path 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#184]
Inspektor Gadget needs to know containers'  PID to get their cgroup or mount namespace to configure the filtering rules in the eBPF tools. Inspektor Gadget retrieves the PID of the containers directly from the container runtimes as it's not exposed in the kubernetes API. The implementation is different for each runtime (as shown [here](https://github.com/kinvolk/inspektor-gadget/tree/master/pkg/gadgettracermanager/containerutils)). 

Currently all the implementations use a default (`DEFAULT_SOCKET_PATH`) value for the socket path of the container runtime . If the runtime runs with a different socket path it'll fail to connect as Inspektor Gadget is not able to determine what is the current socket path that is being used. We haven't found and easy and reliable way to determine the socket path programmatically. 

The purpose of this issue is to explore different possibilities to solve it. Some ideas we have thought about:
- Expose the PID directly in Kubernetes to avoid talking to the runtime
- Expose the container runtime socket path in Kubernetes 
- Look for the container runtime process running in the host and deduct it from its command line 
- `sudo ss -l | grep containerd` and parse its output 

This limitation is only present when using `--hooks-mode=podinformer`, other hooks are able to get the container's PID  without having to talk to the runtime. 
 /cc @alban

**Comment by invidian** [comment]
How about just having some default list of socket paths to probe and connect to first available (e.g. `/var/run/docker.sock` and `/run/docker.sock`) + being able to configure custom socket path for custom scenarios?

**Comment by mauriciovasquezbernal** [comment]
Yes, that would make sense and would solve this issue in most of the cases.

**Comment by mauriciovasquezbernal** [comment]
This is (mostly) fixed by https://github.com/inspektor-gadget/inspektor-gadget/issues/451.
