### ISSUE TITLE
trace/tcpdrop on kernel version < 5.17 doesn't show dropped packages / shows wrong reason

### ISSUE THREAD

**Issue by burak-ok** [inspektor-gadget/inspektor-gadget#1847]
### Problem

The tracepoint with additional drop information (`skb_drop_reason`) we use was introduced in [kernel version 5.17](https://github.com/torvalds/linux/commit/c504e5c2f9648a1e5c2be01e8c3f59d394192bd3)

So for kernels without that our gadget correctly returns an error and refuses to run. But some kernel version < 5.17 has that feature backported, for example the one used in AKS which is running `5.15`

The problem with the kernel in AKS is that the enum has different values assigned. So we show wrong reasons for dropped packets. Or even not showing if a package was dropped.

```c
// $ sudo bpftool btf dump file ./vmlinux format c|grep -A4 'enum.*drop_reason {'
enum skb_drop_reason {
    SKB_DROP_REASON_NOT_SPECIFIED = 0,
    SKB_DROP_REASON_NO_SOCKET = 1,
    SKB_DROP_REASON_PKT_TOO_SMALL = 2,
    SKB_DROP_REASON_TCP_CSUM = 3,
```

We also can't just change the comparision in [`tcpdrop.bpf.c`](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/gadgets/trace/tcpdrop/tracer/bpf/tcpdrop.bpf.c#L133) because of the enum issue described above. Just reporting every reason is also not feasible since the tracepoint used is `SEC("tracepoint/skb/kfree_skb")`.
This gets called for every skb deallocation, be it from a successful connection or dropped one.

### Potential solution
1. Just forbid the gadget to run on lower kernel versions?
2. @alban mentioned in https://github.com/inspektor-gadget/inspektor-gadget/issues/1199#issuecomment-1419079293 that prior kernel versions had a `tcp_drop` function where a kprobe could be attached. -> Have 2 eBPF programs and use the right one?
3. ...?

**Comment by alban** [comment]
For reference, newer kernels has the enum that looks this way (Linux 6.2):
```
$ sudo bpftool btf dump file /sys/kernel/btf/vmlinux format c|grep -A4 'enum.*drop_reason {'
enum skb_drop_reason {
	SKB_NOT_DROPPED_YET = 0,
	SKB_CONSUMED = 1,
	SKB_DROP_REASON_NOT_SPECIFIED = 2,
	SKB_DROP_REASON_NO_SOCKET = 3,
```

Currently, we already use BTF to get an enum's value at run-time, so it is not hardcoded: [bpf/tcpdrop.bpf.c#L131](https://github.com/inspektor-gadget/inspektor-gadget/blob/c9dfa84b081c76ab583f653daa0d3b146bb6fbcd/pkg/gadgets/trace/tcpdrop/tracer/bpf/tcpdrop.bpf.c#L131):
```
int reason_not_specified = bpf_core_enum_value(enum skb_drop_reason, SKB_DROP_REASON_NOT_SPECIFIED);
```

What about using `bpf_core_enum_value()` to detect if `SKB_NOT_DROPPED_YET` and `SKB_CONSUMED` exist at all? As far as I understand, they don't exist on your AKS kernel 5.15, so using `bpf_core_enum_value()` on them would trigger an error in the verifier.
