### ISSUE TITLE
ig top ebpf shows empty container columns

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1859]
## Description

The following columns are shown with the `ig top ebpf` command:
* RUNTIME.CONTAINERNAME
* RUNTIME.CONTAINERIMAGENAME

But they are always empty.

## Impact

Using too much space on the screen for nothing.

## Environment and steps to reproduce

```
$ sudo ig top ebpf
```

## Expected behavior

Either the columns contains useful information or they should be hidden.

## Additional information

The top ebpf gadget currently does not enrich the events with any container metadata.

cc @blanquicet @flyth

**Comment by claudiamarcubina** [comment]
I see that RUNTIME.CONTAINERIMAGENAME and RUNTIME.CONTAINERNAME are shown with most of the gadgets with `ig`. E.g.
- ` ig snapshot *`
- `ig top *`
- `ig trace *`
- a.s.o.

While RUNTIME.CONTAINERNAME is populated, RUNTIME.CONTAINERIMAGENAME is always empty for now (work in progress). I am thinking to hide both fields for every gadget for `ig`. Is there currently a general way to do this, without modifying each of the gadgets?
