### ISSUE TITLE
run: Handling OCI images

### ISSUE THREAD

**Issue by burak-ok** [inspektor-gadget/inspektor-gadget#1875]
# Discussion about `ig run ghcr.io/foo/bar` and `kubectl-gadget run ghcr.io/foo/bar`

Should the client or the server pull the multi-arch image. Initial discussion with @alban 

## `ig`

Doesn't matter that much/Not that interesting. client == server

### Pulling is done client side (`kubectl-gadget`)

The multi-arch image is pulled by the client. It can read the config and the BTF if needed.
It then sends both/specific ELF binaries to every gadget pod.
They execute it and everything works.

For air-gapped servers the user has to push the needed images to a local registry first. Only the client needs access to the registry.
Alternativly we can ship a file based oci store. We then try to read from that first in `kubectl-gadget`

### Pulling is done server side (gadget pods)

Only the needed architecture of the image is pulled by the pods.
No large network transfers are needed between the client and all nodes (The more nodes - the larger the initial performance hit and network congestions)

However the client (`kubectl-gadget`) needs to know the config.
This means at least one gadget pod has to send this information back to the client.
If there is no config (which we want to support in the future) we need to make sure that all pods (multi-arch) would send the same information.

We additionally need the BTF at the client side (currently) aswell.
Gadget pods are sending `event struct`s back to the client. The struct has a `RawData []byte` buffer.
We need access to the BTF to decode the starting addresses and lengths of the kernel struct members. 

For air-gapped servers the user has to push the needed images to a local registry first. (Only) the pods needs access to the registry.
If we wanted to ship a file based oci store we would need to deploy alongside every gadget pod

## Multi-Arch problems

Since we would deploy the same ELF file on a cluster with varying kernel versions and architectures it could happen that the kernel member struct offsets and lengths are different.
So the decoding of the BTF and the `RawData []byte` buffer should happen at the pod?

**Comment by mauriciovasquezbernal** [comment]
> Doesn't matter that much/Not that interesting. client == server

It's almost true except for https://github.com/inspektor-gadget/inspektor-gadget/issues/1681. Anyway, in this case multiarch support is not a challenge, so I agree there's not too much to discuss here.

> ### Pulling is done client side (`kubectl-gadget`)
> 
> The multi-arch image is pulled by the client. It can read the config and the BTF if needed. It then sends both/specific ELF binaries to every gadget pod. They execute it and everything works.
 
I think sending images to all nodes puts a lot of stress to the client. In many cases the client can be running in a machine with a slow connection. 

> ### Pulling is done server side (gadget pods)
> 
> Only the needed architecture of the image is pulled by the pods. No large network transfers are needed between the client and all nodes (The more nodes - the larger the initial performance hit and network congestions)

It's the same when a daemonset is deployed. I don't think it's a big deal 

> Since we would deploy the same ELF file on a cluster with varying kernel versions and architectures it could happen that the kernel member struct offsets and lengths are different. 

Also the endianess... 

> So the decoding of the BTF and the `RawData []byte` buffer should happen at the pod?

I'm wondering the same. Theoretically it could be possible for the client to parse data in different ways according to the server's architecture, but that's a big mess. I think for now each pod should perform the binary to json conversion, and then the client should convert this to columns. (Probably we need to touch a bit the columns library to support this generic json to columns thing).

Later on, we can consider using binary encoding instead of json to save some bandwidth.

**Comment by burak-ok** [comment]
Another thought: When we are pulling from private repositories we need to authenticate.
So we need a configuration for the authentication somewhere and since every gadget pod pulls the image they would need it too. 

How do they get it?
- Our GRPC connect? We would then need to have it fully secured against Man in the Middle attacks
- In a K8s CR? Can they be locked down so not everyone can access it?
- Copy an auth file to every gadget pod?

**Comment by mauriciovasquezbernal** [comment]
> Our GRPC connect? We would then need to have it fully secured against Man in the Middle attacks

Our gRPC will run over a secure protocol, so it should be fine sending secrets over it.
