### ISSUE TITLE
Using kwasm breaks IG event enrichment for host events

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1899]
## Description

When using a wasm runtime (https://kwasm.sh/) on Kubernetes and deploying a wasm workload, events from the host are reported as belonging to the wasm pod.

## Impact

- IG reports wrong container metadata in all gadgets.
- Wasm pods termination is not detected by container-hook

## Environment and steps to reproduce

- Use Minikube with the containerd runtime.
- Install Spin following the kwasm documentation: https://kwasm.sh/quickstart/
- Start IG:

```
$ kubectl debug node/minikube-containerd -ti --image=ghcr.io/inspektor-gadget/ig -- ig --auto-sd-unit-restart trace tcp
RUNTIME.CONTAINERNAME   RUNTIME.CONTAINERIM… T PID      COMM     IP SRC                  DST
spin-hello              ghcr.io/deislabs/co… C 3024289  kubelet  4  192.168.58.2:42960   192.168.58.2:8443
```

Notice that the event from the kubelet is reported as belonging to the `spin-hello` container, which is incorrect.

## Expected behavior

* Minimum:
  * If a container runtime says that a container has pid 1 or that its mntns is the same as the host, don't accept it
* Long term:
  * Add a way to filter by wasm runtimes. Since wasm runtimes don't use cgroups or namespaces to isolate the "container", Gadgets would need to filter by pid of the containerd shims instead.

## Additional information

The container runtime `containerd-shim-spin-v1` always reports the pid of the container to be 1:
https://github.com/deislabs/containerd-wasm-shims/blob/1cb6aaa22daf7eb33bbefe1dd758bb65d67d9425/containerd-shim-spin-v1/src/main.rs#L268

This causes Inspektor Gadget to believe the wasm pod has pid 1:
```
$ kubectl debug node/minikube-containerd -ti --image=ghcr.io/inspektor-gadget/ig -- ig --auto-sd-unit-restart list-containers -o json -c spin-hello | grep -A 2 pid
If you don't see a command prompt, try pressing enter.
    "pid": 1,
    "mntns": 4026533174,
    "netns": 4026533178,
$ minikube ssh 'sudo ls -l /proc/1/ns/{mnt,net}'
lrwxrwxrwx 1 root root 0 Jul 26 21:05 /proc/1/ns/mnt -> 'mnt:[4026533174]'
lrwxrwxrwx 1 root root 0 Jul 26 21:08 /proc/1/ns/net -> 'net:[4026533178]'
```

Notice that IG wrongly believes that the mount namespace `4026533174` belongs to the pod.

Useful documentation:
- https://kwasm.sh/quickstart/
- https://github.com/deislabs/containerd-wasm-shims
- https://github.com/fermyon/spin
- https://developer.fermyon.com/spin/kubernetes#run-a-spin-workload-on-kubernetes
- https://learn.microsoft.com/en-us/azure/aks/use-wasi-node-pools

**Comment by alban** [comment]
For the record, kata containers use a containerd shim that returns the vmm process pid:

https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L487-L489
https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/create.go#L184-L188

This will also cause problems in the current implementation of Inspektor Gadget since those pids are not in separate mount namespaces.

**Comment by alban** [comment]
It seems that containers using wasmtime-spin no longer reports `pid=1` but the pid of `containerd-shim-spin-v2` and it has its own mnt namespace:
```
# gadgettracermanager -dump containers
&{Runtime:{BasicRuntimeMetadata:{RuntimeName:containerd ContainerID:33f48b4831e665f3e59e0de36dad90dd3a1419fbd15a67cc7a1799d386247b77 ContainerName:spin-hello ContainerImageName:ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:latest ContainerImageDigest:sha256:da2c07d3bf122b485a13518783cacd95104a9dab0a0f08c102a8089c56cdf40c}} K8s:{BasicK8sMetadata:{Namespace:default PodName:wasm-spin-9f65849d-7gnn7 PodLabels:map[app:wasm-spin pod-template-hash:9f65849d] ContainerName:spin-hello} PodUID: ownerReference:<nil>} Pid:2148833 OciConfig:<nil> Bundle: SandboxId: Mntns:4026532997 Netns:4026532924 HostNetwork:false CgroupPath:/sys/fs/cgroup/kubepods-besteffort-podd176a934_caca_4c16_bd09_e321282bc9dc.slice:cri-containerd:33f48b4831e665f3e59e0de36dad90dd3a1419fbd15a67cc7a1799d386247b77 CgroupID:57153 CgroupV1: CgroupV2:/kubepods-besteffort-podd176a934_caca_4c16_bd09_e321282bc9dc.slice:cri-containerd:33f48b4831e665f3e59e0de36dad90dd3a1419fbd15a67cc7a1799d386247b77 mntNsFd:73 netNsFd:75 deletionTimestamp:{wall:0 ext:0 loc:<nil>}}
```
```
# ps aux|grep 2148833
root     2148833  0.2  0.1 6296204288 31648 ?    Ssl  10:32   0:03 /opt/kwasm/bin/containerd-shim-spin-v2 -namespace k8s.io -id 32ced0a52e0ff932fbb66927a81b18a2564bb9e066d39a299005ea540df4b3cf -address /run/containerd/containerd.sock
# ls -l /proc/2148833/ns/mnt
lrwxrwxrwx 1 root root 0 Jun 27 10:32 /proc/2148833/ns/mnt -> 'mnt:[4026532997]'
# ls -l /proc/2148833/root/
total 1712
drwxr-xr-x   5 root root     360 Jun 27 10:32 dev
drwxr-xr-x   2 root root    4096 Jun 27 10:32 etc
dr-xr-xr-x 291 root root       0 Jun 27 10:32 proc
-rw-r--r--   1 root root     996 Jun 27 10:32 spin.lock
-rw-r--r--   1 root root     380 Feb 15 18:39 spin.toml
-rwxr-xr-x   1 root root 1520415 Feb 15 18:40 spin_go_hello.wasm
-rwxr-xr-x   1 root root  210859 Feb 15 18:40 spin_rust_hello.wasm
dr-xr-xr-x  12 root root       0 Jun 27 10:32 sys
drwxr-xr-x   3 root root    4096 Jun 27 10:32 var
```

So it no longer causes a bug in IG.

**Comment by mayasingh17** [comment]
@alban I wasn't quite following the technical aspects but do we need to update the chart here that specifies which container runtimes we support: https://inspektor-gadget.io/docs/latest/reference/requirements ?
