### ISSUE TITLE
[RFE] Update controller-runtime to 0.14.x

### ISSUE THREAD

**Issue by anubhabMajumdar** [inspektor-gadget/inspektor-gadget#1907]
## Current situation

Package `controller-runtime` is currently at `v0.13.1-0.20230315234915-a26de2d610c3`. Update to latest `v0.14.x`.

## Impact

Importing IG to latest go project requires using older version of `controller-runtime`.

## Ideal future situation

IG uses `0.14.x` version of `controller-runtime`.

**Comment by mauriciovasquezbernal** [comment]
I think it was fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/1348, please reopen this issue if that's not the case.
