### ISSUE TITLE
[RFE] Adding support for uprobes in gadgets

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1912]
## Current situation

We have gadgets using different kinds of ebpf programs (kprobe, tracepoint, socket filter, etc.) but no gadgets using uprobes so far.

## Impact

Many use cases needs uprobe programs and they are not implemented:
- [ ] See encrypted network traffic by attaching to functions such as openssl's SSL_read() and SSL_write() (see [bcc's sslsnif](https://github.com/iovisor/bcc/blob/master/tools/sslsniff.py))
- [ ] memleak (see [bcc's memleak](https://github.com/iovisor/bcc/blob/41f8010e2e85616ad37303af20f77c1c717b9b11/libbpf-tools/memleak.bpf.c#L164))
- [ ] deadlock (see [bcc's deadlock](https://github.com/iovisor/bcc/blob/master/tools/deadlock.py#L501))

## Ideal future situation

Full support would include:

- [ ] Inspektor Gadget should support uprobes so that the aforementioned gadgets can be implemented as image-based gadgets.
- [ ] ~`ig script` support uprobe scripts~ (not the priority at the moment)
  - [ ] ~Support for dynamic container creation/termination~
- [ ] IG has the following gadgets, either built-in or containerized gadgets:
  - [ ] sslsniff
  - [ ] memleak
  - [ ] deadlock
- [ ] Support for user stacks
  - [ ] in uprobe gadgets
  - [ ] `ig profile cpu` (this is not using uprobes but the code for printing user stack should be similar)

Since it is quite complex, I suggest to start with [bcc's bashreadline](https://github.com/iovisor/bcc/blob/master/tools/bashreadline_example.txt) because it does not require support for user stack.

### Multiple attachment

Similarly to networking gadgets, uprobes ebpf programs need to be attached multiple times (one time for each container) because they are attached to the inode of interest in the rootfs of the container. So we will probably need something similar to pkg/gadgets/internal/networktracer to attach/detach containers but for uprobes instead of socket filters.

Since containers can be created and terminated at any time, the attach/detach should be done dynamically like it was done in pkg/gadgets/internal/networktracer. For bpftrace running as an external process, that will be very difficult since that would require dynamic communication between IG and bpftrace processes.

### Proper filtering

Note that the uprobe program can be executed outside of the selected container, so the uprobe program should check if it is called in a container of interest:
- if 2 containers share files via a common host volume and the uprobe was attached to a file on that volume via one container.
- if 2 containers use the same container image and the snapshotter in containerd uses the same underlying inode in both rootfs.

### User stacks

A common pattern in uprobe programs is to send the stack id so it can be printed. This is done in bcc's memleak and deadlock. This is more difficult than kernel stack since it can't be done with /proc/kallsyms and the addresses functions are dynamic with dynamic libraries. For example, bcc's sslsniff attaches a uprobe to the function `SSL_write` which is defined in the openssl dynamic library and the address of the function will vary depending on the process.

Other implementation options for user stacks:
- https://github.com/inspektor-gadget/inspektor-gadget/issues/1132
- https://www.polarsignals.com/blog/posts/2022/11/23/profiling-without-frame-pointers/
- https://www.polarsignals.com/blog/posts/2022/11/29/dwarf-based-stack-walking-using-ebpf/

## Additional information

🌌

[LFX](https://mentorship.lfx.linuxfoundation.org/project/f016029e-f15f-4ee9-aaf5-5719bee72b59)

**Comment by i-Pear** [comment]
I am quite interested in this project, will try to apply on LFX later.

From my understanding, obtaining symbols for the user stack is generally done by reading `/proc/$pid/maps` to get the offset of shared libraries, which is also the approach taken by `perf`.

Does this project require support for both `frame_pointer` and `dwarf` methods? The former is relatively easier to implement, while the latter may require the introduction of external libraries such as `libunwind` due to the complexity of the unwind algorithm.

**Comment by alban** [comment]
@i-Pear Thanks!
There are two possibilities to unwind the stacks:
1. Unwind in userspace like perf is doing
2. Unwind in ebpf like Polar Signals is doing (see last link in the description).

The problem with the userspace approach is that by the time Inspektor Gadget receives the notification from eBPF that it must unwind the stack, the target process might have terminated already (or it might have munmap()ed the relevant parts). Maybe that's not a big issue in practice.

At this stage, I don't know the complexity of either possibilities and I don't know about whether to use libunwind or other methods. I suggest an iterative approach: even without unwinding the stack, uprobes support would be useful. 

For the [LFX project](https://mentorship.lfx.linuxfoundation.org/project/f016029e-f15f-4ee9-aaf5-5719bee72b59), I think it might be unrealistic to have complete unwinding support (thinking about programs in Go, Python, Node.JS or other interpreted languages). If we get some support for some limited use cases, that's already good.

**Comment by i-Pear** [comment]
> There are two possibilities to unwind the stacks:
> 
> 1. Unwind in userspace like perf is doing
> 2. Unwind in ebpf like Polar Signals is doing (see last link in the description).
> 
> The problem with the userspace approach is that by the time Inspektor Gadget receives the notification from eBPF that it must unwind the stack, the target process might have terminated already (or it might have munmap()ed the relevant parts). Maybe that's not a big issue in practice.

Yes, this problem can arise. The approach taken by `perf` is to retrieve symbols from `/proc/self/maps` at the beginning of tracing. Alternatively, we can obtain notifications when loading a new library by monitoring the `mmap` syscall or using uprobe to monitor certain functions in the loader (this may not be an ideal solution as it requires loader support and may introduce additional overhead).

Unwinding in eBPF looks interesting, but the article mentions that it requires preprocessing DWARF information. If the program dynamically loads libraries, we also need to preprocess the DWARF info in real-time.

> At this stage, I don't know the complexity of either possibilities and I don't know about whether to use libunwind or other methods. I suggest an iterative approach: even without unwinding the stack, uprobes support would be useful.

> For the [LFX project](https://mentorship.lfx.linuxfoundation.org/project/f016029e-f15f-4ee9-aaf5-5719bee72b59), I think it might be unrealistic to have complete unwinding support (thinking about programs in Go, Python, Node.JS or other interpreted languages). If we get some support for some limited use cases, that's already good.

There seems to be little difference between `uprobe` and `kprobe` in the working principles and interfaces; the kernel has largely abstracted away most of the distinctions. I guess, from an implementation standpoint, the primary task is to identify the correct process and attach/unattach automatically, as mentioned in this issue.

For interpreted languages, yes, unwinding requires enabling the `frame_pointer` feature in the interpreter or obtaining information from the interpreter using an agent. This is beyond the scope of eBPF.

**Comment by beaubelgrave** [comment]
The SFRAME work going on in the Linux kernel plans to help solve this problem as well:
https://lwn.net/Articles/932209/

**Comment by kanha-gupta** [comment]
Hi @alban This work is very interesting and a great learning opportunity. will apply :)

**Comment by alban** [comment]
This task has been completed.
See also:
* [Blog post](https://inspektor-gadget.io/blog/2024/06/supporting-uprobe-based-gadgets-lfx-mentorship-report/)
* [Meeting 14 - June 13, 2024](https://docs.google.com/document/d/1cbPYvYTsdRXd41PEDcwC89IZbcA8WneNt34oiu5s9VA/edit#heading=h.n5nj4j6gdxl4)
