### ISSUE TITLE
[RFE] trace exec: add new fields for: from memfd, upper layer, writable, unlinked

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1913]
## Current situation

The events from the trace exec gadget have the following columns:
```
$ ig trace exec -h
...
Available columns:
  args
  comm
  gid
  loginuid
  mntns
  pid
  ppid
  ret
  runtime.containerId
  runtime.containerImageName
  runtime.containerName
  runtime.runtimeName
  sessionid
  timestamp
  uid
Default columns: runtime.containerName,runtime.containerImageName,pid,ppid,comm,ret,args
...
```

It does not have the following details about the program being executed:
- [ ] from memfd: whether the program file is not on the filesystem but on a memfd (see `man 2 memfd_create`), aka "fileless execution"
  - [ ] #2346
- [x] upper layer: whether the program file is on the upper layer of overlayfs, i.e. it was modified in the container
  - [x] #2345
- [ ] writable: whether the caller has write permission on the program file.
- [ ] unlinked: whether the program file has been deleted.

## Impact

The missing details are useful to understand security attacks.

## Ideal future situation

The trace exec gadget has an 'inode info' field with the 4 aforementioned booleans.

## Implementation options

This list comes from Falco libraries and Tetragon:
- [extract__exe_from_memfd](https://github.com/falcosecurity/libs/blob/59fb313475b82f842e9e9bbc1e0e629428c0a4cf/driver/modern_bpf/helpers/extract/extract_from_kernel.h#L736C29-L736C52)
- [extract__exe_upper_layer](https://github.com/falcosecurity/libs/blob/59fb313475b82f842e9e9bbc1e0e629428c0a4cf/driver/modern_bpf/helpers/extract/extract_from_kernel.h#L704)
- [extract__exe_writable](https://github.com/falcosecurity/libs/blob/59fb313475b82f842e9e9bbc1e0e629428c0a4cf/driver/modern_bpf/helpers/extract/extract_from_kernel.h#L869C29-L869C50)
- [file->f_inode->__i_nlink](https://github.com/cilium/tetragon/pull/499/files#diff-7daffaf82e5277f6ec2a32f8a4209bb155bc6c6aa402f47bbb2e61d1a34483d7R36)

We don't have direct access to the `struct file` from `tracepoint/syscalls/sys_exit_execve`. Options:
- kprobe/security_bprm_check (https://github.com/cilium/tetragon/pull/499)
- ([Falco's extract__exe_file_from_task](https://github.com/falcosecurity/libs/blob/master/driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c#L244C26-L244C53))

## Additional information

https://en.wikipedia.org/wiki/Fileless_malware

**Comment by galofir-ms** [comment]
bumping this issue. 
We need this feature for our commitments to product & sales team

**Comment by galofir-ms** [comment]
As per our discussion we should close this issue in favor of new issues split up. 
I cannot close since I didnt open it
