### ISSUE TITLE
run: Support socket enricher

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1920]
Support programs that use the socket enricher (pkg/gadgets/internal/socketenricher/tracer.go) as described in the design document https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/design/002-containerized-gadgets.md#socket-enricher

**Comment by alban** [comment]
The gadgets currently using the socket enricher are:
1. network gadgets using the Attacher interface:
  a. trace dns
  b. trace network
  c. trace sni
2. gadgets using tracepoints:
  a. trace tcpdrop
  b. trace tcpretrans

The two categories use different socket enricher APIs:
1. network gadgets: `struct sockets_value *gadget_socket_lookup(const struct __sk_buff *skb)`
2. tracing gadgets: `struct sockets_value *gadget_socket_lookup(const struct sock *sk, __u32 netns)`

We don't support the Attacher interface in containerized gadgets yet (see #1919). So I can start with the support for the socket enricher in containerized gadgets using tracepoints.

The tcpdrop gadget requires the enum conversion (#1928) which is not supported yet. So I will start with adding tcpretrans in `gadgets/`.
