### ISSUE TITLE
run: Definition file is lacking default values

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1922]
The [definition file](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/design/002-containerized-gadgets.md#definition-file) is used to specify the columns should be printed for a gadget. Currently, the defaults for the columns' attributes are the zero value. This creates issues, for instance, if the width is not specified, the columns is not printed:

```ỳaml
...
  - name: fname
    #min_width: 24
    #width: 32
    order: 1006
    visible: true
...
```

```bash
$ go run -exec "sudo -E" ./cmd/ig/. run --prog @./gadgets/trace_open_x86.bpf.o --definition @./gadgets/trace_open.yaml 
INFO[0000] Experimental features enabled                
RUNTIME.CONTAINERNAME                                                                             PID     COMM             UID      GID      RET              
mycontainer2                                                                                      70812   wget             0        0        -2               
mycontainer2                                                                                      70812   wget             0        0        -2               
mycontainer2                                                                                      70812   wget             0        0        -2               
mycontainer2                                                                                      70812   wget             0        0        -2        

# ^^^ notice the missing fname column in this output
```

We define some [defaults](https://github.com/inspektor-gadget/inspektor-gadget/blob/f0abba4ffb99a7efc15b598fb5f8344b60cca43b/pkg/columns/options.go#L28), but they aren't taken into consideration when unmarshaling from yaml. It'd be nice to support them, so the defaults are used when an attribute is not specified.

There are some discussions and ideas in https://github.com/go-yaml/yaml/issues/165 about how to make it work with the yaml library. 

Notice that https://github.com/inspektor-gadget/inspektor-gadget/issues/1921 intends to make this file optional, but even in that case we'll like to have some reasonable defaults for the attributes when the definition file is used.

**Comment by claudiamarcubina** [comment]
Unassigning as the issue is being handled in #2107.
