### ISSUE TITLE
Implement image handling commands for containerized gadgets

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1923]
Implement the commands as specified in https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/design/002-containerized-gadgets.md#user-experience. 

Ongoing work on https://github.com/inspektor-gadget/inspektor-gadget/pull/1863

**Comment by burak-ok** [comment]
Image handling is complete.
Running from an oci image is tracked in https://github.com/inspektor-gadget/inspektor-gadget/issues/1875
