### ISSUE TITLE
Panic on unknown event when generating network policies

### ISSUE THREAD

**Issue by shaojini** [inspektor-gadget/inspektor-gadget#1978]
## Description

[ 1 paragraph concisely describing the bug ]
Panic on unknown event when generating network policies according to the instructions on "demo":

root@k8s-master:~# kubectl gadget advise network-policy monitor -n demo --output ./networktrace.log
Recording 2549 events into file "./networktrace.log"...^C
Terminating...

root@k8s-master:~# kubectl gadget advise network-policy report --input ./networktrace.log > network-policy.yaml
panic: unknown event

goroutine 1 [running]:
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor.(*NetworkPolicyAdvisor).eventToRule(_, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, 0x177f7eff3dca04ee, ...}, ...})
        /root/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor/advisor.go:218 +0x47f
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor.(*NetworkPolicyAdvisor).GeneratePolicies(0xc000507c78)
        /root/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor/advisor.go:334 +0x1085
github.com/inspektor-gadget/inspektor-gadget/cmd/kubectl-gadget/advise.runNetworkPolicyReport(0x35bbaa0?, {0x22b1331?, 0x2?, 0x2?})
        /root/inspektor-gadget/cmd/kubectl-gadget/advise/network-policy.go:134 +0xb6
github.com/spf13/cobra.(*Command).execute(0x35bbaa0, {0xc000378ec0, 0x2, 0x2})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x35bc620)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /root/inspektor-gadget/cmd/kubectl-gadget/main.go:84 +0x2c5

root@k8s-master:~# kubectl get pods -n demo
NAME                                     READY   STATUS     RESTARTS   AGE
adservice-58687bcc69-vvmcr               1/1     Running    0          94s
cartservice-589b794f8c-7jw6w             1/1     Running    0          95s
checkoutservice-5f96895bb9-2w64r         1/1     Running    0          96s
currencyservice-75f64cdfc9-wb2zr         1/1     Running    0          95s
emailservice-57657d7877-rdlnv            1/1     Running    0          96s
frontend-747fd686b9-zqfbw                1/1     Running    0          95s
loadgenerator-79886b7895-krws7           0/1     Init:0/1   0          95s
paymentservice-77dbcbb75c-4s8xw          1/1     Running    0          95s
productcatalogservice-74b9cd9b4f-zww2k   1/1     Running    0          95s
recommendationservice-6f465c9475-ln75n   1/1     Running    0          96s
redis-cart-665784d5db-npfl4              1/1     Running    0          95s
shippingservice-854d764747-zr6gd         1/1     Running    0          95s

root@k8s-master:~# kubectl get pods -n demo
NAME                                     READY   STATUS    RESTARTS   AGE
adservice-58687bcc69-vvmcr               1/1     Running   0          6m22s
cartservice-589b794f8c-7jw6w             1/1     Running   0          6m23s
checkoutservice-5f96895bb9-2w64r         1/1     Running   0          6m24s
currencyservice-75f64cdfc9-wb2zr         1/1     Running   0          6m23s
emailservice-57657d7877-rdlnv            1/1     Running   0          6m24s
frontend-747fd686b9-zqfbw                1/1     Running   0          6m23s
loadgenerator-79886b7895-krws7           1/1     Running   0          6m23s
paymentservice-77dbcbb75c-4s8xw          1/1     Running   0          6m23s
productcatalogservice-74b9cd9b4f-zww2k   1/1     Running   0          6m23s
recommendationservice-6f465c9475-ln75n   1/1     Running   0          6m24s
redis-cart-665784d5db-npfl4              1/1     Running   0          6m23s
shippingservice-854d764747-zr6gd         1/1     Running   0          6m23s

## Impact

[ 1 sentence detailing the impact this bug is creating for you ]

## Environment and steps to reproduce

1. **Set-up**: [ describe the environment Flatcar/Lokomotive/Nebraska etc was running in when encountering the bug; Platform etc. ]
2. **Task**: [ describe the task performing when encountering the bug ]
3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. [ requested the start of a new pod or container ]
  b. [ container image downloaded ]
4. **Error**: [describe the error that was triggered]

Linux: ubuntu1~20.04.1
Kernel: 5.4.0-156-generic

## Expected behavior

[ describe what you expected to happen at 4. above but instead got an error ]
Generating the network policies successfully.

## Additional information

Please add any information here that does not fit the above format.

**Comment by sstarcher** [comment]
Just hit a similar issue
```
❯ kubectl gadget advise network-policy report -n xx --input ./networktrace.log
panic: unknown event

goroutine 1 [running]:
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor.(*NetworkPolicyAdvisor).eventToRule(_, {{{{0xc000043220, 0x1c}, {0xc000388a50, 0x8}, {0xc000638f60, 0x2b}, {0xc0000f2558, 0x11}}, 0x177fa26af5716028, ...}, ...})
	/home/runner/work/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor/advisor.go:218 +0x47f
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor.(*NetworkPolicyAdvisor).GeneratePolicies(0xc0004bdd88)
	/home/runner/work/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor/advisor.go:323 +0x745
github.com/inspektor-gadget/inspektor-gadget/cmd/kubectl-gadget/advise.runNetworkPolicyReport(0x365f760?, {0x26e866f?, 0x4?, 0x4?})
	/home/runner/work/inspektor-gadget/inspektor-gadget/cmd/kubectl-gadget/advise/network-policy.go:128 +0xb6
github.com/spf13/cobra.(*Command).execute(0x365f760, {0xc00061f840, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x3660160)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/home/runner/work/inspektor-gadget/inspektor-gadget/cmd/kubectl-gadget/main.go:52 +0x25
```

**Comment by alban** [comment]
It seems to be #1793.

Do you use exactly the same version between the CLI and the daemon set?

**Comment by sstarcher** [comment]
```
❯ kubectl gadget version
Client version: v0.13.0
Server version: v0.13.0
```

**Comment by sstarcher** [comment]
I manually installed 0.19.0 and my problem is fixed

**Comment by shaojini** [comment]
The issue can be closed.
