### ISSUE TITLE
[RFE] Confusing error message when misusing flag `ig run --prog`

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1993]
## Current situation

All `ig` flags can use the character `@` to refer to the content of a file, see for example:
https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/gadgets/script.md#script-files

But sometimes, this brings confusing error messages when the `@` character is forgotten:

```
$ sudo -E ./ig run --prog ./gadgets/trace_open_arm64.bpf.o --definition ./gadgets/trace_open.yaml
INFO[0000] Experimental features enabled                
Error: calling custom parser: getting value struct: loading spec: bad magic number '[46 47 103 97]' in record at byte 0x0
```

```
$ sudo -E ./ig run --prog hello --definition ./gadgets/trace_open.yaml
INFO[0000] Experimental features enabled                
Error: calling custom parser: getting value struct: loading spec: EOF
```

## Impact

Users are confused because the error message does not indicate that `@` is missing.

## Ideal future situation

No confusing error message.

## Implementation options

- Add a hint in the error message
- Do not require `@` to load a file for some flags like `--prog` and `--definition`

## Additional information

Maybe this issue will go away when using OCI containers is implemented.

**Comment by mauriciovasquezbernal** [comment]
> Maybe this issue will go away when using OCI containers is implemented.

I think the issue will be almost gone in that case, but perhaps we want to keep the `--prog` and `--definition` parameters for developing purposes. Also, the same issue exists for all cases when the parameter represents the content of a file, like the prometheus gadget.

**Comment by mauriciovasquezbernal** [comment]
That flag isn't supported anymore by the run command, so this issue can be closed.
