### ISSUE TITLE
image-based gadgets: Implement golang API

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2021]
There are cases where a user might want to integrate Inspektor Gadget on their application directly. It was done before by directly using the gadgets (https://github.com/inspektor-gadget/inspektor-gadget/tree/main/examples/gadgets/basic/trace/exec), but this approach won't be possible anymore now that we're implementing the gadgets as containerized gadgets.

We should hence provide a golang API to make this possible as stated in the design doc -> https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/design/002-containerized-gadgets.md#running-gadgets-directly

**Comment by flyth** [comment]
Current high-level API state with custom exporter: https://gist.github.com/flyth/e686d44235d8d7145c6f25aea0bf296a

**Comment by mauriciovasquezbernal** [comment]
This was mostly fixed by #2512. #2753 introduced some examples. 

There are still a couple of things to improve, but we can mark this as done. 

- #2893
- #2891
- #2892
