### ISSUE TITLE
Remove dependency on libseccomp

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2028]
We use [libseccomp-golang](https://github.com/seccomp/libseccomp-golang) that is a wrapper around [libseccomp](https://github.com/seccomp/libseccomp), hence libseccomp is needed and CGO must be enabled. This is not so good as having this dependency complicates builds and makes it difficult to run Inspektor Gadget on all systems. 

This was reported on slack https://kubernetes.slack.com/archives/CSYL75LF6/p1694520761890979

```
challenging external dependency on libseccomp Hi folks, as you know we're using inspektor in our
observability agent, and we would like to expand its capabilities to include seccomp profiles.
However in order to add that, I need to set CGO_ENABLED=1 and have libseccomp-dev installed in my
Docker builder step. This is annoying since I was relying on cross-compilation with buildkit to have
speedy builds... which is now almost impossible to achieve with CGO and an external lib. It is also
annoying to have these external libs in a container, whereas I used to have a single binary. Is
there a hard requirement on libseccomp or can I still have my application as a pure Go program?
```

and

```
adding to this, the functionality IG gets from
[github.com/seccomp/libseccomp-golang](http://github.com/seccomp/libseccomp-golang) seems to be very
limited in comparison with the effect on build/runtime complexity
```

We only use libseccomp go for translanting a syscall name to its number, and vice versa, hence it's not a hard dependency. 

https://github.com/inspektor-gadget/inspektor-gadget/blob/94011ce68f2ba5ed106dc0cca72a8c94bb136b90/pkg/gadgets/advise/seccomp/tracer/tracer.go#L97

https://github.com/inspektor-gadget/inspektor-gadget/blob/0eeb7f19d53882e15dedf9247f6a331d4d1b0e14/pkg/gadgets/traceloop/tracer/tracer.go#L139

### Implementation options

~~We can use https://pkg.go.dev/golang.org/x/sys/unix#SignalName and https://pkg.go.dev/golang.org/x/sys/unix#SignalNum to replace that~~

Edit: Those links I provided are for signals, not syscalls.

**Comment by amitschendel** [comment]
Can I take it?

**Comment by mauriciovasquezbernal** [comment]
For sure, I assigned it to you, don't hesitate to ask any question you might have.

**Comment by amitschendel** [comment]
https://github.com/inspektor-gadget/inspektor-gadget/pull/2054
