### ISSUE TITLE
image-based gadgets: Support BTFGen

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2045]
[BTFGen](https://kinvolk.io/blog/2022/03/btfgen-one-step-closer-to-truly-portable-ebpf-programs/) helps to support programs in kernels that don't expose BTF information. We support this for builtin gadgets and we should support it for containerized gadgets too. It seems to me the easiest way would be to provide all BTF information in a new layer on the OCI image, then this information will be provided to the cilium ebpf library before loading the programs into the kernel. All of this should be integrated with the [image build command](https://github.com/inspektor-gadget/inspektor-gadget/pull/2020) so the user doesn't have to generate these files manually.

**Comment by alban** [comment]
> It seems to me the easiest way would be to provide all BTF information in a new layer on the OCI image

There are many BTF files: one for each supported kernel version.

For the builtin gadgets, they are all embedded with a single `go:embed` in a `embed.FS` variable.

Should the BTF files be in a compressed tarball inside an OCI layer of type `application/vnd.gadget.btf.v1+binary`?

**Comment by mauriciovasquezbernal** [comment]
> Should the BTF files be in a compressed tarball inside an OCI layer of type application/vnd.gadget.btf.v1+binary?

Yes, I think it's the easiest way to implement it while reusing the logic in https://github.com/inspektor-gadget/inspektor-gadget/tree/main/pkg/btfgen. 

> Or can a single BTF file embed several BTF dataset along with the kernel version they refer to?

That's not supported by BTF. It's designed to contain the information for a single kernel.

**Comment by alban** [comment]
The BTFGen step in the CI takes 12 minutes. If we want to use BTFGen in the `image build` command, it needs to be optimized to take a reasonable time.

The BTFHub database should be indexed by symbol instead of indexed by kernel version.

**Comment by mauriciovasquezbernal** [comment]
> The BTFGen step in the CI takes 12 minutes. If we want to use BTFGen in the image build command, it needs to be optimized to take a reasonable time.

The approach we have in Inspektor Gadget is to disable it for developing purposes, and it's only done in the CI, at release or when pushing to main. Also, btfhub-archive is few GBs big right now, so probably most of the users don't want to use it when developing on their local machines.

> The BTFHub database should be indexed by symbol instead of indexed by kernel version.

Could you please elaborate more on this idea?
