### ISSUE TITLE
image-based gadgets: Gadgets testing considerations

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2046]
We have integration tests for the built-in and some image-based gadgets in https://github.com/inspektor-gadget/inspektor-gadget/tree/main/integration. We should provide a way for gadget-developers to easily implement integration tests for their gadgets too. In order to support this, we need:

1. Way to run ig: Wrapper around cmd.Exec (until we have a proper API #2021)
2. Way to generate events: Run commands in real containers: We already have some logic for that:
   - docker (https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/docker.go)
   - containerd (https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/containerd.go). 
3. Way to capture and compare events: We have some "match" functions in https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/run_helpers.go. We need to improve them a lot to be easier to use, but they are a good starting point.

[LFX](https://mentorship.lfx.linuxfoundation.org/project/65719d46-b71f-4778-a29b-3bb878d6ec70)

**Comment by ShivamAhir** [comment]
Hello, I am very interested in this project and would like to contribute in this season of LFX;)

**Comment by ahsenkamal** [comment]
Hi @mauriciovasquezbernal I'd love to contribute to this during this LFX term. Are there any resources to go through and any pre-tests for applying?
