### ISSUE TITLE
[EPIC] Implement a Global Trace Controller

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#206]
## Current situation

#197 implemented a controller for the Trace custom resource. Each trace runs on a single node without interacting with other nodes.

## Impact

That's good for gadgets that can run individually on a single node without collaboration with other instances on other nodes, but that's not enough otherwise. For example, a proper implementation of the Network Policy Advisor would need to look at the network traffic from all nodes to build coherent network policies, otherwise it only has a partial view. Users can create one Trace resource per node, but then the results from each node are currently not merged into one set of network policies.

## Ideal future situation

We could have a `GlobalTrace` resource and a controller that allows gadgets to aggregate results from individual `Trace` resources into one coherent result.

## **Implementation options

![Network-Policy-Advisor-with-CRD](https://user-images.githubusercontent.com/27575/126513758-ee970d60-e659-4e78-9349-108634021650.png)

**Comment by mauriciovasquezbernal** [comment]
We don't know yet if we want to implement a Global Trace Controller. This is something we're discussing in https://github.com/inspektor-gadget/inspektor-gadget/issues/673, hence I'll close it and continue the discussion there.
