### ISSUE TITLE
containerized-gadgets: K8s fields aren't grouped in its own object when using json

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2066]
```bash
$ sudo -E ./ig run ghcr.io/blanquicet/trace_open:latest -o jsonpretty
...
{
  "runtime": {
    "runtimeName": "containerd",
    "containerId": "554d8d8ee425ecfc071ed6ae18bd2f08f134108728f9c55130ad3a0b62cc4e98",
    "containerName": "etcd",
    "containerImageName": "k8s.gcr.io/etcd:3.5.0-0"
  },
  "node": "",
  "namespace": "kube-system",
  "pod": "etcd-master",
  "container": "etcd",
  "hostnetwork": false,
  "timestamp": "1970-01-01T00:00:00.000000000Z",
  "mntns": 4026532395,
  "pid": 1688,
  "comm": "etcd",
  "uid": 0,
  "gid": 0,
  "ret": 15,
  "flags": 524288,
  "fname": "/var/lib/etcd/member/wal",
  "mntns_id": 4026532395
}
```
vs 

```bash
$ sudo -E ./ig trace open -o jsonpretty
...
{
  "runtime": {
    "runtimeName": "containerd",
    "containerId": "554d8d8ee425ecfc071ed6ae18bd2f08f134108728f9c55130ad3a0b62cc4e98",
    "containerName": "etcd",
    "containerImageName": "k8s.gcr.io/etcd:3.5.0-0"
  },
  "k8s": {
    "namespace": "kube-system",
    "podName": "etcd-master",
    "containerName": "etcd"
  },
  "timestamp": 1695234039704630306,
  "type": "normal",
  "mountnsid": 4026532395,
  "pid": 1688,
  "gid": 0,
  "comm": "etcd",
  "fd": 15,
  "ret": 15,
  "flags": [
    "O_RDONLY",
    "O_CLOEXEC"
  ],
  "flagsRaw": 524288,
  "mode": "----------",
  "path": "/var/lib/etcd/member/wal"
}

```

This happens because k8s fields are not a "subcolumn":

https://github.com/inspektor-gadget/inspektor-gadget/blob/18f3a8cdfddf3db73b1c730742bb6fffd81dfd10/pkg/types/types.go#L161

It can be fixed by adding `column:"k8s"`, but that will create other issues. 

ref https://github.com/inspektor-gadget/inspektor-gadget/pull/2015#pullrequestreview-1636098789

**Comment by mauriciovasquezbernal** [comment]
It was faster than expected, thanks @mqasimsarfraz for the fix!

**Comment by blanquicet** [comment]
Mmmmmm why was it already in a sub-struct name "k8s" in `ig trace open` if the `column:"k8s"` was missing?

**Comment by mauriciovasquezbernal** [comment]
built-in gadgets use the standard json parser, then the structure was there because it's part of the commondata

https://github.com/inspektor-gadget/inspektor-gadget/blob/1c7cdb37f26aee4a9a74fe832b69ebaee649ace1/pkg/types/types.go#L154-L162

containerized gadgets use a different json parser (https://github.com/inspektor-gadget/inspektor-gadget/tree/main/pkg/columns/formatter/json) that only takes into consideration the columns tag.
