### ISSUE TITLE
[RFE] tcpdump / wireshark cap/pcap output for tcp trace

### ISSUE THREAD

**Issue by ledroide** [inspektor-gadget/inspektor-gadget#2074]
## Current situation

Output options for tcp trace only cover json, jsonpretty, yaml, columns.

```console
$ kubectl gadget trace tcp --help | egrep '--output'
  -o, --output string          Output format (json, jsonpretty, yaml, columns).
```
## Impact

I could not find a way to import the tcp trace output to [wireshark](https://github.com/wireshark/wireshark) for further analysis.
Wireshark native format for input data is pcapng, but it can import [multiple formats](https://www.wireshark.org/docs/wsug_html_chunked/ChIOOpenSection.html#ChIOInputFormatsSection), including pcap, from [libpcap](https://github.com/the-tcpdump-group/libpcap) / [tcpdump](https://github.com/the-tcpdump-group/tcpdump) 

## Ideal future situation

New output option(s), that can be redirected to a file, that can be imported and usable under wireshark-like tools.

**Comment by mauriciovasquezbernal** [comment]
`trace tcp` only traces specific events for tcp connections (Trace TCP connect, accept and close). We have thought about implement a tcpdump like gadget, there is even a WIP PR in https://github.com/inspektor-gadget/inspektor-gadget/pull/1097, but we haven't finished it yet.
