### ISSUE TITLE
Parameter title is not displayed when using `--help`

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#2077]
`Parameter.Title` is not displayed when using `--help`:

```bash
$ ./ig trace open --help
...
                               
      --full-path              
  -h, --help                   help for open
```

The parameter is defined here:
https://github.com/inspektor-gadget/inspektor-gadget/blob/dbacb0139cb99bf5ddec716df14a70742f7f6334/pkg/gadgets/trace/open/tracer/gadget.go#L49-L54

**Comment by mauriciovasquezbernal** [comment]
Was it fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/2079? @eiffel-fl
