### ISSUE TITLE
run: Implement `--pull` argument

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2101]
The run command only pulls an image if it's not present on the node. This behavior can create some confusion as the image being run not always matches the remote one. This is the exact same issue docker folks faced some years ago -> https://github.com/moby/moby/issues/13331.

### Implementation Options

Add a `--pull` argument that can be `missing` (default), `never` or `always` (same as docker run). The handling of the `latest` tag needs to be taken into consideration, Kubernetes always tries to pull images with that tag by default (https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy), I'm not sure what's the behavior of Docker or other container runtimes.

**Comment by alban** [comment]
I slightly prefer the behaviour of Kubernetes, even if it is more complicated (different default pull policy depending on the tag).
