### ISSUE TITLE
run: `--insecure` is not supported

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2142]
Image commands like push and pull allow to interact with insecure registries by using the `--insecure          Allow connections to HTTP only registries` flag. However it's not present on the `run` command:

```bash
$ ./kubectl-gadget run 192.168.1.150:5000/gadget/foo:latest 
INFO[0000] Experimental features enabled                
Error: getting gadget info: getting gadget info: rpc error: code = Unknown desc = getting gadget info: getting gadget image: pulling image "192.168.1.150:5000/gadget/foo:latest": downloading to local repository: failed to resolve 192.168.1.150:5000/gadget/foo:latest: Get "https://192.168.1.150:5000/v2/gadget/foo/manifests/latest": http: server gave HTTP response to HTTPS client

$ ./kubectl-gadget run 192.168.1.150:5000/gadget/foo:latest --insecure
INFO[0000] Experimental features enabled                
Error: unknown flag: --insecure
```

We should add this flag to the run command so we're able to run images from insecure registries. For sure, it's mainly interesting for testing purposes.

**Comment by kwakubiney** [comment]
I can pick this up

**Comment by kwakubiney** [comment]
I can pick this up

**Comment by mauriciovasquezbernal** [comment]
I assigned you, thanks! 

Please let us know if you have any question or run into any troubles.

**Comment by kwakubiney** [comment]
I might be mistaken but running `kubectl-gadget run` results in an unknown command for `run` but the PR description implies that this command exists. I would like more light to be shed on that? I did do some digging myself to figure it out but saw no such command in the codebase.

**Comment by mqasimsarfraz** [comment]
@kwakubiney `kubectl-gadget run` is indeed available. You will need to enable [experimental features](https://www.inspektor-gadget.io/docs/latest/install/#kubectl-gadget) to have it. You can do this in development as:

```
$ export IG_EXPERIMENTAL=true
$ make minikube-deploy
```

**Comment by burak-ok** [comment]
Just some further information:

>I did do some digging myself to figure it out but saw no such command in the codebase.

Currently all commands regarding images `ig image pull/build/...` live in [cmd/common/image](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/cmd/common/image)

The commands for runnable gadgets (be it the "classic" gadgets or the new "run" command) are located in [pkg/gadgets](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/pkg/gadgets). There the runnable gadgets have a definition from where a mechanism picks them up and sets the corresponding `cobra` commands and flags

For `run` this is definied in [pkg/gadgets/run/tracer/run.go](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/gadgets/run/tracer/run.go#L46-L80)

**Comment by kwakubiney** [comment]
Thanks for the help. @burak-ok @mqasimsarfraz
