### ISSUE TITLE
gadgets: Implement built-in trace-sni gadget as image-based gadget

### ISSUE THREAD

**Issue by claudiamarcubina** [inspektor-gadget/inspektor-gadget#2194]
Part of #2032

**Comment by mauriciovasquezbernal** [comment]
Was it fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/2322? /cc @claudiamarcubina

**Comment by claudiamarcubina** [comment]
> Was it fixed by #2322? /cc @claudiamarcubina

Hi Mauricio,

Yes, it was fixed by #2322. Thank you for noting!
