### ISSUE TITLE
v0.22.0 - issue with --auto-mount-filesystems 

### ISSUE THREAD

**Issue by galofir-ms** [inspektor-gadget/inspektor-gadget#2258]
## Description
Running ig binary inside a linux container (tried with ubuntu 20, 22 and mariner):
`ig trace exec --ignore-errors --auto-mount-filesystems --cwd --host -o json=+runtime,+k8s`
end ups failing

## Impact
IG trace is not streaming events to stdout as it fails to initialize

## Environment and steps to reproduce

1. **Set-up**:  
- AKS Cluster
- Ubuntu image that copies ig binary from `ghcr.io/inspektor-gadget/ig:v0.22.0`
- Deploy image to cluster
- SSH to pod and run command `ig trace exec --ignore-errors --auto-mount-filesystems --cwd --host -o json=+runtime,+k8s`
3. **Task**: Running ig trace exec to collect process creation events

4. **Error**: 
![image](https://github.com/inspektor-gadget/inspektor-gadget/assets/146319678/8ec4718a-a1aa-4982-bc59-d75caf58eb2d)

## Expected behavior
ig should run properly and print events to stdout

**Comment by alban** [comment]
According to https://www.kernel.org/doc/html/latest/trace/ftrace.html#the-file-system:
* Before Linux 4.1, tracefs is mounted at `/sys/kernel/debug/tracing`.
* After Linux 4.1, tracefs is mounted at `/sys/kernel/tracing` but it should still be mounted in the old location for compatibility.

Our code only checks the new location.

In @galofir-ms 's setup, both paths are mounted on the host. And in the container, there is a host volume for `/sys/kernel/debug` but not for the new tracefs location. But it seems to be the same for IG by default in [deploy.yaml#L217](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/resources/manifests/deploy.yaml#L217), so I am not sure.

I think our code should check both locations.

**Comment by mauriciovasquezbernal** [comment]
I did some investigation on this. It turns out it was also broken by https://github.com/inspektor-gadget/inspektor-gadget/commit/d1bccf6c124fc41dcda6cc8d63ae7b98732db736 (part of v0.22.0) and then fixed by https://github.com/inspektor-gadget/inspektor-gadget/commit/e988658dd898d9b1d71359243c297d931b73064b (part of v0.23.0). 

@galofir-ms  could you please check if v0.23.0 works fine for you?
Thanks
