### ISSUE TITLE
[RFC] Discussion about bug fix release

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#2297]
## Current situation

At the moment, we do not have a dedicated process to handle bug fix release.

## Impact

It can be troublesome for people in the community to either use `latest` or wait for another release (the waiting time is, in the worst cast, one month).

## Ideal future situation

We have bug fix release which fixes the latest release when a bug is found.

## Implementation options

We have two possible paths:

1. Cherry-picking and back porting the bug fix commit on top of the latest release. The advantage is that we ensure the back ported commits are stable, but it would need extra work to keep the branch, cherry-pick the commit and deal with conflict while applying it.
2. Doing a new release with the whole commit history when the bug fix commit is merged. This is easier, but it can introduce a bugged commit in the latest release if one was one added in the meanwhile.

**Comment by mauriciovasquezbernal** [comment]
I've always said not to make any backporting stuff. But now that I think better, without any backporting it is very difficult for us to make a bug fix release as the main branch could be on a state that is not ready for a release (features partially implemented, known-bugs, etc).

I'll propose to go with the first option supporting a single release branch as discussed in the community meeting.

**Comment by mayasingh17** [comment]
Do we have a process for identifying high priority bugs vs those that can wait until an "official" release? I assume we want to have these bug fix releases as infrequently as possible.

**Comment by mauriciovasquezbernal** [comment]
We don't have such a process, we'll need to create it as part of this discussion.

**Comment by mauriciovasquezbernal** [comment]
> We should have a stable branch named, for example, stable-vX.Y.Z

I think it should be release-vX.Y (minor is not needed as all bug fix commits for the same release go to the same branch). Like release-v0.23 and from there we can tag v0.23.0 (when making the release), v0.23.1, v0.23.Z (when making bug fix releases)

> Let's reduce the bus factor: no one is responsible of the bug fix release. If you are a maintainer here and open bug fix PR, you should backport it to stable-vX.Y.Z.

Who (and when) will make the release?

> If backporting needs to modify the commit(s), you should open a PR here against stable-vX.Y.Z, so everyone can review the modified commit(s) to ensure it is correct before it being merged (it can be error prone to backport commit)

I'd rather always use a PR. It seems a bit off to push to the branch in some occasions and using a PR in others.
