### ISSUE TITLE
Cannot Find Manifest example to use ig in Kubernetes

### ISSUE THREAD

**Issue by Shivangx01b** [inspektor-gadget/inspektor-gadget#2303]
Hi, I was trying to read the ig docs at  https://www.inspektor-gadget.io/docs/v0.23.1/ig/ 
While going through the doc I fount the following url https://www.inspektor-gadget.io/docs/v0.23.1/ig/examples/pod-ig.yaml which should give as a example of a manifest. But the url is not present. Can you please provide one ?

**Comment by mauriciovasquezbernal** [comment]
Related https://github.com/inspektor-gadget/inspektor-gadget/issues/2254.

**Comment by mauriciovasquezbernal** [comment]
Closing as @eiffel-fl provided the right link. Please reopen if we're missing anything. We'll track the relative paths bug in https://github.com/inspektor-gadget/inspektor-gadget/issues/2254.
