### ISSUE TITLE
[RFE] Documenting eBPF parameters in image-based gadgets

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#2374]
## Current situation

#2119 / #1927 implemented eBPF parameters in image-based gadgets but without documentation.

## Impact

Users don't know how to make use of it.

## Ideal future situation

- [Gadget helper API](https://inspektor-gadget.io/docs/latest/reference/gadget-helper-api/): section for `GADGET_PARAM`
- [ig image build command](https://inspektor-gadget.io/docs/latest/core-concepts/images/#build): explain how to write a `ebpfParams` section in `gadget.yaml` (I wonder if we should have a separate reference documentation for `gadget.yaml`?)
- Optional: [Hello world gadget](https://inspektor-gadget.io/docs/latest/devel/hello-world-gadget/): add an example (not sure about this one)

## Implementation options

- Edit docs/core-concepts/images.md
- Edit docs/reference/gadget-helper-api.md

## Additional information

```
$ git grep GADGET_PARAM -- docs/
$ git grep ebpfParams -- docs/
```

cc @burak-ok

**Comment by mauriciovasquezbernal** [comment]
I think we also need to document those parameters from the user point of view. Perhaps it can be done in #2726.

**Comment by mauriciovasquezbernal** [comment]
Related #2727

**Comment by mauriciovasquezbernal** [comment]
Params are now documented in the gadgets' docs:

Some examples:
- https://www.inspektor-gadget.io/docs/latest/gadgets/trace_bind#flags
- https://www.inspektor-gadget.io/docs/latest/gadgets/trace_exec#flags
