### ISSUE TITLE
Support a Configuration File

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2493]
Inspektor Gadget has a lot of parameters that can be configured at run time. Currently, all those parameters must be specified in the CLI, however this approach is not flexible, and it should be possible to define those parameters on a file to: 

- Avoid the user having to type them all the time it uses the CLI. It should be possible to override the values by using the CLI though.  
- Allow the user to configure Inspektor Gadget when running gadgets without the CLI as describe in the “Declarative way to run gadgets” case. 

These are the parameters we should support through the configuration file. Many of them are already exposed in the CLI (try running kubectl gadget or ig without any argument to see them) 

### Workarounds 

- Auto mount file systems: Automatically mount bpffs, debugfs and tracefs if they are not already mounted 
- Auto sd unit restart: Automatically run in a privileged systemd unit if lacking enough capabilities 
- Auto wsl workaround: Automatically find the host procfs when running in WSL2 

### Container runtimes (docker, cri-o, containerd, podman) 

- Namespace (only for containerd?) 
- Socket paths  
- Enable/disable: if IG should try to contact that container runtime 

### OCI registry  

- Credentials 
- Bool flag indicating if this is an insecure registry 
- Security policies (TODO add link to security issue) 

### Exporters  
- Prometheus 
  - Metrics listen address: Address to serve Prometheus metrics on 
  - Metrics path: Path to export Prometheus metrics on 

## kubectl-gadget 

- API server connection: How to connect to the k8s API server. (It seems some of them are inherited from the kubeconfig) 
  - connection-timeout 
  - request-timeout 
  - client-certificate 
  - client-key 
  - insecure-skip-tls-verify 
  - kubeconfig 
  - server 
  - tls-server-name 
   - token 
- Specific IG connection params 
  - tcp-port 
- gadget-namespace 
- verbose 

## gadgetctl 

- connection-timeout 
- remote-address: Comma-separated list of remote address (gRPC) to connect to (default "unix:///var/run/ig/ig.socket") 
- Verbose 

## Implementation options 

A lot of projects already use any sort of configuration file, so it’s a well-known approach in the industry. Projects like https://github.com/spf13/viper should contain all the support we need for this.

**Comment by mqasimsarfraz** [comment]
Although https://github.com/inspektor-gadget/inspektor-gadget/pull/2831 was merged I will keep this issue for follow-up work:
- Support for ig-k8s
- Add unit/integration tests
- See if we can improve getting all the operators, currently `GetDataOperators()` might miss some but it needs to be looked into.
