### ISSUE TITLE
[RFE] gadgets: Separate Event data structure by related fields 

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#250]
## Current situation

As discussed in  https://github.com/kinvolk/inspektor-gadget/pull/238#discussion_r700284527, the socket-collector gadget uses the Event data structure which is not really suitable because socket-collector is not an event-based gadget.

## Impact

It is not really an issue but could cause confusion.

## Ideal future situation

An initial proposal is:

Split `eventtypes.Event` into one named `Kubernetes` with `Node`, `Namespace`, `Pod` and `Container`, `Host` fields. Then, I would create another one named `Event` which includes `Kubernetes` and adds `Err`, `Ready` and `Notice` fields. This new data structure would replace the old `eventtypes.Event`.
 
Starting from that, the DNS gadget can create its own (Maybe `DnsEvent`) based on `Event` as it was before, while socket-collector would create one based on `Kubernetes` and adds its own fields, resulting in something that would finally deserve to be called `Socket`.

**Comment by mauriciovasquezbernal** [comment]
https://github.com/kinvolk/inspektor-gadget/commit/bbb2524ce621ed6dbb7aaa3fe044f88e75f3bab6 introduced a `CommonData` structure as you described it here. It's still missing to update the socket collector to use it.

**Comment by mauriciovasquezbernal** [comment]
I think this is not needed anymore as we're focusing on image-based gadgets now (#1929). @blanquicet WDYT?

**Comment by blanquicet** [comment]
Agree. Closing based on previous comment.
