### ISSUE TITLE
Unable to Delete GKE Cluster if Job is Cancelled During Cluster Creation

### ISSUE THREAD

**Issue by mqasimsarfraz** [inspektor-gadget/inspektor-gadget#2535]
Currently, we're encountering an issue where attempting to delete a Google Kubernetes Engine (GKE) cluster results in a 400 error if a running job is cancelled during the cluster creation process:

```
ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
 - ResponseError: code=400, message=Operation operation-1708671573108-f885d274-4b3b-414c-b595-2563466f79c5 is currently creating cluster ig-ci-gke-amd64-5476. Please wait and try again once it is done.
```
This can lead to unused clusters which need to be cleaned up manually:

- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/8015620779/job/21896454066
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/8015620779/job/21896454066

and we can end up running into quotas issue.

## Workaround

Clean up the clusters manually using: `gcloud container clusters delete ...`

## Possible Solutions

We can run a nightly job to delete all the clusters / cluster resources old than a day. We can use tags to achieve this!

**Comment by burak-ok** [comment]
> ## Possible Solutions
> We can run a nightly job to delete all the clusters / cluster resources old than a day. We can use tags to achieve this!

Even if this might not be the final solution, this could be implemented fast :tm: So I would go for that
