### ISSUE TITLE
[Discussion] image-based gadgets: How to mark the maps used by a gadget to generate information?

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2560]
## Introduction

The gadgets generate information using different kind of maps: tracers use perf event arrays or ring buffers, snapshotters use ebpf iterators and toppers and profilers use hashmaps. Inspektor Gadget needs to know what are the maps (and the types) that are used by the gadget to generate the information in order to be able to run the gadget and collect the information it generates. 

Currently Inspektor Gadget supports two ways to set this information. Any of the two methods needs to be used. If both methods are used, Inspektor Gadget validates that them contain the same information.

### Metadata file 

The metadata file, besides other things, allows to set the kind of information that is provided by the gadget:

- https://github.com/inspektor-gadget/inspektor-gadget/blob/8c433c4b29399cabd6ac233933c602f76c3c7c5f/gadgets/trace_exec/gadget.yaml#L3-L6
- https://github.com/inspektor-gadget/inspektor-gadget/blob/79eb65512419557898554ad063536b59bb38bf1c/gadgets/top_file/gadget.yaml#L3-L6
- https://github.com/inspektor-gadget/inspektor-gadget/blob/0ac7b3d565b6f5775cccbe3595c1eea5a6b91871/gadgets/snapshot_process/gadget.yaml#L3-L5

### `GADGET_` macros

There are some `GADGET_` macros defined in in [include/gadget/macros.h](https://github.com/inspektor-gadget/inspektor-gadget/blob/7cdf64eac0d1f943152b602abee2421e961f355e/include/gadget/macros.h) that allow to set this information directly in the ebpf code of the gadget: 

- https://github.com/inspektor-gadget/inspektor-gadget/blob/9949c29dfe45e9622d8e5f5e603c954ea25294e2/gadgets/trace_exec/program.bpf.c#L60
- https://github.com/inspektor-gadget/inspektor-gadget/blob/79eb65512419557898554ad063536b59bb38bf1c/gadgets/top_file/program.bpf.c#L68
- https://github.com/inspektor-gadget/inspektor-gadget/blob/f01ffa9821808fb7b40673c873110f83dc0de2f6/gadgets/snapshot_process/program.bpf.c#L32

The current implementation uses the metadata file as the single source of truth, these macros are used  to populate the metadata if this is missing when running the gadget

https://github.com/inspektor-gadget/inspektor-gadget/blob/78058fb246bedc6107fb2660ac5b8e063e61c90a/pkg/gadgets/run/tracer/run.go#L166-L169

Or to generate it when --update-metadata is used when building the gadget image

https://github.com/inspektor-gadget/inspektor-gadget/blob/c067ec3411ce5b341bda9a3443c7e4f5cb39aeed/pkg/oci/build_metadata.go#L117-L119

## Issue 

While implementing #2132 @blanquicet mentioned this approach wasn't too clear and opened #2518, #2498. There is some discussion on #2518 and also on our developer sync, but there isn't an agreement yet. Additionally, #2512 appears to be changing this behavior too, so it's time to discuss and make a decision on this.

There are different ways to implement this:

### 1. Optional `GADGET_` macros and metadata 

(current approach)

As mentioned above, the current implementation allows to use any of the two ways. 

- Advantages
  - There's is more flexibility as users can choose the way better fits their needs
- Disadvantages
  - Having two ways to define the same creates confusion
  - We need to validate information matches when both ways are used at the same time

### 2. Mandatory `GADGET_` macros 

(Suggested in https://github.com/inspektor-gadget/inspektor-gadget/pull/2518#issuecomment-1956593517 and used by #2512)

- Advantages
  - The metadata file can always be generated from the code when using `--update-metadata`
  - There is not confusion as the macros are always needed
- Disadvantages
  - All users will be forced to use it

### 3. Mandatory metadata

- Advantages
  - Single source of truth 
- Disadvantages
  - Metadata will always be required, even if the user doesn't want to configure advance attributes
  - Users will need to write their metadata file by hand 

### 4. Best effort approach to automatically detect maps and structures used

We could have some logic to automatically detect the maps and structures used by the gadget.
- tracers: look for perf event array or ring buf and `event` structure
- toppers: look for hashmaps (value information can be automatically gathered from BTF information of the map)
- snapshotters: look for iterator programs and `entry` structure

- Advantages
  - Very simple as the user don't need to worry about specifying it
- Disadvantages
  - Whole approach is based on "magic" that relies on type names 
  - Could fail to automatically detect the information (not all hashmaps are used for sending "top" information)
  - Doesn't work if gadget implements multiple way to show information (multiple tracers, multiple toppers, etc.)

**Comment by blanquicet** [comment]
I'm all for the option 2 as I [suggested](https://github.com/inspektor-gadget/inspektor-gadget/pull/2518#issuecomment-1956593517). 

I would add another advantage:

- The metadata file can always be generated **and kept updated** from the code when using `--update-metadata`.

I think it is important because if users don't use the macro and they make some changes on the code, they will need to manually update the metadata accordantly.

Regarding the disadvantages:

- All users will be forced to use it: IMO, that's a valid price to pay for having the functionalities mentioned in the advantages.

**Comment by alban** [comment]
I prefer option 2 too.

Note that the macros just define some constants with `__attribute__((unused))`. Users don't have to use the macros and they can define the constants themselves. In the end, the way to define those constants is part of the [gadget helper API](https://inspektor-gadget.io/docs/v0.25.1/reference/gadget-helper-api/) and it should be documented there, since this is the ABI between IG and a gadget.

A ebpf module in a gadget could be implemented in Rust. In that case, the C macros would not be used, but it can still define those constants and therefore follow the gadget helper API.

**Comment by blanquicet** [comment]
This issue has been open for a month. IMO, we can conclude that we will go for option 2. 

Additionally, https://github.com/inspektor-gadget/inspektor-gadget/pull/2512 already made the macro implicitly mandatory as metadata info is used only as a validator for tracer/snapshot definitions. Everything is driven by the global variables defined by the `GADGET_TRACER` and `GADGET_SNAPSHOTTER` macros.

**Comment by mauriciovasquezbernal** [comment]
I'd agree to go with number 2 then. However IMO macros are too limited (at least by using them just to store information in the name of a variable), hence I want to explore and discuss an alternative to them, for instance something like @blanquicet makes a lot of sense to me https://github.com/inspektor-gadget/inspektor-gadget/pull/2637#discussion_r1548894860.
