### ISSUE TITLE
run/top/file: Sorting is not working properly

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#2566]
## Description

As mentioned during https://github.com/inspektor-gadget/inspektor-gadget/pull/2132 review, the sort is not working properly:

- [Sort on the server side](https://github.com/inspektor-gadget/inspektor-gadget/pull/2132#discussion_r1362705716).
- [Sort by strings is not working](https://github.com/inspektor-gadget/inspektor-gadget/pull/2132#pullrequestreview-1898505393).

## Impact

Output is not always properly sorted.

## Additional information

This should be solved on top of https://github.com/inspektor-gadget/inspektor-gadget/pull/2512.

**Comment by mauriciovasquezbernal** [comment]
I tried sorting by strings and it's working now. Are we still missing sorting on the server? @blanquicet

**Comment by blanquicet** [comment]
No, we already sorting on both sides.
