### ISSUE TITLE
[RFE] run/toppers: Possible improvements for reading ebpf program's output

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#2567]
As mentioned during https://github.com/inspektor-gadget/inspektor-gadget/pull/2132 review, the user space code for collecting and cleaning up eBPF program's output could be improved using the following suggestions: 

- [Study the possibility of using `Iterate()`](https://github.com/inspektor-gadget/inspektor-gadget/pull/2132#discussion_r1500282176).
- [Study the possibility of using `BatchLookupAndDelete()`](https://github.com/inspektor-gadget/inspektor-gadget/pull/2132#discussion_r1500282806)

**Comment by mauriciovasquezbernal** [comment]
@blanquicet it's not about bpf code nor for the top file gadget. It's to be done in the Inspektor Gadget side and will affect all toppers.

**Comment by blanquicet** [comment]
> @blanquicet it's not about bpf code nor for the top file gadget. It's to be done in the Inspektor Gadget side and will affect all toppers.
>
Oops, you're right. I'll update the title and the description. Thanks!

**Comment by blanquicet** [comment]
Done by https://github.com/inspektor-gadget/inspektor-gadget/pull/3182
