### ISSUE TITLE
[RFE] gadget/socket-collector: Improve management of socket from pods with hostNetwork=true

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#258]
## Current situation

As discussed in https://github.com/kinvolk/inspektor-gadget/pull/247#discussion_r701822737:

> if there are several pods with hostNetwork=true, then the host network namespace will be inspected several times, and the sockets will be reported several times.

## Ideal future situation

It still needs to be defined but probably the host sockets will be filtered out and maybe a CLI flag will be added to allow users to include host information.

## Additional information

PR https://github.com/kinvolk/inspektor-gadget/pull/249 is addressing this for DNS gadget.

**Comment by mauriciovasquezbernal** [comment]
> if there are several pods with hostNetwork=true, then the host network namespace will be inspected several times, and the sockets will be reported several times.

This is not true anymore. I'm not sure when it was fixed, but the logic uses a map indexed by net namespace to avoid visiting the same multiple times 

https://github.com/inspektor-gadget/inspektor-gadget/blob/d61e5ef270f118e4f51f20c99224b2cc1dac83d2/pkg/gadgets/snapshot/socket/tracer/tracer.go#L217

I tried the following experiment and the socket is only reported once:

```bash
# Nothing on port 5001
$ go run -exec "sudo -E" ./cmd/ig/. snapshot socket | grep 5001
INFO[0000] Experimental features enabled                

# start a container on the host net ns listening in 5001
$ docker run -d --net=host --name=mycontainer3 busybox sh -c "nc -l -s 127.0.0.1 -p 5001"
49a3fd8be2f36fed28926d24f9b11857345d6553f8a6b0277ef4f983b09cd03c

# another container on host net ns doing nothing 
$ docker run -d --net=host --name=mycontainer4 busybox sh -c "sleep 9999"
23371e191ac456d226d1d86de1e82bff78d4ae8cc78f55ee83f82e67483b367c

# only one socket is reported
$ go run -exec "sudo -E" ./cmd/ig/. snapshot socket | grep 5001
INFO[0000] Experimental features enabled                
                               TCP              127.0.0.1:5001                           0.0.0.0:0                                LISTEN 
```

Please reopen if you think it's still an issue.
