### ISSUE TITLE
Adding PPID in tracepoint based gadgets

### ISSUE THREAD

**Issue by amitschendel** [inspektor-gadget/inspektor-gadget#2645]
## Current situation

ppid field missing in some the tracers.

## Ideal future situation

Include the ppid in the event data.

## Implementation options

[Slack discussion with guidance ](https://kubernetes.slack.com/archives/CSYL75LF6/p1711450813873579)

## Additional information

[ Please Add any information that does not fit into any of the above sections here ]

**Comment by amitschendel** [comment]
keep

**Comment by mauriciovasquezbernal** [comment]
We'll track this on #1567
