### ISSUE TITLE
WithInitialKubernetesContainers missing enrichment

### ISSUE THREAD

**Issue by amitschendel** [inspektor-gadget/inspektor-gadget#2660]
## Current situation

Using `WithInitialKubernetesContainers` gets all the containers from the api server but doesn't enrich them with runtime metadata.

## Impact

Forces using `WithContainerRuntimeEnrichment` in order to list the initial containers.

## Ideal future situation

Adding enrichment.

## Implementation options

[ Optional: please provide one or more options for implementing the feature requested ]

## Additional information

[ Please Add any information that does not fit into any of the above sections here ]

**Comment by blanquicet** [comment]
Hi @amitschendel, that's the expected behaviour. Enriching containers with runtime metadata implies additional calls to the runtime for each container, thus it's not done by default but only if requested.

**Comment by amitschendel** [comment]
This requires the user to implement the logic of figuring the container runtime and then doing the enrichment. I would expect ig to have this logic built in.

**Comment by blanquicet** [comment]
You can initialize `WithMultipleContainerRuntimesEnrichment(rc)` with all the runtimes:

```go
    rc := []*containerutilsTypes.RuntimeConfig{
	    {Name: "docker"},
	    {Name: "containerd"},
	    {Name: "crio"},
    }
```

And IG will find the proper runtime for each container and enrich it with the runtime metadata.
