### ISSUE TITLE
CI: Cancelling concurrent jobs on main can cause (weird) issues

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2728]
I was investigating why the `trace_dns` was broken:

```bash
# latest at the time of writing this issue
$ sudo -E ig run trace_dns@ha256:4df44b97f3a8413ebea56aa2739339f7dfd8dfda102adcfe8276f9ecbdca6cf6f6
# $ sudo -E ig run trace_dns:latest
RUNTIME.C… S… S… D… D… MNT… NET… PID     TID    UID      GID      TASK   ID     QTYPE   P… R… L… NAME      ANCO… ANAD… TIME… SRC.… DST.…
ERRO[0001] starting operator "ebpf": creating eBPF collection: program ig_trace_dns: load program: invalid argument: Unreleased reference id=257 alloc_insn=116: BPF_LD_[ABS|IND] cannot be mixed with socket references (truncated, 1056 line(s) omitted)
```

After running `git bisect` few times and not understanding what was going on, I realized our ebpf-builder image is out of sync. 5d125f4912cd1dccbfaea2fc68ee74c3c3129943 updated the include/gadget/sockets-map.h file, but it wasn't updated on the  `latest` version of the builder image:

```bash 
# file on git tree
$ sed -n 69p /usr/include/gadget/sockets-map.h
        __u8 proto;

# file on builder image
# this is the latest tag at the time of writing this issue
$  docker run --rm -it ghcr.io/inspektor-gadget/ebpf-builder@sha256:0fb401f1b52c35384ee47ece2e4d191e1d5102968eed50e6d0baab405f1b86b0
# $ docker run --rm -it ghcr.io/inspektor-gadget/ebpf-builder:latest bash -c "sed -n 69p /usr/include/gadget/sockets-map.h"
        __u16 proto;
```

It happened because the job on charge of building the image after merging #2579 was cancelled https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/8361463092

We have some logic to avoid cancelling concurrent jobs on main
https://github.com/inspektor-gadget/inspektor-gadget/blob/1657d70bb57f540d3783d2b1df44101ce072cb5e/.github/workflows/inspektor-gadget.yml#L13

but, there is still possible that a job is skipped if it was pending when a new PR is merged:

> When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any pending job or workflow in the concurrency group will be canceled. This means that there can be at most one running and one pending job in a concurrency group at any time.

(from https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency)

The image hasn't been rebuild recently because there is some logic to skip that job:

https://github.com/inspektor-gadget/inspektor-gadget/blob/1657d70bb57f540d3783d2b1df44101ce072cb5e/.github/workflows/inspektor-gadget.yml#L845-L852

### Implementation Options

- daily job that compiles all images, but it doesn't seem clean to me.
- use manual trigger (workflow_dispatch)

**Comment by mauriciovasquezbernal** [comment]
I manually built and pushed the ebpf-builder image and the dns gadget to fix the issue in the meanwhile. 

This approach however won't work once we start signing the images, so we'll need to find a way to allow to rebuild those images on request (workflow_dispatch?).

**Comment by mqasimsarfraz** [comment]
That is a nasty issue. I feel like the right way to avoid this is to build the helper images every time we merge something in `main`. I mean the idea of conditional build is to not impact PRs by always building these images and the current implementation takes care of that well. What is left is how to keep the `main` sync and for that we just build it on each merge similar to what we do for [releases](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/.github/workflows/inspektor-gadget.yml#L863). What do you say?

**Comment by mauriciovasquezbernal** [comment]
I think that's a good idea, opened #2737.
