### ISSUE TITLE
"kubectl-gadget completion" errors out instead of just creating the completion file.

### ISSUE THREAD

**Issue by johanneskastl** [inspektor-gadget/inspektor-gadget#2773]
## Description

I am trying to package kubectl-gadget for openSUSE: I wanted to package the completion files.
With many other packages it is enough to just issue `something completion bash > some/file` and package the results.

The same happens with the installed package, this also errors out  but does not output the completion.

I also downloaded the latest release, it also errors out:

```
$ ./kubectl-gadget completion bash
FATA[0000] Searching for running Inspektor Gadget instances: Get "http://localhost:8080/apis/apps/v1/daemonsets?fieldSelector=metadata.name%3Dgadget&labelSelector=k8s-app%3Dgadget": dial tcp [::1]:8080: connect: connection refused 
$
```

## Impact

Only `gadgetctl` has bash completion in the package, but not `kubectl-gadget`

## Environment and steps to reproduce

1. Build the kubectl-gadget binary.
1. Call it and give it the `completion bash` command
1. It fails with the error given above

## Expected behavior

Completion should be printed out.

**Comment by mauriciovasquezbernal** [comment]
Thanks a lot @johanneskastl for opening this issue. #2774 should fix it. Are you able to try it out?

On a broader comment, perhaps we should provide our own completion scripts to be able to complete k8s things like pod, containers, namespaces, etc. I'll open an issue about it.

**Comment by johanneskastl** [comment]
Thanks for the fast fix. I can check if I can add the patch to the local build later today.

**Comment by johanneskastl** [comment]
Had some minutes and tested this. The patch worked perfectly, now the completions could be built for kubectl-gadget as well. Thanks!

**Comment by johanneskastl** [comment]
On a related note:

The `kubectl-gadget version` command fails, if it has no connection, and does not even give the client version. Should I open a new issue for this? As it is not as easy to fix as this one?

**Comment by mauriciovasquezbernal** [comment]
I updated #2774 to also handle this case. Can you check it out?

**Comment by johanneskastl** [comment]
> I updated #2774 to also handle this case. Can you check it out?

I'll try, but the patch does not apply properly to 0.27.0. Will have a look on the weekend...

**Comment by mauriciovasquezbernal** [comment]
You'll need to clone the branch directly as there have been other modifications in between.

**Comment by johanneskastl** [comment]
I know, but that messes up the whole packaging logic... :-)

**Comment by johanneskastl** [comment]
OK, I built based on your branch:

```
$ kubectl-gadget version
Client version: v0.27.0
Error: searching for running Inspektor Gadget instances: Get "http://localhost:8080/apis/apps/v1/daemonsets?fieldSelector=metadata.name%3Dgadget&labelSelector=k8s-app%3Dgadget": dial tcp [::1]:8080: connect: connection refused
$
```

So it successfully shows the client version before erroring out due to no server connection.

(I just set the version to 0.27.0 during build for $REASONS)

**Comment by johanneskastl** [comment]
@mauriciovasquezbernal 

Should this be in 0.28.0 or 0.28.1? Because the build with these versions still errors out during generating the completions:

```bash
[   47s] + /home/abuild/rpmbuild/BUILDROOT/inspektor-gadget-0.28.1-0.x86_64//usr/bin/gadgetctl completion bash
[   52s] time="2024-05-18T10:14:23Z" level=warning msg="could not load gadget info from remote: dialing random target: dialing \"unix:///var/run/ig/ig.socket\" (\"local\"): dialing \"unix:///var/run/ig/ig.socket\" (\"local\"): context deadline exceeded"
[   52s] time="2024-05-18T10:14:23Z" level=warning msg="Failed to load deploy info: opening info file: open /home/abuild/.ig/info.json: no such file or directory"
[   52s] + /home/abuild/rpmbuild/BUILDROOT/inspektor-gadget-0.28.1-0.x86_64//usr/bin/kubectl-gadget completion bash
[   52s] time="2024-05-18T10:14:23Z" level=fatal msg="Searching for running Inspektor Gadget instances: Get \"http://localhost:8080/apis/apps/v1/daemonsets?fieldSelector=metadata.name%3Dgadget&labelSelector=k8s-app%3Dgadget\": dial tcp 127.0.0.1:8080: connect: connection refused"
[   52s] error: Bad exit status from /var/tmp/rpm-tmp.DqGdDm (%install)
```

**Comment by mauriciovasquezbernal** [comment]
The commit fixing it is not part of any release yet (https://github.com/inspektor-gadget/inspektor-gadget/commit/09a33a396d00f3af4e2997ab0270c28d5350654d). It should be part of v0.29.0 that we'll release in two weeks.

**Comment by johanneskastl** [comment]
Thanks for the fast confirmation, then I'll wait until 0.29.0 is out before sending the package to Tumbleweed.

Have a nice week!

**Comment by johanneskastl** [comment]
Sorry to warm this up, but the `version` output is still broken with `kubectl gadget version` 0.29.0:

```
$ kubectl gadget version
I0607 21:49:38.572014    8154 versioner.go:58] invalid configuration: no configuration has been provided
Client version: v0.29.0
Error: searching for running Inspektor Gadget instances: Get "http://localhost:8080/apis/apps/v1/daemonsets?fieldSelector=metadata.name%3Dgadget&labelSelector=k8s-app%3Dgadget": dial tcp [::1]:8080: connect: connection refused
$ echo $?
1
$
```

Is it intentional that this exits with return code 1 if no kubeconfig was provided?

**Comment by mauriciovasquezbernal** [comment]
I haven't thought about this use case, however, I see kubectl has the same behavior (to return an error code 1 when the server can't be contacted):

```bash
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
The connection to the server localhost:8080 was refused - did you specify the right host or port?
$ echo $?
1
```

Is this an issue for you? What are you trying to accomplish?

**Comment by johanneskastl** [comment]
Good point regarding kubectl.

I am merely used to other tools just printing out their version, without erroring out if the kubeconfig is missing or not provided. I stumbled upon this because I thought of adding a simple "check" to the package to make sure the version output is valid, i.e. does not break in the future. There a return code of 1 is not helpful. :-)

But if you would like to keep the current behaviour I am also fine.

**Comment by mauriciovasquezbernal** [comment]
I'd prefer to keep the same kubectl behavior.

**Comment by johanneskastl** [comment]
OK, perfectly reasonable.

Thanks for your help!
