### ISSUE TITLE
container-hook: map gets full and it stops working

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#2789]
## Description

The "execs" ebpf map from execruntime.bpf.c gets full under a specific workload and then container-hook stops working.

This is very similar to a previous bug in the trace exec gadget: #2424. This was fixed in:
- https://github.com/inspektor-gadget/inspektor-gadget/pull/2454
- https://github.com/inspektor-gadget/inspektor-gadget/pull/2475

## Impact

Commands such as `kubectl-gadget trace exec` stop returning early events because new containers are not detected by container-hook anymore. However, new containers are detected by the "podinformer" fallback, so further events are detected and the issue is not very visible.

## Environment and steps to reproduce

The reproducer workload is similar to the one in #2424 but with failing `syscall.Exec`. When running it in a loop, at some point the map is full:

```
$ sudo bpftool map dump name exec_args|grep key|wc -l
128
```

## Expected behavior

* The `exec_args` map does not get full
* container-hook is able to detect new containers
* Gadgets can reliably report early events

## Additional information

The fix is going to be slightly different than #2454 and #2475 because `kretprobe/fsnotify_remove_first_event` needs to lookup the exec_args map by tgid because `struct fanotify_event` contains the tgid and not the pid.

Alternatively, we can try to fix this by removing parts of the ebpf code as suggested on https://github.com/inspektor-gadget/inspektor-gadget/pull/2764#discussion_r1583310422

cc @matthyx

**Comment by matthyx** [comment]
nice catch!
