### ISSUE TITLE
traceloop show fails with `message larger than max`

### ISSUE THREAD

**Issue by qxmips** [inspektor-gadget/inspektor-gadget#2868]
kubectl gadget traceloop show 33e588d70d7fdf6c837d727f4d1c6e067aaf7bdd03f96db26449a26a747c8411
CPU PID        COMM             SYSCALL                      PARAMS                                                                                                                  RET
Error: unmarshaling output: invalid character '\x1b' looking for beginning of value
Error: failed to receive stream on node "ip-10-11-85-0.ec2.internal": command terminated with exit code 1d message larger than max (12984636 vs. 4194304)

**Comment by alban** [comment]
I suspect we need to change this line:
https://github.com/inspektor-gadget/inspektor-gadget/blob/b9c34d89947cf8d56589205f98f8476c727f8060/pkg/gadget-collection/gadgets/traceloop/gadget.go#L446

in this way:

```diff
-trace.Status.OperationError = fmt.Sprintf("failed to unmarshal output: %s", err)
+trace.Status.OperationError = fmt.Sprintf("failed to unmarshal output %q: %s", t.trace.Status.Output, err)
```

This would be consistent with what was done in https://github.com/inspektor-gadget/inspektor-gadget/pull/714/files
