### ISSUE TITLE
[RFC] New gadget: fsnotify-enricher

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#2903]
RFC: should fsnotify-enricher remain an external gadget or moved to the main Inspektor Gadget repository?

## Current situation

There are no in-tree gadgets tracing the usage of the inotify/fanotify Linux API.

There is one but it is on an external repository:
https://github.com/alban/fsnotify-enricher

## Impact

- Changes to the fsnotify-enricher gadget are not reviewed by the Inspektor Gadget team
- Maintenance is more difficult.
  - For example, IG recently required to use char for strings (see 2607fcdc62ec82cee49d9115a0b7bb186f7e2a34)
```diff
-  __u8 tracer_comm[TASK_COMM_LEN];
+  char tracer_comm[TASK_COMM_LEN];
```

## Ideal future situation

There are a rule of thumb saying when it makes sense to add a gadget in-tree or develop it out-of-tree.

## Implementation options

1. Add fsnotify-enricher to the main repository
2. Archive the external repository

## Additional information

The fsnotify-enricher gadget is tracing the fsnotify APIs (both inotify and fanotify) in a generic way. The ebpf code was originally inspired from the [container-hook pkg](https://github.com/inspektor-gadget/inspektor-gadget/blob/370de192e1bd4326acb85db5ff09834e0f353e94/pkg/container-hook/bpf/execruntime.bpf.c#L89-L90) but it was made generic.

It is useful as a debugging tool for developers of applications using fsnotify APIs because it reveals more information than strace can provide (e.g. both tracer and tracee process metadata).

It is also useful to use as a Go package in applications using fsnotify APIs. Developers would then use the IG Go API. In this scenario, the application would typically filter events from one specific inotify or fanotify file descriptor. The `tracer-group` ebpf param is designed for this. The benefit is the same: it can enrich events you get from the kernel API with additional metadata such as inode information, tracer/tracee process metadata including when running in a different pid namespace (in a container or a Kubernetes pod).

**Comment by flyth** [comment]
IMHO it should become a part of the main repo until we move all image-based gadgets out again (and then it'll still stay in our org). That way we can "guarantee" compatibility with all the changes that are happening right now.

**Comment by alban** [comment]
@flyth Thanks. I'll make a PR to add the gadget to the main repo.
