### ISSUE TITLE
[RFE] K8s Enrichment: Container Start Time

### ISSUE THREAD

**Issue by galofir-ms** [inspektor-gadget/inspektor-gadget#2961]
We would like to have an additional field in k8s enrichment: Container start time. AFAIK we can use the proc/x file created time.

@alban

**Comment by dorser** [comment]
@galofir-ms if the container creation timestamp works, then enriching it from the container runtime is pretty straightforward. I started working on something here: https://github.com/inspektor-gadget/inspektor-gadget/compare/main...dorser:inspektor-gadget:enrich-with-created-at

**Comment by dorser** [comment]
Spoke with @galofir-ms offline, the ask is for start time.

**Comment by galofir-ms** [comment]
> Does it have to be in the k8s enrichment or can we add it to the runtime enrichment?

I think we usually use k8s enrichment, but runtime works too AFAIK
