### ISSUE TITLE
gadgets: Implement trace fsslower as image based one

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2994]
Port [trace fsslower](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/pkg/gadgets/trace/fsslower) to be an image-based gadget.

**Comment by burak-ok** [comment]
Needs dynamic binding of eBPF programs to tracepoints/kprobes. Depending on the user provided runtime parameter

**Comment by mauriciovasquezbernal** [comment]
> Needs dynamic binding of eBPF programs to tracepoints/kprobes. Depending on the user provided runtime parameter

Exactly! This will handled by #3132 and #3131.
