### ISSUE TITLE
gadgets: Finish implementing trace tcpdrop as image-based gadget

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2996]
- convert fields of original proc_ctx to struct (https://github.com/inspektor-gadget/inspektor-gadget/pull/2477#discussion_r1484672309)
- once we support bitfield to string conversion (https://github.com/inspektor-gadget/inspektor-gadget/issues/2482), update event->tcpflags type (https://github.com/inspektor-gadget/inspektor-gadget/pull/2477#discussion_r1483555007)

**Comment by burak-ok** [comment]
> * convert fields of original proc_ctx to struct ([Add trace_tcpdrop image based gadget #2477 (comment)](https://github.com/inspektor-gadget/inspektor-gadget/pull/2477#discussion_r1484672309))

Do I remember right that we still can't have substructs in eBPF.
Additionally we would have the `mount_ns_id` in the substruct. And that woud also mean that we have it twice. (1 per substruct). So enrichment for this is kinda hard?

**Comment by mauriciovasquezbernal** [comment]
> Do I remember right that we still can't have substructs in eBPF.

We already have support for substructs. 

> Additionally we would have the mount_ns_id in the substruct. And that woud also mean that we have it twice. (1 per substruct). So enrichment for this is kinda hard?

Yeah, that's kind of an open question. @blanquicet added some warnings about this on #2877. Perhaps we should have a single field of this type and some logic to fill it from the source that is available.

**Comment by burak-ok** [comment]
> > Do I remember right that we still can't have substructs in eBPF.
> 
> We already have support for substructs.

When I played around I didn't get (at least the json) output  for the substructs. But I didn't dive deep into it

**Comment by mauriciovasquezbernal** [comment]
> convert fields of original proc_ctx to struct (https://github.com/inspektor-gadget/inspektor-gadget/pull/2477#discussion_r1484672309)

No other gadget is using a struct for common fields. I'll mark this as done and discuss it for all gadgets in a follow up issue.
