### ISSUE TITLE
Integration tests aren't run for PRs from forks

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3009]
https://github.com/inspektor-gadget/inspektor-gadget/pull/2678 added the `public-key-check` and `check-secrets` as a condition for the `build-and-push-gadgets` job. The `public-key-check` job is skipped for PRs coming from forks, this causes all integration tests to be skipped as well:

- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/9295730950
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/9373503598

This causes the CI to appear to be working, to later on find out that it wasn't working, like https://github.com/inspektor-gadget/inspektor-gadget/pull/3007 and https://github.com/inspektor-gadget/inspektor-gadget/pull/2867

Integration tests should be run also on PRs coming from forks.

**Comment by mqasimsarfraz** [comment]
This should be fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/2847, the current implementation is working fine but I want to improve it using https://github.com/inspektor-gadget/inspektor-gadget/pull/2885 to have independent steps for signing and artifact publishing!

**Comment by mauriciovasquezbernal** [comment]
We have a similar condition for dependabot's PRs: 
- [Slack's discussion](https://kubernetes.slack.com/archives/CSYL75LF6/p1718375563732039)
- [Run example](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/8845843568/job/24290561784)

**Comment by mqasimsarfraz** [comment]
I tested on the Fork and things are better: https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/9597816363 I think once we have working PR from fork/ dependabot we can close this issue!

**Comment by mqasimsarfraz** [comment]
Integration test are running fine for forks (https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/9608024796/attempts/1) so closing this issue!
