### ISSUE TITLE
[RFE] CI: Verify that BPF objects and skeletons are up-to-date

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#304]
## Current situation

The socket-collector BPF elfs were committed in PR https://github.com/kinvolk/inspektor-gadget/pull/297. The idea is to create a task in the CI to check that those binary files and the skeletons are updated with respect to what is generated by the compilation inside the `builder` container.

**Comment by marga-kinvolk** [comment]
We currently have BPF objects for all gadgets, right? Is something verifying that they are up-to-date or is this still pending?

**Comment by blanquicet** [comment]
> We currently have BPF objects for all gadgets, right? Is something verifying that they are up-to-date or is this still pending?

It is still pending.

**Comment by mauriciovasquezbernal** [comment]
Ref https://github.com/kinvolk/inspektor-gadget/pull/820.

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/1190.
