### ISSUE TITLE
pod crashing when immediate stop annotation is passed to the biolatency gadget 

### ISSUE THREAD

**Issue by ashu8912** [inspektor-gadget/inspektor-gadget#305]
## Description
While computing the latency if a stop annotation is immediately added after we added a start annotation for biolatency gadget the biolatency trace throws an error saying 
```Failed to send SIGINT to process: os: process already finished ```

## Impact
if a user immediately stops the latency check the above error keeps on popping up for all later latency checks(which i believe is because the pod crashed)

## Expected behavior

Throw the error but let the latency computation work for all subsequent annotations with a significant time gap between start and stop operations 
## Additional information
The exact error is 
```Failed to send SIGINT to process: os: process already finished (stdout: "" stderr: "Traceback (most recent call last):\n File \"/usr/share/bcc/tools/biolatency\", line 173, in <module>\n if BPF.get_kprobe_functions(b'blk_start_request'):\n File \"/usr/lib/python2.7/dist-packages/bcc/_init_.py\", line 718, in get_kprobe_functions\n elif re.match(b'^.*\\.cold(\\.\\d+)?$', fn):\n File \"/usr/lib/python2.7/re.py\", line 141, in match\n return _compile(pattern, flags).match(string)\n File \"/usr/lib/python2.7/re.py\", line 233, in _compile\n bypass_cache = flags & DEBUG\nKeyboardInterrupt\n")```

**Comment by mauriciovasquezbernal** [comment]
This took way longer than expected to fix, sorry about that. I opened https://github.com/inspektor-gadget/inspektor-gadget/pull/1188 that should fix this issue.
