### ISSUE TITLE
testing: Provide way to get image ID 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3176]
Our testing framework allows to get the ID, PID and other fields from a container:

https://github.com/inspektor-gadget/inspektor-gadget/blob/e1b1ff984d47b68092184efb74d0f093f75237df/pkg/container-utils/testutils/container_interface.go#L38-L47

However it's not possible to get the container image digest, hence we can't test it, see #3172. The container interface should provide a way to return the container image digest too.

**Comment by btwshivam** [comment]
hey, Assign me. I want to work on it

**Comment by mastersans** [comment]
Hi progress on this one seems to be stale, I am working on this one.

**Comment by btwshivam** [comment]
I'm having my university exams going on. go ahead with it😀
