### ISSUE TITLE
bpf: Enum formatter fails sometimes 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3185]
Some tests (trace_mount & trace_capabilities) are failing some times on CI.

trace_mount: https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/9983344413/attempts/2#summary-27591909684

```bash 
...
{"runtime":{"containerId":"ddd1024b48de8ff1f738b2252ec6903aa8d2d27a208a53c8a1a8bf1136bbb131","containerImageName":"docker.io/library/busybox:latest"},"k8s":{"namespace":"test-trace-mount-1703214863855454248","podName":"test-trace-mount","containerName":"test-trace-mount"},"delta":1,"flags":"foo","pid":1,"tid":1,"mount_ns_id":1,"timestamp":"foo","ret":-2,"comm":"mount","fs":"foo","src":"/mnt","dest":"/mnt","data":"","op":"MS_SILENT","call":"foo"}
expected:
{"runtime":{"containerId":"ddd1024b48de8ff1f738b2252ec6903aa8d2d27a208a53c8a1a8bf1136bbb131","containerImageName":"docker.io/library/busybox:latest"},"k8s":{"namespace":"test-trace-mount-1703214863855454248","podName":"test-trace-mount","containerName":"test-trace-mount"},"delta":1,"flags":"foo","pid":1,"tid":1,"mount_ns_id":1,"timestamp":"foo","ret":-2,"comm":"mount","fs":"foo","src":"/mnt","dest":"/mnt","data":"","op":"MOUNT","call":"foo"}
```

After formatting and removing non relevant fields, we can see the issue is that the flags and op fields are swapped: 

captured:
```json
{
    "flags": "MOUNT",
    "flags_raw": 32768,
    "op": "MS_SILENT",
    "op_raw": 0,
}
```

MS_SILENT corresponds to 32768 (0x8000) and MOUNT corresponds to 0

https://github.com/inspektor-gadget/inspektor-gadget/blob/1e825235044eba04f27ae173fd903389898ac7c2/gadgets/trace_mount/program.bpf.c#L38

https://github.com/inspektor-gadget/inspektor-gadget/blob/1e825235044eba04f27ae173fd903389898ac7c2/gadgets/trace_mount/program.bpf.c#L18

For an unknown reason, the value of op_raw is being used for flags and flags_raw for op.

The same happened for trace_capablities in https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/9994164208/attempts/1#summary-27623830074

```json
{
    "cap": "FLAG_CAP_CHOWN|FLAG_CAP_DAC_OVERRIDE|FLAG_CAP_FOWNER|FLAG_CAP_FSETID|FLAG_CAP_KILL|FLAG_CAP_SETGID|FLAG_CAP_SETUID|FLAG_CAP_SETPCAP|FLAG_CAP_NET_BIND_SERVICE|FLAG_CAP_MAC_OVERRIDE|FLAG_CAP_MAC_ADMIN|FLAG_CAP_SYSLOG|FLAG_CAP_WAKE_ALARM|FLAG_CAP_BLOCK_SUSPEND|FLAG_CAP_AUDIT_READ|FLAG_CAP_PERFMON|FLAG_CAP_BPF|FLAG_CAP_CHECKPOINT_RESTORE",
    "cap_effective": "CAP_SYS_NICE",
    "cap_effective_raw": 1531,
    "cap_raw": 23,    
}
```
Both tests have failed on "Test gadgets K8s (cri-o)", I don't know if this is coincidence or not.

I haven't been able to reproduce it locally. I looked at [the code](https://github.com/inspektor-gadget/inspektor-gadget/blob/fb35786664ca738437c19ad54b710dab6916b629/pkg/operators/ebpf/formatters.go#L69-L151) that handles it but I can't spot any reason why it should fail.

**Comment by flyth** [comment]
If we wouldn't use Go 1.22, my first speculation would be using [pointers in for-loops (enum in this case)](https://github.com/inspektor-gadget/inspektor-gadget/blob/fb35786664ca738437c19ad54b710dab6916b629/pkg/operators/ebpf/formatters.go#L78). But afaiu that's [in the past with 1.22](https://go.dev/blog/loopvar-preview)...

**Comment by flyth** [comment]
Analyzed this a bit more: it's basically an out-of-sync error regarding the GadgetInfo when using multiple nodes and non-deterministic code (the enums are handled in a non-deterministic way and thus swapped from time to time). I'll get into more details tomorrow and will also work on a fix.
