### ISSUE TITLE
[RFE] New gadget for detecting deadlocks

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#3194]
## Current situation

Inspektor Gadget does not have a gadget to detect deadlocks. The idea of a gadget for detecting deadlocks was previously mentioned in #1912 while discussing the uprobe support.

## Impact

Consider a multi-threaded application with this code pattern:

* Thread 1
```
pthread_mutex_lock(&mtx1);
pthread_mutex_lock(&mtx2);
foo()
pthread_mutex_unlock(&mtx2);
pthread_mutex_unlock(&mtx1);
```

* Thread 2
```
pthread_mutex_lock(&mtx2);
pthread_mutex_lock(&mtx1);
bar();
pthread_mutex_unlock(&mtx1);
pthread_mutex_unlock(&mtx2);
```

This lock inversion can cause a deadlock. On bigger code base, it can be difficult to figure out the problem because the pthread_mutex_lock() calls can be located in different functions.

## Ideal future situation

A gadget giving the stacks when the locks were taken.

## Implementation options

A new gadget using BPF and WASM:
* The BPF program will be attached on mutex locks and mutex unlocks functions with uprobes.
* The WASM program will build a mutex wait directed graph and look for cycles. Then, the gadget will display the stack trace showing the mutex locks causing the deadlock. 

## Additional information

It can be built upon previous work:

* Support for uprobes in Inspektor Gadget
  * https://github.com/inspektor-gadget/inspektor-gadget/issues/1912
  * https://www.inspektor-gadget.io/blog/2024/06/supporting-uprobe-based-gadgets-lfx-mentorship-report/
* BCC tools include deadlock.py doing the same
  * https://github.com/iovisor/bcc/blob/master/tools/deadlock_example.txt
  * https://github.com/iovisor/bcc/blob/master/tools/deadlock.py 

However, there are still challenges:
* Inspektor Gadget does not support dumping stack traces from userspace applications yet

**Comment by angad-singhh** [comment]
Hey @alban ,  I would like to be part of the project, it looks interesting and useful. I will start with going through the attachments provide in the issue to understand the project better. 

Thanks !

**Comment by HitanshuPrasad** [comment]
Hi @alban , i have went through the issues and things for the problem to be right up my alley, and is looking forward to working as mentee for this project.

**Comment by HitanshuPrasad** [comment]
Is there any pre-test/pre-task I can do to show my competence and interest in the project ?  As I really to be part of it.

**Comment by burak-ok** [comment]
> Is there any pre-test/pre-task I can do to show my competence and interest in the project ? As I really wish to be part of it.

Hi,
If you want you can grab some of the issues marked with `good first issue`. Or you can also just play with Inspektor Gadget and create same sample gadgets

**Comment by 836hardik-agrawal** [comment]
Hey @alban , I would like to be part of the project, it looks interesting and useful. In my computer science course we have studied about operation system . Learnt about mutex,deadlocks there .Interesting to work once again.
I have started learning about the code base and grabbing some good first issue to understand better.
Thanks !

**Comment by mauriciovasquezbernal** [comment]
I see we already have a [deadlock](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/gadgets/deadlock) gadget, is there anything missing to close this issue?

**Comment by Snehil-Shah** [comment]
@mauriciovasquezbernal The deadlock gadget is done. The only thing mentioned in the RFE that is remaining is unwinding user stack traces which is currently a WIP, but I believe we can consider it an issue separate from the deadlock gadget ([ref](https://github.com/inspektor-gadget/inspektor-gadget/pull/3457)), so feel free to close this issue.

**Comment by mauriciovasquezbernal** [comment]
Thanks for the clarification!
