### ISSUE TITLE
image-based gadgets: Implement unit tests

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3195]
Currently we are running integration tests for image-based gadgets (thanks to #2046) and unit tests for built-in gadgets (see #817), however we don't run unit tests for image-based gadgets yet. 

### Motivation 

Integration tests are a great way to check that everything is working fine, however it's difficult to check a lot of specific details in those tests. The unit tests are ideal to check that:
- The gadget provides the correct information for all fields 
- The filtering mechanism works fine (by mount namespace or other things like uid, ports, etc) 
- The gadget flags change the gadget's behavior 
- The gadget works on different kernel versions (see #1343) 

### Implementation Options 

For this support we need the following components:

- A mechanism to generate events: The existing one on https://github.com/inspektor-gadget/inspektor-gadget/tree/v0.30.0/internal/test can be used 
- A mechanism to match the result: It's already done in https://github.com/inspektor-gadget/inspektor-gadget/tree/v0.30.0/pkg/testing/match 
- A mechanism to run the gadget: It's possible to run a gadget by using the Golang API as done in https://github.com/inspektor-gadget/inspektor-gadget/tree/v0.30.0/examples/gadgets/simple/trace_open. It should be possible to create a wrapper (or even an operator) around the Golang API for testing purposes so users don't have to repeat all the same code in all tests.

**Comment by btwshivam** [comment]
Hi @mauriciovasquezbernal 
I hope this message finds you well. My name is Shivam, and I am excited to contribute to the implementation of unit tests for image-based gadgets under the LFX mentorship program.

I am eager to enhance the reliability of these gadgets and would appreciate your guidance on where to start. Could you please suggest some issues to begin with?

**Comment by HitanshuPrasad** [comment]
hi @mauriciovasquezbernal @alban ,  Interested in this project for fall term LFX. excited to solve such a problem. Thanks!

**Comment by mauriciovasquezbernal** [comment]
> Could you please suggest some issues to begin with?

Sure, I opened some new issues about missing **integration** tests we have. I think they're a good starting point to get familiar with this tasks
- https://github.com/inspektor-gadget/inspektor-gadget/issues/3235
- https://github.com/inspektor-gadget/inspektor-gadget/issues/3240

**Comment by Ali-Alnosairi** [comment]
Hey @alban @mauriciovasquezbernal,
The project sounds interesting, and I'm excited about the opportunity to implement it. I'm looking forward to LFX Term 3 starting, and hope we'll get a chance to collaborate in December .

**Comment by kairveeehh** [comment]
Hi @alban and @mauriciovasquezbernal  I am kairvee and would like to take up this project under lfx term-3 as it aligns with my skills and interests

**Comment by pandeyyyy** [comment]
Hi @alban @mauriciovasquezbernal  my skills and experience matches with this also i am currently setting up environment and started looking into the issue till then can you please tell me what's the last date for cover letter and resume submission

also please share slack link if there is

**Comment by Jeeten8205** [comment]
hello @alban @mauriciovasquezbernal 

I'm interested in the project to enhance unit testing support for Inspektor Gadget. The idea of improving testing mechanisms, particularly for gadgets and their behavior across different kernel versions, is exciting. With experience in Golang and familiarity with testing frameworks, I’m eager to contribute to this project.

Looking forward to contributing!
