### ISSUE TITLE
gadgets/top_file: File field only contains the file name

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3234]
The file field provided by this gadget only contains the name of the file:

```json 
"file": "foo.txt",
```

While running 

```bash 
 echo sdafa > /foo.txt
 echo sdafa > /bar/foo.txt
```

The file should be the absolute path inside the container. I think we can use 

https://github.com/inspektor-gadget/inspektor-gadget/blob/13cb07051c4617853983f2b1d3dc9c8296b8b626/include/gadget/filesystem.h#L80

to get it.

Any thoughts @alban?

**Comment by jbiers** [comment]
Hey @mauriciovasquezbernal, I'd like to give this issue a shot. Can you assign it to me? Any additional context needed?
