### ISSUE TITLE
gadgets/snapshot_socket: Missing tests

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3235]
The [snapshot_socket](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/gadgets/snapshot_socket) gadget is missing the tests. We can port them from the built-in gadget (https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/k8s/snapshot_socket_test.go)

**Comment by btwshivam** [comment]
hey, I would like to work on this. Please assign me.

**Comment by kairveeehh** [comment]
hii @mauriciovasquezbernal  I would like to work for this issue as it aligns with my skills and interests , could you please assign it to me so that I can work over it

**Comment by btwshivam** [comment]
@kairveeehh Hey, many similar issues are open, so go ahead. I'm currently working on this

**Comment by kairveeehh** [comment]
> @kairveeehh Hey, many similar issues are open, so go ahead. I'm currently working on this

But nobody is assigned , so ig issue is open

**Comment by mauriciovasquezbernal** [comment]
Hi folks, I assigned it to @btwshivam as they're first. @kairveeehh feel free to start working on other issues on the repo (always commenting before to avoid multiple folks working on the same).

**Comment by anujagrawal699** [comment]
@mauriciovasquezbernal I'll work on it as assignee didn't seem to be working on it.

**Comment by anujagrawal699** [comment]
@mauriciovasquezbernal I'll work on it as the assignee doesn't seem to be active.

**Comment by anujagrawal699** [comment]
@mauriciovasquezbernal The tests are failing due to timeout. Can environment setup cause this problems?
`IG_PATH=/home/anuj_agrawal/inspektor-gadget-lfx/inspektor-gadget/inspektor-gadget/kubectl-gadget IG_RUNTIME=kubernetes go test -v
=== RUN   TestSnapshotSocket
    utils.go:178: Seed used: 1723445360569292488
    command.go:92: Run command(Create test namespace):
    command.go:94: Command returned(Create test namespace):
        
        namespace/test-snapshot-socket-1636736912831736689 created
        NAME      SECRETS   AGE
        default   0         0s
        
    command.go:111: Start command(Run test-snapshot-socket)
    command.go:92: Run command(SleepForSeconds):
    command.go:94: Command returned(SleepForSeconds):
        
        
    command.go:92: Run command(WaitForTestPod):
    command.go:94: Command returned(WaitForTestPod):
        
        pod/test-snapshot-socket condition met
        
    command.go:128: Stop command(Run test-snapshot-socket)
    command.go:130: Command returned(Run test-snapshot-socket):
        
        pod/test-snapshot-socket created
        
    command.go:92: Run command(Run_snapshot_socket):
panic: test timed out after 10m0s
running tests:
        TestSnapshotSocket (10m0s)

goroutine 30 [running]:
testing.(*M).startAlarm.func1()
        /home/anuj_agrawal/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/testing/testing.go:2366 +0x385
created by time.goFunc
        /home/anuj_agrawal/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/time/sleep.go:177 +0x2d
`

**Comment by mauriciovasquezbernal** [comment]
@btwshivam are you still working on this one?
