### ISSUE TITLE
gadgets/trace_dns: Missing tests

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3236]
The [trace_dns](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/gadgets/trace_dns) gadget is missing its tests. We can port the tests from https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/k8s/trace_dns_test.go and https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/ig/non-k8s/trace_dns_test.go.

**Comment by andoriyaprashant** [comment]
Hello @mauriciovasquezbernal @burak-ok  I want to work on this issue. Please assign it to me
Thank you

**Comment by MeherRushi** [comment]
Hey @andoriyaprashant , are you still working on this issue. If not, can I work on it ?

**Comment by MeherRushi** [comment]
Hello, @mauriciovasquezbernal , I maybe missing something here but the [trace_dns](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/gadgets/trace_dns) gadget already seems to have the [test implemented](https://github.com/inspektor-gadget/inspektor-gadget/commit/84d2519362b494848d31d4ddf9cfa2fcbf87cf37).

**Comment by mauriciovasquezbernal** [comment]
You're right. When I opened this issue #3093 wasn't merged, so I forgot I was implementing the tests there. Thanks for your interest on this one and feel free to look for other issues.
