### ISSUE TITLE
gadgets/trace_tcpconnect: Missing tests 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3240]
The [trace_tcpconnect](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/gadgets/trace_tcpconnect) gadget doesn't have any test implemented. We can port the tests from https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/k8s/trace_tcpconnect_test.go.

**Comment by mastersans** [comment]
Hey @mauriciovasquezbernal can i work on this one?

**Comment by btwshivam** [comment]
hey @mastersans I'm working on it. but you can try it too!😊

**Comment by mastersans** [comment]
@btwshivam I think there are many other similar issue that you can work,since I am already working on this one.

**Comment by mauriciovasquezbernal** [comment]
> Hey @mauriciovasquezbernal can i work on this one, Could you guide me a little?

Sure. The goal is to create a new test for our trace_tcpconnect gadget. We have existing tests https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/k8s/trace_tcpconnect_test.go but those are designed for a different kind of gadgets (we call them built-in) and the framework to run them is different too. 

These are a rough list of steps you can follow:
1. Take one of the existing tests, for instance https://github.com/inspektor-gadget/inspektor-gadget/blob/main/gadgets/trace_open/test/trace_open_test.go and copy it to the trace_tcpconnect gadget
2. Update the `traceOpenEvent` with the event generated by trace_tcpconnect. You can check https://www.inspektor-gadget.io/docs/v0.30.0/guides/run/ to learn how to run a gadget.
3. Update the [command](https://github.com/inspektor-gadget/inspektor-gadget/blob/36398a3cf244e2b5b969ad06e6388392d1bfb3d9/gadgets/trace_open/test/trace_open_test.go#L70C21-L70C53) we use to generate the events. Command to use is on https://github.com/inspektor-gadget/inspektor-gadget/blob/36398a3cf244e2b5b969ad06e6388392d1bfb3d9/integration/k8s/trace_tcpconnect_test.go#L87
4. Update the expected events. Take them from https://github.com/inspektor-gadget/inspektor-gadget/blob/36398a3cf244e2b5b969ad06e6388392d1bfb3d9/integration/k8s/trace_tcpconnect_test.go#L32-L48

I hope it helps!
