### ISSUE TITLE
gadgets/trace_tcpretrans: Missing tests

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3241]
The [trace_tcpretrans](https://github.com/inspektor-gadget/inspektor-gadget/tree/main/gadgets/trace_tcpretrans) gadget doesn't have any test implemented. There is not a built-in version of this gadget, hence these tests need to be implemented from scratch.

**Comment by mastersans** [comment]
I'll like to work on this one.
