### ISSUE TITLE
[RFE] K8s Context Enrichment - Controller Kind & Name

### ISSUE THREAD

**Issue by galofir-ms** [inspektor-gadget/inspektor-gadget#3260]
Hello

We would like to be able to correlate ebpf events with the originating controller, in addition to existing enrichments such as k8s and container runtime.

I understand this might require a query to API server and a non trivial request

Lets discuss

**Comment by alban** [comment]
Done for kubectl-gadget in #3319.
For `ig`, it is not yet done.
