### ISSUE TITLE
Add support for dynamically linking eBPF programs in image based gadgets

### ISSUE THREAD

**Issue by burak-ok** [inspektor-gadget/inspektor-gadget#3274]
Some builtin gadgets like `trace fsslower` allow the user to decide which tracepoint to attach to (The user choses which filesystem format and we attach to the corresponding kprobe)

Other builtin gadgets like `top blockio` checks for the existence of tracepoints or kprobes and only then attaches to them according to what is on the system.

It would be nice if we can dynamically attach to tracepoints

**Comment by h4l0gen** [comment]
Hey @burak-ok I want to work on this issue. Can you please assign it to me. Thank you!

**Comment by burak-ok** [comment]
Correct, most gadgets are fine with hardcoded associations between the eBPF programs and tracepoints/kprobes.

As you said for some gadgets we need to make that association/linking dynamically. So at runtime and according to either user input, kernel versions or other stuff

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/3449
