### ISSUE TITLE
Error inspektor-gadget.yml

### ISSUE THREAD

**Issue by andoriyaprashant** [inspektor-gadget/inspektor-gadget#3275]
## Description

Encountering an error "Missing property 'matrix'" within the GitHub Actions YAML configuration file. Specifically, the error occurs under the "strategy: fail-fast: false" section, indicating a potential issue with the nesting or structure of the matrix property.

## Impact

The workflow fails to execute properly due to the missing matrix property, preventing the CI/CD pipeline from running the specified jobs.

## Environment and steps to reproduce

- Go to .github\workflows\inspektor-gadget.yml

## Expected behavior

The workflow should correctly recognize and utilize the matrix property within the strategy section.

**Comment by andoriyaprashant** [comment]
Hello  @mauriciovasquezbernal  @burak-ok

I encountered an error in the workflow. If you find this issue valuable, please assign it to me, and I will try to fix it

Thank you

**Comment by mauriciovasquezbernal** [comment]
Hi @andoriyaprashant, I'm not sure I follow this issue. Could you please point to the specific line in the workflow definition where this issue is?

**Comment by andoriyaprashant** [comment]
> Hi @andoriyaprashant, I'm not sure I follow this issue. Could you please point to the specific line in the workflow definition where this issue is?

Here Sir 
![image](https://github.com/user-attachments/assets/475d9e6a-6f06-43b7-9bba-0cf9f241473a)

**Comment by mauriciovasquezbernal** [comment]
Oh right, good catch! I think we need to remove those two lines. Happy to review a PR fixing it.
