### ISSUE TITLE
[EPIC]: Package Inspektor Gadget

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3304]
Inspektor Gadget provides three binaries (ig, gadgetctl and kubectl-gadget) that are available to download for different architectures and operating systems on the release page. This approach is not very user friendly, as they need to download the binary manually to get the updates, etc. 

The goal of of this issue is to create packages for:
- [ ] Windows 
   - [ ] Winget
   - and/or 
   - [ ] Chocolatey
- [ ] MacOS
   - [ ] Brew
- [ ] Linux
   - [ ] Ubuntu
   - [ ] Fedora
   - [ ] What else?

### Discussion

We can package the binaries in different ways

- option 1: Put all binaries in the single inspektor-gadget package
- option2: Put the ig + gadgetctl binaries in on package, and put kubectl-gadget in another 

I'd say option is easier for us and for the users.

(ig only will be package for Linux as it doesn't support Windows or MacOS)

**Comment by rd-michel** [comment]
can you share any updates?

ive also downloaded gadgetctl recently (manually) ... and ive asked myself "where is the corresponding brew package for this tool :) "

**Comment by mauriciovasquezbernal** [comment]
> can you share any updates?

We've packaged it for Fedora https://repology.org/project/inspektor-gadget/versions, other package managers are on the roadmap but we don't have an estimate time for them.
