### ISSUE TITLE
docs: Document filtering in user space

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3388]
https://www.inspektor-gadget.io/docs/latest/reference/run#filtering-in-user-space

The idea is to explain how to use the --filter flag:

```bash 
$ sudo ig run trace_open:latest -h 
WARN[0000] Ignoring runtime "cri-o" with non-existent socketPath "/run/crio/crio.sock" 
WARN[0000] Ignoring runtime "podman" with non-existent socketPath "/run/podman/podman.sock" 
...
  -F, --filter string                          Filter rules
                                                 A filter can match any column using the following syntax
                                                   columnName==value     - matches, if the content of columnName equals exactly value
                                                   columnName!=value     - matches, if the content of columnName does not equal exactly value
                                                   columnName>=value     - matches, if the content of columnName is greater than or equal to the value
                                                   columnName>value      - matches, if the content of columnName is greater than the value
                                                   columnName<=value     - matches, if the content of columnName is less than or equal to the value
                                                   columnName<value      - matches, if the content of columnName is less than the value
                                                   columnName~value      - matches, if the content of columnName matches the regular expression 'value'
                                                                see [https://github.com/google/re2/wiki/Syntax] for more information on the syntax
                                                        (default "")
```

**Comment by andoriyaprashant** [comment]
Hello @mauriciovasquezbernal,
I'd like to work on this issue. Could you please assign it to me
I'll open a pull request on it as soon as possible.
Thank you

**Comment by andoriyaprashant** [comment]
Sir @mauriciovasquezbernal 

I have made some changes to the 'run.mdx' file. Please take a moment to review it. If any further changes are needed, please let me know, and I will make those adjustments.

![image](https://github.com/user-attachments/assets/27a7a7a4-9fe6-498d-ba72-7518c61230da)

Thank you

**Comment by mauriciovasquezbernal** [comment]
Instead of copying and pasting the result of `sudo ig run trace_open:latest -h` there I'd like to directly document the flag there:

Something like:

The `filter` flag allows to filter events by any field that is provided by the gadget. The following syntax is used:

- columnName==value: matches, if the content of columnName equals exactly value
- columnName!=value: matches, if the content of columnName does not equal exactly value
- columnName>=value: matches, if the content of columnName is greater than or equal to the value
- columnName>value: matches, if the content of columnName is greater than the value
- columnName<=value: matches, if the content of columnName is less than or equal to the value
- columnName<value: matches, if the content of columnName is less than the value
- columnName~value: matches, if the content of columnName matches the regular expression 'value' see  [https://github.com/google/re2/wiki/Syntax] for more information on the syntax


And then add few examples:
- equal filter (comm==cat)
- not equal filter (uid!=0)
- something about regexp 
- using multiple filters at once (comm==cat, uid==0, this is cat processes executed by root) for instance. 
- other examples you think my be useful (we don´t need a look of them)

**Comment by andoriyaprashant** [comment]
@mauriciovasquezbernal 

Sir, I have made the changes you suggested. Please review them and then I'll open the pull request 

https://github.com/user-attachments/assets/29cc8e23-3af8-4104-887c-b171347ff9c2

**Comment by mauriciovasquezbernal** [comment]
hi @andoriyaprashant reviewing a video is not very efficient. Would you mind opening a PR and I'll provide feedback there?

**Comment by andoriyaprashant** [comment]
> hi @andoriyaprashant reviewing a video is not very efficient. Would you mind opening a PR and I'll provide feedback there?
Sure sir 👍🏻

**Comment by andoriyaprashant** [comment]
Sir @mauriciovasquezbernal I have opened a pull request #3402  Please check it.
Thank you
