### ISSUE TITLE
Unable to build any gadget that involves a wasm module

### ISSUE THREAD

**Issue by inaeem** [inspektor-gadget/inspektor-gadget#3427]
## Description

Unable to build any gadget that involves a wasm module

root@instance-20240717-023214:/home/user/inspektor-gadget/gadgets# sudo -E ig image build . -t newgadget:latest
INFO[0000] Experimental features enabled                
Error: source file "program.bpf.c" not found
root@instance-20240717-023214:/home/user/inspektor-gadget/gadgets# make build
Building trace_open
INFO[0000] Experimental features enabled                
Pulling builder image ghcr.io/inspektor-gadget/ebpf-builder:latest
latest: Pulling from inspektor-gadget/ebpf-builder
Digest: sha256:91de59b5099b4a90dc03ca8c600c5ec7d0e6467bbbd9be2d8a77ed61781ddc7d
Status: Image is up to date for ghcr.io/inspektor-gadget/ebpf-builder:latest
^Cmake: *** [Makefile:35: trace_open] Interrupt

**Comment by mauriciovasquezbernal** [comment]
> root@instance-20240717-023214:/home/user/inspektor-gadget/gadgets# sudo -E ig image build . -t newgadget:latest
> INFO[0000] Experimental features enabled
> Error: source file "program.bpf.c" not found

What gadget are you trying to build? You need to change directory to the specific gadget (cd trace_open, cd trace_exec, etc) or pass the path to the build command:

```bash 
$ pwd
/home/user/inspektor-gadget/gadgets
$ sudo ig image build ./snapshot_process/ -t foo
Pulling builder image ghcr.io/inspektor-gadget/ebpf-builder:latest
latest: Pulling from inspektor-gadget/ebpf-builder
Digest: sha256:1d252183b18805f9a4a9e72593b2d9c00927ba759fe11c1d2e59c53ff1cb021c
Status: Image is up to date for ghcr.io/inspektor-gadget/ebpf-builder:latest
Successfully built ghcr.io/inspektor-gadget/gadget/foo:latest@sha256:06d2e3fef7634739ec8ab72f57a8eb5337083dd509d2173a7d01bcedbd833b18
```

Please also consider this https://www.inspektor-gadget.io/docs/latest/gadget-devel/building#in-tree-gadgets-with-wasm when building gadgets with wasm modules in the tree.

**Comment by inaeem** [comment]
I guess the issue with the ig command. It hangs when it tries to build wasm modules. It never passes the 
"Status: Image is up to date for ghcr.io/inspektor-gadget/ebpf-builder@sha256:d67e78263f93d4d6bea5af38cf0d745e5453ed755318c21a9cfc14014c4adf19" and becomes unresponsive.

As you can see i am compiling built-in trace_open gadget. Is there a way to debug or print log?

user1@instance-20240717-023214:~$ sudo ig image build $IG_SOURCE_PATH/gadgets/trace_open -t trace_open
Pulling builder image ghcr.io/inspektor-gadget/ebpf-builder@sha256:d67e78263f93d4d6bea5af38cf0d745e5453ed755318c21a9cfc14014c4adf19
ghcr.io/inspektor-gadget/ebpf-builder@sha256:d67e78263f93d4d6bea5af38cf0d745e5453ed755318c21a9cfc14014c4adf19: Pulling from inspektor-gadget/ebpf-builder
Digest: sha256:d67e78263f93d4d6bea5af38cf0d745e5453ed755318c21a9cfc14014c4adf19
Status: Image is up to date for ghcr.io/inspektor-gadget/ebpf-builder@sha256:d67e78263f93d4d6bea5af38cf0d745e5453ed755318c21a9cfc14014c4adf19

**Comment by mauriciovasquezbernal** [comment]
Did you set `export IG_SOURCE_PATH=~/go/pkg/mod/github.com/inspektor-gadget/inspektor-gadget`?

If you did so, you need to run sudo with  -E to pass the env variables. `sudo -E ig image build ...`

**Comment by mauriciovasquezbernal** [comment]
I opened #3435 to fix the documentation.

**Comment by inaeem** [comment]
Just to clarify, how do I build a new gadget with WASM support? I followed all the steps in [this guide](https://www.inspektor-gadget.io/docs/v0.31.0/gadget-devel/), but I'm still unable to build the gadget. Any advice?

Here are a few questions:

- Is it still necessary to set IG_SOURCE_PATH?

- Should the new gadget be placed within the IG source path?

```powershell
export IG_SOURCE_PATH=/home/user1/inspektor-gadget/
Error: the current directory "/home/user1/mygadget" is not under the inspektor-gadget source path "/home/user1/inspektor-gadget/"
```  

- What is the purpose of adding the Inspektor Gadget dependency in a Go program?
```powershell
module main

go 1.22.5

toolchain go1.22.6

// Version doesn't matter because of the replace directive below.
require github.com/inspektor-gadget/inspektor-gadget v0.0.0
```
