### ISSUE TITLE
operators/oci: authfile and pull-secret should be global parameters

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3444]
The [authfile](https://github.com/inspektor-gadget/inspektor-gadget/blob/489a7719c992f3cb20c0f16972abfde54d6d0846/pkg/operators/oci-handler/oci.go#L102) and [pull secret](https://github.com/inspektor-gadget/inspektor-gadget/blob/489a7719c992f3cb20c0f16972abfde54d6d0846/pkg/operators/oci-handler/oci.go#L128) parameters should be global instead of instance parameters.

Tasks
- [ ] Move the parameters from InstanceParams to GlobalParams
- [ ] Update the [documentation](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/spec/operators/oci.md)

Ref https://github.com/inspektor-gadget/inspektor-gadget/pull/3406#discussion_r1740758215

**Comment by botwithlag** [comment]
Hi I am relatively new to open Source, Can you guide me a little

**Comment by mauriciovasquezbernal** [comment]
> Hi I am relatively new to open Source, Can you guide me a little

For sure. I'd recommend you to follow our contributing guide to setup your [dev env](https://www.inspektor-gadget.io/docs/latest/devel/contributing#setup-developer-environment) and [compile ig](https://www.inspektor-gadget.io/docs/latest/devel/contributing#building-ig). Once you are able to compile and run `ig` locally you can start working on this.

Let's start by just (1) moving those parameters fro the `InstanceParams` to the `GlobalParams` functions in https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/operators/oci-handler/oci.go and (2) in https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/spec/operators/oci.md. 

Once you have completed these two steps, I can guide you to the third one that is a little more complex.

**Comment by botwithlag** [comment]
I have completed the two tasks, I have gone through the #2f2a568 but I m still a bit unsure on what changes to do.

**Comment by mauriciovasquezbernal** [comment]
I was checking with more care and we don't need to do anything for kubectl-gadget, all of this was handled in #2223. Please open a PR with those two tasks.

**Comment by manas-yu** [comment]
@mauriciovasquezbernal can i open a PR, i have completed the two tasks.
