### ISSUE TITLE
Missing bpf instructions for image-based gadgets

### ISSUE THREAD

**Issue by dorser** [inspektor-gadget/inspektor-gadget#3462]
## Description

When I start an image-based gadget and it fails due to a verifier error, I don't see the bpf instructions despite passing the `-v` argument.

## Impact

Impacts gadget development experience

## Environment and steps to reproduce

1. **Set-up**: Ubuntu 22.04
2. **Task**: ig run -v <my_gadget>
3. **Action(s)**: 
Create a gadget that results in a verifier error (You can find examples [here](https://getanteon.com/blog/unveiling-ebpf-verifier-errors/#prerequisites-11d6d454-9979-43b5-8779-b52bf6e76a1e))
4. **Error**: The output is missing the bpf instructions:
```
error: starting operators: starting operator "oci": starting operator "ebpf": creating eBPF collection: program tracepoint__sys_enter_clone: load program: invalid argument: Unreleased 
reference id=3 alloc_insn=10 (28 line(s) omitted) 
```

## Expected behavior

See the bpf instructions for the gadget.

## Additional information

Applying the follow patch fixes this: https://gist.github.com/alban/25cbc5e92feb784d77ee059d5c042462

**Comment by patrickpichler** [comment]
Hey, I would like to take a stab at this (if it isn't already fixed haha).

**Comment by mauriciovasquezbernal** [comment]
@patrickpichler it's not fixed. Go for it!
