### ISSUE TITLE
You don't need to do this manually as Inspektor Gadget framework will do this for you. Please check [Enumerations documentation](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/gadget-devel/gadget-ebpf-api.md#enumerations).

### ISSUE THREAD

**Issue by mani1911** [inspektor-gadget/inspektor-gadget#3478]
You don't need to do this manually as Inspektor Gadget framework will do this for you. Please check [Enumerations documentation](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/gadget-devel/gadget-ebpf-api.md#enumerations).

However, I'm wondering how to consider the logic we had in the built-in gadget for `UDP` sockets:

https://github.com/inspektor-gadget/inspektor-gadget/blob/cf695bcf7fce116f8420436b2b874dfc97436703/pkg/gadgets/snapshot/socket/tracer/tracer.go#L63-L73

Maybe adding `STATE_ACTIVE` and `STATE_INACTIVE` to the enum and setting those two values (instead of `STATE_ESTABLISHED` and `STATE_CLOSE`, respectively) based on the protocol?

_Originally posted by @blanquicet in https://github.com/inspektor-gadget/inspektor-gadget/pull/3314#discussion_r1706727500_

**Comment by mani1911** [comment]
@blanquicet can you tell more about inspektor gadget handling enums and how I can make use of them rather than specifying enums of my own. Any reference would be appreciated

**Comment by blanquicet** [comment]
This is the documentation: https://inspektor-gadget.io/docs/latest/gadget-devel/gadget-ebpf-api#enumerations

An example is the `trace_tcp` gadget:

1) We define the enum:

https://github.com/inspektor-gadget/inspektor-gadget/blob/4c4003de9373e9aed7d656826cf2383a420429a3/gadgets/trace_tcp/program.bpf.c#L22-L26

2) Use it in the event struct:

https://github.com/inspektor-gadget/inspektor-gadget/blob/4c4003de9373e9aed7d656826cf2383a420429a3/gadgets/trace_tcp/program.bpf.c#L43

3) IG automatically translate it to the name of the enum:

```bash
$ sudo ig run ghcr.io/inspektor-gadget/gadget/trace_tcp:latest
RUNTIME.CONTAINE… SRC                     DST                     COMM            PID       TID       UID      GID TYPE
myalpine          172.17.0.2:47594        143.244.178.33:80       wget          41399     41399         0        0 connect
```

```bash
$ sudo ig run ghcr.io/inspektor-gadget/gadget/trace_tcp:latest -o jsonpretty
WARN[0000] Ignoring runtime "cri-o" with non-existent socketPath "/run/crio/crio.sock"
WARN[0000] Ignoring runtime "podman" with non-existent socketPath "/run/podman/podman.sock"
{
  ...
  "type": "connect",
  "type_raw": 0,
  ...
}
```
