### ISSUE TITLE
[RFE] Harden Inspektor Gadget with Landlock

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#3537]
## Current situation

Inspektor Gadget uses several hardening mechanism but not Landlock.
Particularly, the container image is set read-only, but this is not forcefully the case of mounted paths.

## Impact

Landlock could be used to restrict which path can be read and write.
It could be used to workaround this limitation:
https://github.com/inspektor-gadget/inspektor-gadget/blob/49a2adc716f48591a220b11f9fe78ee22e002022/charts/gadget/templates/daemonset.yaml#L184-L194

## Ideal future situation

Landlock is used to restrict which path Inspektor Gadget can read and write.

## Implementation options

An initial attempt was done in https://github.com/inspektor-gadget/inspektor-gadget/commit/21e23e702cc54a8eb872ba5fcf95b07a70a143ad.

Sadly, using Landlock makes the call to `os.Stat(/host/proc/1/ns/pid)` fails with `EPERM` being returned:

```
(gdb) s
domain_scope_le (child=0x0 <fixed_percpu_data>, parent=0xffff888005cd73c0) at security/landlock/task.c:37
37              if (!parent)
(gdb) n
39              if (!child)
(gdb) p !child
$27 = 1
(gdb) bt
#0  domain_scope_le (child=0x0 <fixed_percpu_data>, parent=0xffff888005cd73c0) at security/landlock/task.c:39
#1  task_is_scoped (child=0xffff8880041c0000, parent=0xffff888007ad49c0) at security/landlock/task.c:59
#2  task_ptrace (child=0xffff8880041c0000, parent=0xffff888007ad49c0) at security/landlock/task.c:70
#3  task_ptrace (parent=0xffff888007ad49c0, child=0xffff8880041c0000) at security/landlock/task.c:64
#4  0xffffffff814febf7 in security_ptrace_access_check (child=child@entry=0xffff8880041c0000, mode=mode@entry=9) at security/security.c:956
#5  0xffffffff8109f2bf in __ptrace_may_access (task=task@entry=0xffff8880041c0000, mode=mode@entry=9) at kernel/ptrace.c:346
#6  0xffffffff8109f959 in ptrace_may_access (task=task@entry=0xffff8880041c0000, mode=mode@entry=9) at kernel/ptrace.c:353
#7  0xffffffff813b5864 in proc_ns_get_link (dentry=<optimized out>, inode=<optimized out>, done=<optimized out>) at fs/proc/namespaces.c:58
#8  0xffffffff8132c351 in pick_link (flags=<optimized out>, inode=0xffff888006ff02f0, link=0xffffc90000747c58, nd=0xffffc90000747ce0) at fs/namei.c:1806
#9  step_into (nd=0xffffc90000747ce0, flags=<optimized out>, dentry=<optimized out>) at fs/namei.c:1874
#10 0xffffffff8132d4c9 in lookup_last (nd=<optimized out>) at fs/namei.c:2461
#11 path_lookupat (nd=nd@entry=0xffffc90000747ce0, flags=flags@entry=65, path=path@entry=0xffffc90000747e08) at fs/namei.c:2485
#12 0xffffffff8132ea7c in filename_lookup (dfd=dfd@entry=-100, name=name@entry=0xffff88801296d000, flags=flags@entry=1, path=path@entry=0xffffc90000747e08, root=root@entry=0x0 <fixed_percpu_data>) at fs/namei.c:2514
#13 0xffffffff813208c4 in vfs_statx (dfd=dfd@entry=-100, filename=filename@entry=0xffff88801296d000, flags=flags@entry=2048, stat=stat@entry=0xffffc90000747e88, request_mask=request_mask@entry=2047) at fs/stat.c:244
#14 0xffffffff8132107d in vfs_fstatat (dfd=-100, filename=<optimized out>, stat=0xffffc90000747e88, flags=<optimized out>) at fs/stat.c:304
#15 0xffffffff813210d6 in __do_sys_newfstatat (dfd=<optimized out>, filename=<optimized out>, statbuf=0x7ffecc114380, flag=<optimized out>) at fs/stat.c:468
#16 0xffffffff81f87268 in do_syscall_x64 (nr=<optimized out>, regs=0xffffc90000747f58) at arch/x86/entry/common.c:52
#17 do_syscall_64 (regs=0xffffc90000747f58, nr=<optimized out>) at arch/x86/entry/common.c:83
#18 0xffffffff82000130 in entry_SYSCALL_64 () at arch/x86/entry/entry_64.S:121
#19 0x00007f0ce74d9020 in ?? ()
#20 0x00005644d5bf4da0 in ?? ()
#21 0x00007ffecc114548 in ?? ()
#22 0x0000000000000000 in ?? ()
```

Indeed, Landlock does not permit a Landlock'ed process, _i.e._ Inspektor Gadget, to trace a no Landlock'ed process, _i.e._ host PID 1 _aka_ `systemd`.

There are two possible solutions:
1. Change Inspektor Gadget architecture to have two processes: one is not Landlock'ed and handles the "privileged" operations, the other is Landlock'ed and handles the current operations.
2. Add Landlock'ing later on in the code where no more "privileged" operations are run.

**Comment by dorser** [comment]
Trying to be a little creative, I'm wondering if we can achieve something similar by building a BPF LSM gadget that blocks which paths a program can read and write from and load as part of the initialization of IG.

This is a gadget I'd like to see anyhow, so maybe we could leverage it.
