### ISSUE TITLE
BCC-based gadgets issue on a minikube (vm-driver=docker) multi-node cluster

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#354]
## Description

The BCC-based gadgets fail with the following error only the very first time we execute them after deploying the gadget container:

```
$ ./kubectl-gadget <BCC-gadget>
rmmod: ERROR: Module kheaders is not currently loaded
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module) or installing the kernel development package for your running kernel version.
chdir(/lib/modules/5.11.0-20-generic/build): No such file or directory
Traceback (most recent call last):
  File "/bin/gadgets/<BCC-gadget>", line 244, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 480, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

Error running command: command terminated with exit code 1

  File "/bin/gadgets/execsnoop", line 244, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 478, in __init__
    allow_rlimit, device)
KeyboardInterrupt
```

So far, we have reproduced this issue only on a multi-node cluster where nodes are containers running in the same host (e.g. minikube with `vm-driver=docker`).

Notice the issue does not impact the gadgets `biotop` and `tcptop` because they do not run simultaneously on all the nodes but we need to specify the node where it has to be executed.

### Set-up
Linux ubuntu-focal 5.11.0-20-generic.
Minikube v1.22.0 (vm-driver=docker) running Kubernetes v1.21.2 on Docker 20.10.7 to create a cluster with two nodes (But it should be reproducible if there is more than one node)

### Action(s)
1. Deploy gadget container
2. First execution of any BCC-based gadget -> **FAILURE**
3. Next execution of the same or any other BCC-based gadget -> **OK**
4. Delete and re-deploy gadget container
5. First execution of any BCC-based gadget -> **FAILURE**
6. Next executions of the same or any other BCC-based gadget -> **OK**

## Expected behavior

The BCC-based gadgets should always work, not only from the second execution.

## Additional information

After an analysis, the issue seems to happen during the process of getting the [kernel headers](https://github.com/kinvolk/bcc/blob/eafc80f3a931402e33b254db9cbb7183d10bb6b1/src/cc/frontends/clang/kbuild_helper.cc#L150-L218) for each node. Such process consists on:

1. Check if folder `/tmp/kheaders-$(uname -r)` exist. If so, the next steps are not executed. Notice it is the folder where kernel headers are extracted at the end of this process.
2. Verify if kernel headers are loaded by checking if the file `/sys/kernel/kheaders.tar.xz` exist. If it does not, the `kheaders` module is loaded.
3. Extract the kernel headers in `/tmp/kheaders-$(uname -r)`.
4. If the kernel headers were already loaded at step 2 and we did not have to do it ourselves, then we let the module load. Otherwise, we unload it: `rmmod kheaders`.

The problem of this procedure with our setup (where all the nodes are sharing the same kernel), is that it can cause a race condition between the nodes when accessing the kernel headers. Meaning that one node can unload the `kheaders` module while another one is accessing the file `/sys/kernel/kheaders.tar.xz`. 

The race condition is confirmed if we use a [modified BCC](https://github.com/kinvolk/bcc/tree/jose/no-rm) code that never unloads `kheaders`. In fact, in that case, the issue is never reproduced. It is the same if the `kheaders` module is already loaded before executing the gadgets because none of the nodes will unload it.

The fact that it starts working from the second execution comes from the fact that at the first execution, one of the noded succeed to extract the kernel headers in `/tmp/kheaders-$(uname -r)` and then unloads `kheaders` when the other node is using `/sys/kernel/kheaders.tar.xz`. However, from the second execution on, none of the nodes deals with the `kheaders` module because all of them exit at step (1) given that `/tmp/kheaders-$(uname -r)` already exists.

**Comment by mauriciovasquezbernal** [comment]
We're avoiding the use of BCC-based tools as much as possible and we have plans to mark them as legacy -> https://github.com/inspektor-gadget/inspektor-gadget/issues/625. This issue seems to be a corner case: minikube with 2 or more nodes, using the docker driver and only for BCC-based tools, hence I'll mark this a won't fix and close it.
