### ISSUE TITLE
[RFE] Test gadgets on ARM platform

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#359]
## Current situation

For the moment and from what I know, we are mainly focused on AMD64 architecture.
But the tools we use also exist for ARM architecture ([minikube](https://github.com/kubernetes/minikube/issues/9762), [docker](https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/), etc.).

## Impact

This can be a good idea to tests our gadgets on ARM based platform to see if they work and what are the problem.
For example, `traceloop` has harcoded `syscalls` values for AMD64 in [`pkg/straceback/syscall_table.go`](https://github.com/kinvolk/traceloop/blob/452c42a5efbefdfa71e4620d58f0eda767bbe5b2/pkg/straceback/syscall_table.go).

## Ideal future situation

All our gadgets should be able to run on ARM based platform.

**Comment by mauriciovasquezbernal** [comment]
Just to be clear, this issue was about **manually** testing the gadgets on ARM, right? We aren't running the integration tests on that platform yet. @eiffel-fl could you please confirm?
