### ISSUE TITLE
[RFC] clang-format version

### ISSUE THREAD

**Issue by burak-ok** [inspektor-gadget/inspektor-gadget#3602]
Newest update: The Rollout has been put on hold. Nonetheless we should discuss this

In our CI we are using `clang-format` on `ubuntu-latest`. That ubuntu version was pointing to `Ubuntu 22.04`, which has `clang-format` up to version `14.0`

There is currently a rollout to change `ubuntu-latest` to `Ubuntu 24.04` https://github.com/actions/runner-images/issues/10636 where `clang-format` is available up to version `18.0`.
The problem here is that the rules are slightly changed and we would need to reformat the code to make it compliant again: https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/11347257386/job/31558242289#step:3:79
```
diff --git a/gadgets/trace_open/program.bpf.c b/gadgets/trace_open/program.bpf.c
index 9a72f99..5605657 100644
--- a/gadgets/trace_open/program.bpf.c
+++ b/gadgets/trace_open/program.bpf.c
@@ -13,7 +13,7 @@
 
 #define TASK_RUNNING 0
 #define NAME_MAX 255
-#define INVALID_UID ((uid_t)-1)
+#define INVALID_UID ((uid_t) - 1)
 
 struct args_t {
 	const char *fname;
```

- Stay on `Ubuntu 22.04`
- Update to `Ubuntu 24..04`, but install earlier version of clang-tidy
- Update to `Ubuntu 24.04` and use newest version of clang-tidy. We would need the newest version of it too locally

**Comment by mauriciovasquezbernal** [comment]
What about if we use our ebpf-builder image to also format the ebpf code to avoid this dependency?

**Comment by burak-ok** [comment]
Its a possibility. We would also need to update the makefile target `clang-format` to spin up the container. In general that would be the best solution since `clang-format` mismatches between developer machines and CI can happen
