### ISSUE TITLE
[RFE] Align CR and CLI operations of muti-rounds gadgets (seccomp, biolatency and network-policy-advisor)

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#366]
## Current situation

Currently, muti-rounds gadgets (The ones that need more than one operation to generate the output: seccomp, biolatency and network-policy-advisor) uses its own CR operations and logic to generate the final report:

- **Biolatency**: The report is generated by annotating the trace with the `stop` operation.
- **Seccomp**: The report is generated by annotating the trace with the `generate` operation (Notice it must be done before annotation with `stop`).
- **Network-policy-advisor**: The report is generated by annotating the trace with the `update` and then the `report` operations.

Of course, it is necessary to have initially annotated all of them with the `start` operation.

In addition, the network-policy-advisor CLI uses different sub-commands: `monitor` (The combination of `start` + `update` CR operations) and `report`. While the biolatency and seccomp CLI does not exist yet.

## Impact

It is confusing for the user.

## Ideal future situation

We agreed to align the CR operations and have only `start` and `stop` (That automatically generates the report). Then, based on users feedback, we will consider adding another operation to provide temporal results without the need of stopping the gadget.

In addition, make the CLI 1:1 with the CR operations.

TO-DO:
- [ ] #367 
- [ ] < Issue to change trace operations of network-policy-advisor >

**Comment by mauriciovasquezbernal** [comment]
Closing as there were no comments opposing to it.
