### ISSUE TITLE
[RFE] seccomp: Generate the report when annotating the trace with the `stop` operation

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#367]
## Current situation and impact

Check #366 to see the motivation for this change.

## Ideal future situation

- The seccomp's CR operations need to be modified to generate the report when annotating the trace with the `stop` operation.
- Update the CLI
- Update documentation:
  - https://github.com/kinvolk/inspektor-gadget/blob/main/docs/gadgets/seccomp.md
  - https://github.com/kinvolk/inspektor-gadget/blob/main/docs/guides/seccomp.md
- Describe into the documentation that:
  - When pods are terminated, the generation is done automatically. TBD: I think we should also automatically stop the whole trace in this case. Do we all agree?
  - The `trace.Spec.Filter` field is read when the trace is annotated with the `generate` operation. TBD: Do we really want to keep the possibility of changing such a field at runtime now that the `generate` operation does not exist anymore?

**Comment by blanquicet** [comment]
Thanks @alban for your response!

> > Why it is not possible to filter only by namespace when using the operation=generate? Is there something that prevents us from putting the policies of every pod within the requested namespace, one after the other, as we are doing if they terminate?
> 
> It could be possible with some `OutputMode` but not with `OutputMode=ExternalResource` since the `spec.output` field can only specify one name to the SeccompProfile. Unless we consider the `spec.output` field not to contain the full name of the resource to create, but a prefix and the gadget would add a random suffix to avoid collisions?

I think it could be an idea, also because we are already auto-generating the resource name for the policies generated at pod termination with the prefix `<trace-name>-`. Actually, I think it would be better to have the same name convention for both cases: On-demand and at-termination generation. In addition, if we decide to do so, I would start asking myself if we should continue using the  `spec.output` or if we should use `<trace-name>-` as a prefix in both cases. What do you think?

> > I know it is currently not supported by the trace-controller but do you think it would be feasible to support the automatic policy generation with Status output mode?
> 
> What do you mean with automatic? Upon pod termination? Yes, I think it is possible. The gadget has already a Kubernetes Client to create SeccompProfile. It could just use the same Kubernetes Client to modify the trace.

Great! 

> > I noticed that the pod must exist before annotating the trace with operation=start if we want the gadget to generate the automatic policy when it terminates. Do you think the seccomp gadget could subscribe to the container creation event to support this?
> 
> I don't think the pod must exist before the "start" operation. The gadget subscribes to pod termination for all pods that match the filter. Are you sure your filter was correct?

You are right. My fault, sorry!

cc @marga-kinvolk

**Comment by blanquicet** [comment]
> > > Why it is not possible to filter only by namespace when using the operation=generate? Is there something that prevents us from putting the policies of every pod within the requested namespace, one after the other, as we are doing if they terminate?
> > 
> > 
> > It could be possible with some `OutputMode` but not with `OutputMode=ExternalResource` since the `spec.output` field can only specify one name to the SeccompProfile. Unless we consider the `spec.output` field not to contain the full name of the resource to create, but a prefix and the gadget would add a random suffix to avoid collisions?
> 
> I think it could be an idea, also because we are already auto-generating the resource name for the policies generated at pod termination with the prefix `<trace-name>-`. Actually, I think it would be better to have the same name convention for both cases: On-demand and at-termination generation. In addition, if we decide to do so, I would start asking myself if we should continue using the `spec.output` or if we should use `<trace-name>-` as a prefix in both cases. What do you think?

@alban, I thought long and hard about this and I think that, even though we decide to use the prefix `<trace-name>-` also for the on-demand generation, the `spec.output` field would be still useful if the user wants to specify the namespace where the policy has to be created. However, if we want to keep it, I think we need to ensure the following items:

1. All the policies must be created in the same namespace: Currently, with the trace's fields `spec.output=seccomp-demo/hello-profile` and `metadata.namespace=gadget` (as usual), the on-demand policy will be created on `seccomp-demo` namespace, while the at-termination policies will be created on `gadget` (The trace's namespace).
2. If `spec.output` field is missing, we should throw a more specific error: Currently, if such field is not specified, the `generate` operation fails with the `operationError` field set to `Failed to update resource: SeccompProfile.security-profiles-operator.x-k8s.io "" is invalid: metadata.name: Required value: name or generateName is required`. I suggest managing this error to be something like `Field spec.output was not specified and it is mandatory for OutputMode=ExternalResource`.

What do you think?

**Comment by alban** [comment]
@blanquicet I wonder if it could use `spec.output` as a prefix for both on-demand generation and at-termination policies, and fallback to the trace's namespace and name when `spec.output` is empty. That would solve the error message issue. It might be useful to add another annotation to specify if the SeccompProfile was on-demand or at-termination generated.

**Comment by blanquicet** [comment]
@alban I think that having it mandatory help us to keep things easier under control (which I like) but your proposal gives more flexibility to the user.

**Comment by blanquicet** [comment]
To summarise all these discussions, following a list of improvements we concluded that could be done in addition to the main task requested by this issue (generating the report with the `stop` operation):

1. Align namespace and naming convention for the policies generated on-demand and at pod termination. A first proposal is to use a generated name with the prefix specified by `spec.output` or `<trace-name>` when `spec.output` is empty. The same goes for the namespace, all the policies must be created in the same namespace which can come from the `spec.output` or the trace's namespace as a fallback if `spec.output` is empty or it does not follow the notation `<namespace>/<policy-prefix-name>`.
2. Add another annotation to specify if the SeccompProfile was on-demand or at-termination generated.
3. After having implemented (1), the only constraint remaining to be able to support more flexible filtering is the lack of a GlobalTrace CRD. This task is already tracked by #265.
4. Support the policy generation at pod termination when using `OutputMode=Status`. We still have to decide what to do when the user executes the `generate` operation: I think we could append the new policy (The one triggered by the `generate` operation) to the policies already present in the `Status.Output` field (The ones triggered by the pod termination) even if the filter could have changed. That's up to the user to understand the final output knowing that the filter was modified.

I will create an issue for them to keep issues and PRs simple and concrete.
