### ISSUE TITLE
[EPIC] Stream events API  

### ISSUE THREAD

**Issue by margamanterola** [inspektor-gadget/inspektor-gadget#372]
Currently, the dns gadget uses the `Stream` output mode. To do this, it uses a gRPC client that runs inside the existing gadget container and communicates with the gRPC server using Unix sockets. 

This works, but doesn't allow third party applications (like Headlamp) to interact with any streaming gadgets. It also doesn't aggregate events that arrive from different nodes. 

So, for this epic we need to:
- [ ] Expose gRPC interface for event streaming to third party tools 
- [ ]  Aggregate streamed events from different nodes

**Comment by mauriciovasquezbernal** [comment]
Related to https://github.com/inspektor-gadget/inspektor-gadget/pull/1096.

**Comment by mauriciovasquezbernal** [comment]
It's difficult to tackle this issue alone, then I'll close it and let the whole thing be handled in https://github.com/inspektor-gadget/inspektor-gadget/issues/673.
