### ISSUE TITLE
ig-k8s: Consolidate entrypoint binary on main gadget tracer manager binary

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3742]
The [entrypoint](https://github.com/inspektor-gadget/inspektor-gadget/blob/8f27e02415ac3af3998bf97ba61fbedeed30fc7a/gadget-container/entrypoint/entrypoint.go) logic is currently compiled as an [independent binary](https://github.com/inspektor-gadget/inspektor-gadget/blob/7a25d47ec46edcae209d816ba7880e0d5b9740a9/gadget-container/Makefile#L10-L15). There is not any reason to do this way, this logic should be directly called from the [main](https://github.com/inspektor-gadget/inspektor-gadget/blob/8ddda6b1ff6dc779b46a516fec620876cb6f98c5/gadget-container/gadgettracermanager/main.go#L121) function of the gadget tracer manager process.

Ref https://github.com/inspektor-gadget/inspektor-gadget/pull/2207#issuecomment-1798489733

**Comment by KapilSareen** [comment]
Hi @mauriciovasquezbernal , is issue open for contributions?

**Comment by mauriciovasquezbernal** [comment]
@KapilSareen for sure.
