### ISSUE TITLE
Align DNS image-based gadget with built-in gadget

### ISSUE THREAD

**Issue by Sefi4** [inspektor-gadget/inspektor-gadget#3804]
## Description
DNS image-based gadget doesn't report the `exepath` and `cwd` fields given the `--paths` flag. Also, it doesn't report the `nameserver` field.

**Comment by alban** [comment]
Before increasing the size of the event with `exepath` and `cwd`, I would like to fix #3806 first to limit the size of the packet sent to userspace.

**Comment by alban** [comment]
> Also, it doesn't report the nameserver field.

The nameserver is reported in the `dst` field for DNS requests and `src` field for DNS responses:
```
$ sudo ig run ghcr.io/inspektor-gadget/gadget/trace_dns:latest -o yaml
...
dst:
  addr: 192.168.0.1
  port: 53
  proto: UDP
  proto_raw: 17
  version: 4
```

**Comment by Sefi4** [comment]
> The nameserver is reported in the dst field for DNS requests and src field for DNS responses:
Totally agree, I thought it would be nice to add a dedicated field for this to be consistent with the built-in event:
https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/gadgets/trace/dns/tracer/tracer.go#L195
`if dnsLayer.QR {
  event.Qr = types.DNSPktTypeResponse
  event.Nameserver = event.SrcIP
  
  event.Latency = time.Duration(bpfEvent.LatencyNs)
  event.Rcode = dnsLayer.ResponseCode.String()
  } else {
  event.Qr = types.DNSPktTypeQuery
  event.Nameserver = event.DstIP
}`

What do you think?

**Comment by alban** [comment]
Oh, I see. Yes I think that is fine to add, and that would make it easier for consumers to get the nameserver. Feel free to file a PR.

**Comment by Sefi4** [comment]
> Feel free to file a PR.

Will do, thanks!
