### ISSUE TITLE
ContainerHook with Fanotify failed for large PID file size

### ISSUE THREAD

**Issue by ninadingole** [inspektor-gadget/inspektor-gadget#3812]
## Description

We upgraded from 0.34 to 0.35 for IG and we are using `containercollection.WithContainerFanotifyEbpf()` from go code. 
We also need to read some other stuff from `/proc` directory so we have `hostPID: true` set. However, because we are sharing the host namespace the code that checks for PID file size fails [here](https://github.com/ninadingole/inspektor-gadget/blob/refs/heads/main/pkg/container-hook/tracer.go#L490). We have a large k8s cluster with many containers so the pid file seems bigger and the code fails causing our daemonSet to fail.

## Impact

Our app cannot start

Error:

```
time="2024-12-17T14:51:00Z" level=error msg="fanotify: received fd refers to a large file: 9873 bytes
```

## Expected behavior

the fanotification in containerhooks should work if we are sharing hostPID namespace

**Comment by alban** [comment]
The pid file from runc should just contains the pid digits. Even if the pid was maxint `4294967295`, that's only 10 bytes. In your error message, it says 9873 bytes, so it can't be a pid file.

It should be fine if the fanotify code receives an event for a file that is not a pid file for any container. It can happen if a process reads a file in the same directory as where containerd/runc stores the pid files. It is just ignored later [here](https://github.com/ninadingole/inspektor-gadget/blob/6033b619b4a43ecf3eb90d3614226469642b0b3d/pkg/container-hook/tracer.go#L523).

`containercollection.WithContainerFanotifyEbpf()` logs an error with `log.Errorf` in that case but it does not stop. Arguably, it should be replaced by a warning or a debug message. It should not cause your process to stop. Do you have other error messages after?

For debugging, could you print `data.GetPath()`? (moving this [block](https://github.com/ninadingole/inspektor-gadget/blob/6033b619b4a43ecf3eb90d3614226469642b0b3d/pkg/container-hook/tracer.go#L496-L500) before [this](https://github.com/ninadingole/inspektor-gadget/blob/6033b619b4a43ecf3eb90d3614226469642b0b3d/pkg/container-hook/tracer.go#L490) and printing the path)

**Comment by ninadingole** [comment]
@alban thanks for your reply, we figured out the issue it was because of the container enrichment type passed to container collection option we used. We changed that and it was not working, now it's all working fine so I will close this issue. However, you are right the logging needs some improvement as the context is not clear

**Comment by alban** [comment]
I tried to improve the logging in #3864.
