### ISSUE TITLE
Add a list of supported / tested distributions to the requirements page

### ISSUE THREAD

**Issue by margamanterola** [inspektor-gadget/inspektor-gadget#404]
## Current situation

The requirments page lists the kernel versions necessary for each gadget, but it doesn't talk but supported distributions.

## Impact

Someone that isn't aware of the kernel version they are running (specially relevant for kubernetes vendors) might not know whether their distribution is supported or not.

## Ideal future situation

The requirements page should include information regarding on what distributions we have tested Inspektor Gadget, and whether those are "officially supported" or not (whatever that means, since we haven't defined that yet)

**Comment by mqasimsarfraz** [comment]
I believe this issue can be closed since we defined supported [platforms here](https://www.inspektor-gadget.io/docs/v0.26.0/getting-started/requirements/#kubernetes-platform-requirements). Should we mention that AKS, GKE and AWS are tested in the CI as well. @mauriciovasquezbernal thoughts?

**Comment by mauriciovasquezbernal** [comment]
> I believe this issue can be closed since we defined supported [platforms here](https://www.inspektor-gadget.io/docs/v0.26.0/getting-started/requirements/#kubernetes-platform-requirements).

Yes, this can be closed. 

> Should we mention that AKS, GKE and AWS are tested in the CI as well.

It'll make sense. What about adding a new column called `tested` and add links to the workflows testing those platforms?
