### ISSUE TITLE
[RFE] Provide a HELM chart

### ISSUE THREAD

**Issue by margamanterola** [inspektor-gadget/inspektor-gadget#414]
## Current situation

Deploying Inspektor Gadget on the cluster requires running the deploy subcommand and applying the output of that command. There's no HELM chart

## Impact

Operators that are used to deploying with HELM need to work outside of their workflow both to deploy and remove the deployed pods.

## Ideal future situation

We should provide a HELM chart and make sure it's published in the right places so that people that use HELM charts can find it.

## Implementation options

To avoid duplication of work, it would make sense if both the HELM chart and the output of the deploy subcommand have the same source of truth.

**Comment by mqasimsarfraz** [comment]
Helm Charts for Inspektor Gadget have been published [here](https://inspektor-gadget.github.io/charts), closing the issue!
