### ISSUE TITLE
[RFE] Allow filtering based on not matching some specific criteria

### ISSUE THREAD

**Issue by margamanterola** [inspektor-gadget/inspektor-gadget#415]
## Current situation

Many of our gadgets can filter by typical kubernetes criteria like node, namespace, label, etc. However, it's only possible to select pods or containers that match the specified criteria. It's not possible to sleecto those that don't match. For example: it's not possible to say "Everything except the kube-system namespace"

## Impact

If users want to inspect what's going on in the cluster except for the kube-system controlling layer, they need to manually list all namespaces present.

## Ideal future situation

Users should be able to select pods that don't match a specific criteria.

**Comment by mqasimsarfraz** [comment]
I believe this issue can be closed now since we support negative filtering with `--filter/-F` e.g `kubectl gadget trace open -A -F 'k8s.namespace:!kube-system'`
