### ISSUE TITLE
Feedback on local gadget

### ISSUE THREAD

**Issue by invidian** [inspektor-gadget/inspektor-gadget#436]
Unfortunately, my original feedback notes got lost, so I'm posting what I've been able to notice again. Some generic feedback on user and developer experience on using local gadget and interacting with the project. As discussed, reporting as a single issue for possible further breakdown:
- [ ] Gracefully check if local gadget is executed as root user. Right now one gets cryptic "failed to set memlock rlimit: operation not permitted" error message when running as regular user.
- [x] Git ignore locally built binaries to get rid of -dirty tag in version when rebuilding the binary.
- [x] Git ignore *.o files.
- [x] Add Go 1.17 build tags. Right now building with Go 1.17 automatically modifies source files.
- [x] Add local gadget welcome message what commands can be run or point to 'help' command (e.g. "To see available commands, run "help".)
- [x] Make --help and version work for local gadget without spawning the cmd?
- [x] Clean up Docker image from temporary files to reduce size of Docker image.
- [ ] Add 'help' target to Makefile with list of targets with description.
- [x] With `operations` command, it is ambiguous what operations can be executed on traces (and --help does not help).

Major usability issue I had is reported separately: #431.

**Comment by mauriciovasquezbernal** [comment]
@invidian I opened two smaller issues with the remaining items. Thanks a lot for your feedback.

**Comment by invidian** [comment]
Thanks for addressing most of it, whole team is doing awesome work :)
