### ISSUE TITLE
[RFE] Ensure that generating the BPF object files is stable to avoid errors and commit noise

### ISSUE THREAD

**Issue by invidian** [inspektor-gadget/inspektor-gadget#459]
## Current situation

It seems generating `pkg/gadgets/socket-collector/tracer/*.o` is environment dependent somehow, as those files are being modified on my machine.

## Impact

Those files might be pointlessly committed back and forth if their generation is not stable. It may also indicate, that people installing binaries e.g. using `go install` may get not appropriate version of files for their environments?

## Ideal future situation

`pkg/gadgets/socket-collector/tracer/*.o` files generation is stable or they are not committed at all.

## Additional information

Also, it seems `go:generate` statement use `GOOS=$(go env GOHOSTOS)`, however, when setting e.g. `GOOS=darwin`, generation fails. Perhaps some platform build tags should be used there instead?

My environment:
- go version go1.17.5 linux/amd64 (also tried 1.16.x)
- clang version 13.0.0
- Linux 5.15.12-arch1-1

**Comment by marga-kinvolk** [comment]
Currently, building local-gadget triggers overwriting the object files and can cause this issue.

**Comment by mauriciovasquezbernal** [comment]
This is somehow related to https://github.com/kinvolk/inspektor-gadget/pull/820.

**Comment by mauriciovasquezbernal** [comment]
We know have a test on the CI to check that the BPF objects are updated (https://github.com/inspektor-gadget/inspektor-gadget/pull/1190). Closing it as I think it's fixed.
