### ISSUE TITLE
gadgets/networkpolicyadvisor: consider avoid using string comparison in tests

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#52]
Current tests for the network policy advisor marshall the policies to strings and them compare if they are equal.  This method could have some problems as the string representation of two identical policies could be different. We already found a problem https://github.com/kinvolk/inspektor-gadget/pull/50 due to the fact that maps are not ordered in Golang. 

The scope of this issue is to find another way of comparing network policies to avoid such problems.

**Comment by alban** [comment]
Fixed by https://github.com/kinvolk/inspektor-gadget/pull/50 ?

**Comment by mauriciovasquezbernal** [comment]
#50 only solves one of the potential issues, the order of the policies itself. Maps are used in other places to build the network policy, so it could happen that in more complicated cases (having multiple ingress / egress rules per policy) the output could not be deterministic.  

In this issue I'm suggesting to change the way network policies are compared to avoid relying on the marshaling process. Another solution could be to make sure that policies marshaling is deterministic, I don't know if that's feasible though. 

https://github.com/kinvolk/inspektor-gadget/blob/3b201441a3ddf78fd2afa19cf4269f04b75a164d/pkg/gadgets/networkpolicy/networkpolicy.go#L212-L213

**Comment by mauriciovasquezbernal** [comment]
I think this can be handled as part of #373.
