### ISSUE TITLE
Investigate why sometimes the trace `start` operation takes a long time

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#559]
## Description

When running IG on AKS, I noticed that sometimes the CLI goes in timeout after analysing the logs, I realized that the `start` operation took 4 seconds to complete:

```bash
time="2022-03-08T07:14:00Z" level=info msg="Reconcile trace gadget/bindsnoop-8znxw (gadget bindsnoop, node aks-agentpool-31885719-vmss000000)"
time="2022-03-08T07:14:00Z" level=info msg="Gadget bindsnoop operation \"start\" on gadget/bindsnoop-8znxw"
time="2022-03-08T07:14:04Z" level=info msg="Gadget completed operation. Trace status will be updated accordingly"
time="2022-03-08T07:14:04Z" level=info msg="Updating new status of trace \"gadget/bindsnoop-8znxw\": state=Started operationError=\"\" operationWarning=\"\" output=<0 characters>"
```

It is strange because the bindsnoop gadget is using the CORE implementation so it does not need to compile the eBPF program and should not require such a long time to create the tracer and install the program.

https://github.com/kinvolk/inspektor-gadget/pull/558 increases the timeout but we need to investigate where this time is being used and how (if possible) we can reduce it.

## Impact

There is a delay to start displaying the events to the user.

## Environment and steps to reproduce

I reproduced it by running the same gadget multiple times locally using the integration tests.

cc @mauriciovasquezbernal

**Comment by mauriciovasquezbernal** [comment]
Few things about this issue:
1. Some investigation and improvements have been made to speed up tracer start up
   -  https://github.com/inspektor-gadget/inspektor-gadget/issues/1394#issuecomment-1456421534
   - https://github.com/inspektor-gadget/inspektor-gadget/pull/1419
   - https://github.com/inspektor-gadget/inspektor-gadget/issues/1611
   - https://github.com/inspektor-gadget/inspektor-gadget/issues/1612
2. This issue won't happen anymore as that code is not used after https://github.com/inspektor-gadget/inspektor-gadget/pull/1281
3. https://github.com/inspektor-gadget/inspektor-gadget/issues/1429 proposes to measure the time to boot a gadget under different conditions

I think we can close it as it's covered by other issues.
