### ISSUE TITLE
kinvolk/inspektor-gadget network policy fails to monitor flows due to "Gadget Daemon not found"

### ISSUE THREAD

**Issue by QWERTY92009** [inspektor-gadget/inspektor-gadget#578]
## Description

When attempted to use the kinvolk/inspektor-gadget network policy function, very few logs are obtained, the "Gadget Daemon not found" error is provided, and after several seconds the monitoring stops.

## Impact

This prevents us from using kinvolk/inspektor-gadget to monitor flows and develop / validate network policies.

## Environment and steps to reproduce

1. **Set-up**: On prem-cluster, Kubernetes v1.19. Using nodeSelector to apply inspektor-gadget to nodes running  pods of interest.

Note that one worker node c5 is configured not to schedule pods, but the gadget yaml has been configured to use a nodeSelector to avoid this node.

2. **Task**: Starting network policy monitoring per https://kinvolk.io/docs/inspektor-gadget/0.2/guides/network-policy/ 
kubectl gadget network-policy monitor --namespace ns1 --output ./networktrace.log

3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. [ requested the start of a new pod or container ]
  b. [ container image downloaded ]
5. **Error**: [describe the error that was triggered]
```
Node g4 ready.
Node g2 ready.
Error running command: Gadget Daemon not found
Node g1 ready.
Node g3 ready.
Node l1 ready.
Node c7 ready.
Error running command: Gadget Daemon not found
Node l2 ready.
Error running command: Gadget Daemon not found
Node c9 ready.
Node c8 ready.
Node c6 ready.
Error running command: Gadget Daemon not found

```

Node c4 did not report as ready, but the gadget pod is running on that node, and there are no abnormalities in the pod logs.
This process is running on the gadget pod on node c4. Per "ps -aux":
root      4800  0.1  0.8 1340956 17056 ?       Ssl  17:17   0:01 /bin/gadgettracermanager -serve -podinformer -controller

## Expected behavior

Expected the gadget network monitor tool to run and log pod network transactions.
Some of these are logged, but very few and not enough to validate network policies.

## Additional information

May be related to this issue: https://github.com/kinvolk/inspektor-gadget/issues/168

**Comment by mauriciovasquezbernal** [comment]
Hi! Could you please confirm the version if you are using? I suppose it's v0.4.2 by the error message you posted. Would you mind trying with latest version? I'm curious what happen there even if I think it'll fail because Inspektor Gadget doesn't support running only on some nodes (see https://github.com/kinvolk/inspektor-gadget/issues/125). 

It seems to be a difficult one to solve, I'll try to think more and will be back with some ideas.

**Comment by QWERTY92009** [comment]
Hi @mauriciovasquezbernal. Thanks for looking into this. Your latest release seems to be v0.4.2. I'll look for a different version...

**Comment by QWERTY92009** [comment]
@mauriciovasquezbernal I don't see a newer release than v0.4.2. Is there another branch I should be looking at? Thanks!

**Comment by mauriciovasquezbernal** [comment]
You're right, v0.4.2 is out latest release. I meant to use the `main` branch. You can follow the [Compile from the sources](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/install.md#compile-from-the-sources) documentation to install it.

**Comment by marga-kinvolk** [comment]
Hi! We released version 0.5.0 last week. You could check if it works better for you with that version (please note that with this version we've changed the syntax of the CLI commands. To invoke the network-policy advisor you now need to do: `kubectl gadget advice network-policy monitor`).

However, after re-reading the initial message I noticed that the command line says `namespace`, and for the network-policy advisor it still currently requires the parameter to be called `namespaces` (even when you pass only one). I'll file a separate bug for that, but you could also check if that fixes the issue for you.

**Comment by marga-kinvolk** [comment]
Actually, scratch that, that issue was fixed a long time ago, so version 0.4.2 should have worked correctly anyway. @QWERTY92009 , could you please provide any more information regarding your failure? Thanks!

**Comment by mauriciovasquezbernal** [comment]
Would you mind testing this with the latest version @QWERTY92009? thanks!

**Comment by mauriciovasquezbernal** [comment]
Closing this as inactive. Please reopen / open a new one if you have further info to share @QWERTY92009.
