### ISSUE TITLE
gadgets: Create helper function to replace filter map in gadgets

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#682]
Almost all the gadgets have the same code pattern to handle the "filter" map replacement:

https://github.com/kinvolk/inspektor-gadget/blob/e8f72df6c13dcce6bcabac8b7bb31bb6f0476ca8/pkg/gadgets/execsnoop/tracer/core/tracer.go#L90-L111

https://github.com/kinvolk/inspektor-gadget/blob/e8f72df6c13dcce6bcabac8b7bb31bb6f0476ca8/pkg/gadgets/opensnoop/tracer/core/tracer.go#L93-L114

https://github.com/kinvolk/inspektor-gadget/blob/e8f72df6c13dcce6bcabac8b7bb31bb6f0476ca8/pkg/gadgets/mountsnoop/tracer/core/tracer.go#L94-L115

Alban suggested (https://github.com/kinvolk/inspektor-gadget/pull/654#discussion_r871494812) to create a helper function to do it.

Needs to be done after https://github.com/kinvolk/inspektor-gadget/issues/662.

**Comment by burak-ok** [comment]
Most of the times only the code that you linked is present in the gadgets. But there are some exceptions to that. Examples:

[`audit seccomp`](https://github.com/inspektor-gadget/inspektor-gadget/blob/3efb455a99d2e32a8f292f892e2bd1953fac6ee0/pkg/gadgets/audit/seccomp/tracer/tracer.go#L72-L89)
`mapReplacements` is needed for `"containers"` aswell.

[`profile cpu`](https://github.com/inspektor-gadget/inspektor-gadget/blob/3efb455a99d2e32a8f292f892e2bd1953fac6ee0/pkg/gadgets/profile/cpu/tracer/tracer.go#L322-L338) other constants needs to be rewritten aswell.

Do we want to create a helper function which only replaces the most common usage (the one you mentioned) or should it be kind of extensible where the helper function accepts additional items for the `mapReplacements` and `consts`?

**Comment by mauriciovasquezbernal** [comment]
Creating a helper that replaces the most common use case is good enough. For other cases, we can implement the custom logic on each gadget.

**Comment by claudiamarcubina** [comment]
Starting working on this.
