### ISSUE TITLE
[RFE] Use gopogh to convert tests results from JSON to user-friendly HTML

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#688]
## Current situation

Try to use [gopogh](https://github.com/medyagh/gopogh) to improve the integration-tests results shown in the CI. Example of usage in Minikube [here](https://github.com/kubernetes/minikube/blob/fdd027ba1166485cd660bbfe2b9f1646b6d79f43/.github/workflows/functional_verified.yml#L154-L169).

## Impact

It will ease our life while analysing a failure on the integration tests.

cc @alban

**Comment by mqasimsarfraz** [comment]
@blanquicet do you think we can close this issue since we have logs in [summary](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3984769935/attempts/1#summary-10816840833)?  or we keep it open in case we still want `gopogh` or something similar?

**Comment by blanquicet** [comment]
> @blanquicet do you think we can close this issue since we have logs in [summary](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3984769935/attempts/1#summary-10816840833)? or we keep it open in case we still want `gopogh` or something similar?

I think the summary is enough for now and we can close this issue. In case we find that we can still improve it, we can open another issue.
