### ISSUE TITLE
gadget pod restarts under load because of livenessProbe

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#712]
## Description

When starting several pods at the same time, it causes enough load that the `livenessProbe` takes more than 1s to complete and after 3 probe failures, the pod is restarted. This interrupts long running gadgets such as the network policy advisor.

## Impact

Cannot reliably use long-running gadgets while creating several pods.

## Environment and steps to reproduce

1. **Set-up**:
  - `minikube start --container-runtime=containerd --cni=calico`
  - `make minikube-install`
  - In a separate terminal: keep monitoring events: `kubectl get events -n gadget -w`
  - In a separate terminal: keep monitoring `kubectl exec -ti -n gadget gadget-9dkrd -- bash -c 'while sleep 1 ; do time /bin/gadgettracermanager -liveness ; done'`

3. **Task**:
  - Follow the [Network Policy Advisor guide](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/guides/advise/network-policy.md): 
4. **Action(s)**:
  a. `./kubectl-gadget advise network-policy monitor -n demo --output ./networktrace.log`
  b. `kubectl apply -f network-policy-demo.yaml -n demo`
5. **Error**:

```
$ kubectl get events -n gadget -w
0s          Warning   Unhealthy          pod/gadget-9dkrd   Liveness probe failed: command "/bin/gadgettracermanager -liveness" timed out
0s          Warning   Unhealthy          pod/gadget-9dkrd   Liveness probe failed: command "/bin/gadgettracermanager -liveness" timed out
0s          Warning   Unhealthy          pod/gadget-9dkrd   Liveness probe failed: command "/bin/gadgettracermanager -liveness" timed out
0s          Normal    Killing            pod/gadget-9dkrd   Container gadget failed liveness probe, will be restarted
```

```
$ kubectl exec -ti -n gadget gadget-9dkrd -- bash
root@minikube:/# while sleep 1 ; do time /bin/gadgettracermanager -liveness ; done
...
Gadget Tracer Manager healthy: SERVING
real	0m4.507s
user	0m0.233s
sys	0m0.046s
Gadget Tracer Manager healthy: SERVING
real	0m1.490s
user	0m0.174s
sys	0m0.047s
Gadget Tracer Manager healthy: SERVING
real	0m2.257s
user	0m0.149s
sys	0m0.049s
Gadget Tracer Manager healthy: SERVING
real	0m1.336s
user	0m0.119s
sys	0m0.034s
Gadget Tracer Manager healthy: SERVING
real	0m3.508s
user	0m0.256s
sys	0m0.060s
```

```
$ kubectl logs -n gadget gadget-9dkrd --previous
time="2022-06-27T15:02:57Z" level=info msg="Stopping Pod controller"
```

```
$ ./kubectl-gadget advise network-policy monitor -n demo --output ./networktrace.log
...
Error: failed to receive stream on node "minikube": command terminated with exit code 1
```

```
$ tail -1 ./networktrace.log
^[[31mFATA^[[0m[0885] &{0xc0005e3900}.ReceiveStream(_) = _, rpc error: code = Unavailable desc = error reading from server: EOF
```

## Expected behavior

* [ ] The liveness probe reliably completes within its timeout and the gadget pod does not restart.
* [ ] Maybe: the advisor "report" command should ignore unparsable input files (or at least the last line), so that the user is not forced to manually fix the input file

## Additional information

The gadget's liveness probe looks like this:
```
      livenessProbe:
        exec:
          command:
          - /bin/gadgettracermanager
          - -liveness
        failureThreshold: 3
        initialDelaySeconds: 60
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
```

A workaround could be to increase `timeoutSeconds`, but there might be something in Inspektor Gadget that uses too much CPU.

Side note: the `Makefile` attempts to replace `initialDelaySeconds` with a `sed`, but since c47ce878c33e43c91e4e23671709b4cf0075e08e, the `sed` pattern does not match because it does not match the default value in `cmd/kubectl-gadget/deploy.go`. cc @blanquicet

**Comment by mauriciovasquezbernal** [comment]
Related to https://github.com/kinvolk/inspektor-gadget/issues/799.
