### ISSUE TITLE
top gadgets don't print information when using the same interval and timeout

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#716]
## Summary 

It's possible to run the top gadgets in a "single shot" fashion, i.e, when the interval and timeout values are the same (for instance `./kubectl-gadget top file 2 --timeout 2`). In this configuration the gadget should print a single summary of the events and exit, however it could happen that in some cases nothing is printed. This was implemented in https://github.com/kinvolk/inspektor-gadget/pull/583. 

## The issue
In the top gadgets each node pushes a summary of the events each interval https://github.com/kinvolk/inspektor-gadget/blob/008667ba8192f53c8af25d52e2324e2d06708020/pkg/gadgets/filetop/tracer/tracer.go#L216-L237 and https://github.com/kinvolk/inspektor-gadget/blob/008667ba8192f53c8af25d52e2324e2d06708020/pkg/gadgets/filetop/gadget.go#L176, then those are collected 
https://github.com/kinvolk/inspektor-gadget/blob/008667ba8192f53c8af25d52e2324e2d06708020/cmd/kubectl-gadget/top/file.go#L114 and printed by the kubectl-gadget client  https://github.com/kinvolk/inspektor-gadget/blob/008667ba8192f53c8af25d52e2324e2d06708020/cmd/kubectl-gadget/top/file.go#L140. 

There is not any synchronization used among kubectl-gadget and the nodes, it can happen that some updates are missed but it is not a big problem, those will be considered in the next iteration, however this creates some problems when `--timeout` is used as it could happen that some events are lost, printing nothing to the terminal. 

I've been able to reproduce it when loading the CPU of the node. Please notice that this is a one node setup and kubectl-gadget is run on the same node too. The only difference between the following two cases is that one sleeps on each iteration. 

## Case that works fine

```bash
$ kubectl run ubuntu --image ubuntu:latest -- /bin/bash -c 'while true; do date >> foo.txt && sleep 0.1; done'
pod/ubuntu created
$ kubectl wait --for=condition=Ready pod/ubuntu
pod/ubuntu condition met
./kubectl-gadget top file 2 --timeout 2

NODE             NAMESPACE        POD              CONTAINER        PID     COMM             READS  WRITES R_Kb    W_Kb    T FILE
ubuntu-hirsute   default          ubuntu           ubuntu           3831900 sleep            5      0      2       0       R libc.so.6
ubuntu-hirsute   default          ubuntu           ubuntu           3831916 sleep            5      0      2       0       R libc.so.6
ubuntu-hirsute   default          ubuntu           ubuntu           3831931 date             5      0      2       0       R libc.so.6
ubuntu-hirsute   default          ubuntu           ubuntu           3831889 date             5      0      2       0       R libc.so.6
ubuntu-hirsute   default          ubuntu           ubuntu           3831938 sleep            5      0      2       0       R libc.so.6
ubuntu-hirsute   default          ubuntu           ubuntu           3831926 date             0      1      0       0       R foo.txt
ubuntu-hirsute   default          ubuntu           ubuntu           3831924 date             0      1      0       0       R foo.txt
ubuntu-hirsute   default          ubuntu           ubuntu           3831925 sleep            5      0      2       0       R libc.so.6
ubuntu-hirsute   default          ubuntu           ubuntu           3831939 date             5      0      2       0       R libc.so.6
ubuntu-hirsute   default          ubuntu           ubuntu           3831899 date             5      0      2       0       R libc.so.6
[...]
$ kubectl delete pod ubuntu
```

## Reproducer
```bash
$ kubectl run ubuntu --image ubuntu:latest -- /bin/bash -c 'while true; do date >> foo.txt; done'
pod/ubuntu created
$ kubectl wait --for=condition=Ready pod/ubuntu
pod/ubuntu condition met
$ ./kubectl-gadget top file 2 --timeout 2

NODE             NAMESPACE        POD              CONTAINER        PID     COMM             READS  WRITES R_Kb    W_Kb    T FILE
[ nothing is printed]

$ kubectl delete pod ubuntu
```

## Possible solution

One possibility would be to add some synchronization between kubectl-gadget and the nodes, but it seems rather difficult to implement. A complicated algorithm waiting for results of all nodes should be implemented. Another possibility can be to switch from a "push" to a "pull" approach, i.e, instead of waiting for the nodes to "push" the results, the client could "pull" the results from all nodes each interval, this solution seems easier to implement in the long term, however it requires big changes to Inspektor Gadget as we don't have a way to implement it now. 

Some discussion on slack regarding the top gadgets implementation -> https://kubernetes.slack.com/archives/CSYL75LF6/p1655846371253189?thread_ts=1655287566.910119&cid=CSYL75LF6.

**Comment by mauriciovasquezbernal** [comment]
It should be fixed now. Check if this is actually working fine on kubectl-gadget.

**Comment by mqasimsarfraz** [comment]
I tried to test it locally but it doesn't seem to working. For `ig` it works fine but I don't see any information for `kubectl-gadget`. I will investigate why that could be:

```bash
$ kubectl gadget top block-io --all-namespaces --interval 10  --timeout 10  --verbose
NODE                        NAMESPACE                   POD                        CONTAINER                  PID         COMM           R/W MAJOR          MINOR          BYTES          TIME           OPS       
DEBU[0010] minikube-docker      | calling operator.PostGadgetRun() 
DEBU[0010] minikube-docker      | calling RemoveTracer() 
DEBU[0010] minikube-docker      | runClient returned with EOF 
DEBU[0010] minikube-docker      | done from server side (<nil>)
```
