### ISSUE TITLE
[RFE] ci/integration-tests: Use JSON output format for integration tests

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#719]
## Current situation

We execute `kubectl-gadget` using the columns format for integration tests and then we verify the output using regular expressions. The problem is that we are not currently verifying the type of all the fields because the current regular expressions do not match all the columns. 

## Impact

We could miss regressions on those fields that we are not verifying.

## Proposal

Given that the output generated by the `gadget` pod is in JSON format by default, the proposal is that the integration tests run `kubectl-gadget` with JSON output format and then unmarshall the output using the specific types. For instance, for execsnoop, using structs of type [Event](https://github.com/kinvolk/inspektor-gadget/blob/d4000354caac5fb58df556942b3539dbadf41013/pkg/gadgets/execsnoop/types/types.go#L21-L31). Doing so, we are verifying the type of all the fields. In addition, we must verify as many fields as possible. In particular, node, namespace, podname and container name (if available) must always be verified.

To test the transformation from JSON to columns done by the CLI, I propose to test it with unit-tests. After the refactoring of CLI (e.g. PR https://github.com/kinvolk/inspektor-gadget/pull/695), it means to unit-test the implementation of the gadget parsers, e.g. [SocketParser](https://github.com/kinvolk/inspektor-gadget/blob/4786d91d27d229f88850a44ed0d1ebf565a98d17/cmd/kubectl-gadget/snapshot/socket.go#L33) for the snapshot-socket gadget.

## PR tracker 
- Advise: It doesn't apply.
- Audit:
  - [x] Seccomp https://github.com/inspektor-gadget/inspektor-gadget/pull/1104
- Profile:
  - [x] Block-IO https://github.com/inspektor-gadget/inspektor-gadget/pull/1089
  - [x] CPU https://github.com/inspektor-gadget/inspektor-gadget/pull/1089
- Snapshot:
  - [x] Process https://github.com/inspektor-gadget/inspektor-gadget/pull/1087
  - [x] Socket https://github.com/inspektor-gadget/inspektor-gadget/pull/1083
- Top:
  - [x] Block-IO https://github.com/inspektor-gadget/inspektor-gadget/pull/1080
  - [x] ebpf https://github.com/inspektor-gadget/inspektor-gadget/pull/1079
  - [x] file https://github.com/inspektor-gadget/inspektor-gadget/pull/1077
  - [x] tcp: https://github.com/inspektor-gadget/inspektor-gadget/pull/1064
- Trace:
  - [x] Bind: https://github.com/kinvolk/inspektor-gadget/pull/945
  - [x] Capabilities: https://github.com/kinvolk/inspektor-gadget/pull/989
  - [x] DNS: https://github.com/kinvolk/inspektor-gadget/pull/990
  - [x] Exec: https://github.com/kinvolk/inspektor-gadget/pull/945
  - [x] Fsslower https://github.com/kinvolk/inspektor-gadget/pull/1017
  - [x] Mount https://github.com/kinvolk/inspektor-gadget/pull/1009
  - [x] Network: https://github.com/inspektor-gadget/inspektor-gadget/pull/1046
  - [x] OOMKill https://github.com/kinvolk/inspektor-gadget/pull/1027
  - [x] Open: https://github.com/kinvolk/inspektor-gadget/pull/971
  - [x] Signal: https://github.com/kinvolk/inspektor-gadget/pull/945
  - [x] SNI: #1015
  - [x] TCP: https://github.com/kinvolk/inspektor-gadget/pull/945
  - [x] TCP-Connect: https://github.com/kinvolk/inspektor-gadget/pull/1026

**Comment by mauriciovasquezbernal** [comment]
I got bitten by this on https://github.com/kinvolk/inspektor-gadget/pull/767/files#diff-9f5fd20913c5fe80c85263153fa9a0b28dbd1407e53da4ab5d09e13d2774c5db

**Comment by blanquicet** [comment]
Reopening as https://github.com/kinvolk/inspektor-gadget/pull/945 didn't implement all the gadgets. This is the current state per category:

- Advise: It doesn't apply.
- Audit:
  - [ ] Seccomp
- Profile:
  - [ ] Block-IO. NOTE: It is necessary also to implement some unit-tests that verify the transformation to the histogram: [`reportToString`](https://github.com/kinvolk/inspektor-gadget/blob/21bbf94f5ee949f0ff25bbcc510274eee2076343/cmd/kubectl-gadget/profile/block-io.go#L101) and [`starsToString`](https://github.com/kinvolk/inspektor-gadget/blob/21bbf94f5ee949f0ff25bbcc510274eee2076343/cmd/kubectl-gadget/profile/block-io.go#L77).
  - [ ] CPU
- Snapshot:
  - [ ] Process
  - [ ] Socket
- Top:
  - [ ] Block-IO
  - [ ] ebpf
  - [ ] file
  - [ ] tcp
- Trace:
  - [ ] Bind: https://github.com/kinvolk/inspektor-gadget/pull/945
  - [ ] Capabilities
  - [ ] DNS
  - [ ] Exec: https://github.com/kinvolk/inspektor-gadget/pull/945
  - [ ] Fsslower
  - [ ] Mount
  - [ ] Network
  - [ ] OOMKill
  - [ ] Open
  - [ ] Signal: https://github.com/kinvolk/inspektor-gadget/pull/945
  - [ ] SNI
  - [ ] TCP: https://github.com/kinvolk/inspektor-gadget/pull/945
  - [ ] TCP-Connect
