### ISSUE TITLE
ci/integration-tests: Tcptracer sometimes does not produce an output

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#726]
## Description

Sometimes, when running the integration tests, like [here](https://github.com/kinvolk/inspektor-gadget/runs/5542738429?check_suite_focus=true), the output of the Tcptrace gadget is empty so the test fails:

```bash
--- FAIL: TestTcptracer (79.78s)
    command.go:168: Run command: kubectl create ns test-tcptracer-2199668958781972059
    command.go:174: Command returned:
        
        namespace/test-tcptracer-2199668958781972059 created
        
    command.go:203: Start command: $KUBECTL_GADGET tcptracer -n test-tcptracer-2199668958781972059
    command.go:168: Run command: kubectl run --restart=Never --image=busybox -n test-tcptracer-2199668958781972059 test-pod -- sh -c 'while true; do wget -q -O /dev/null -T 3 http://1.1.1.1; done'
    command.go:174: Command returned:
        
        pod/test-pod created
        
    command.go:168: Run command: kubectl wait pod --for condition=ready -n test-tcptracer-2199668958781972059 test-pod
    command.go:174: Command returned:
        
        pod/test-pod condition met
        
    command.go:233: Stop command: $KUBECTL_GADGET tcptracer -n test-tcptracer-2199668958781972059
    command.go:244: Command returned:
        
        NODE             NAMESPACE        POD              CONTAINER        T PID    COMM             IP  SADDR            DADDR            SPORT   DPORT  

     command.go:248: output didn't match the expected regexp: C\s+\d+\s+wget\s+\d\s+[\w\.:]+\s+1\.1\.1\.1\s+\d+\s+        
```

## Impact

CI sometimes fails and loses reliability.

## Expected behavior

The test must not fail.

## Additional information

The problem looks like the cluster loses connectivity but, at least, we need to be sure that it is the issue. Therefore, solving https://github.com/kinvolk/inspektor-gadget/issues/567 first would help to understand if the test-pod is actually generating the events needed to trigger an output on the Tcptracer gadget.

**Comment by blanquicet** [comment]
> I was thinking that we could change these tests to avoid reaching an external service

Sounds good, that could be already an improvement to continue removing external requirements and focusing on the actual behaviour of the gadget.

**Comment by mauriciovasquezbernal** [comment]
I suppose we can close it now that https://github.com/inspektor-gadget/inspektor-gadget/pull/1091 is merged? @blanquicet what do you think?
