### ISSUE TITLE
[RFE] Add support for non-Kubernetes containers with Containerd

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#734]
## Current situation

Currently, In [the runtime-client](https://github.com/kinvolk/inspektor-gadget/blob/main/pkg/container-utils/runtime-client/interface.go) package, the Docker implementation does not use the Docker CRI but directly the Docker Engine API so it is able to retrieve both kinds of containers: Kubernetes and non-Kubernetes. On the contrary, with Contained, we are using the CRI so we don't have visibility of the containers that weren't created via Kubernetes.

## Impact

With Contained, we don't have visibility of the containers that weren't created via Kubernetes as we have with Docker. For the use-case of `local-gadget`, it is a big disadvantage because we are missing part or even all the containers running in the system.

## Ideal future situation

We should use with the dedicated API for Containerd so that we have visibility of all the containers running in the system.

**Comment by burak-ok** [comment]
For `CRI-O` i searched and found this https://pkg.go.dev/github.com/cri-o/cri-o@v1.26.0/internal/client
But this is in a directory called "internal" which means that it could be quite unstable? Should we keep using the `CRI` Client for `CRI-O`?

**Comment by blanquicet** [comment]
Yep, according to CRI-O documentation: [What is the scope of this project?](https://github.com/cri-o/cri-o#what-is-the-scope-of-this-project) and [What is not in the scope of this project?](https://github.com/cri-o/cri-o#what-is-not-in-the-scope-of-this-project), the scope of CRI-O is tied to the scope of the CRI. Therefore, I would say that it doesn't make sense to support non-Kubernetes containers for CRI-O.
