### ISSUE TITLE
[RFE] Enrich containers with k8s metadata the runtime information

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#737]
### Current situation

The [containerRuntimeEnricher](https://github.com/kinvolk/inspektor-gadget/blob/65a398e8ef72887c9b36550de64e7b00cfa8451f/pkg/container-collection/options.go#L43) is enriching the containers with the container name and the PID (only at start-up when retrieving the already running containers). However, there is a lot of information that we can gather from the runtimes to improve the information display per container and the filtering.

### Ideal future situation

We should start by adding the following fields:

- **Container runtime name**: Given that we are collecting the container from different runtimes, we should show the owner of each container. 
- **Container ID**: Two containers can have the same name so the only way to distinguish them is to use the ID.
- **Kubernetes metadata**: For the use-case of `ig` (formerly known as `local-gadget`), it would be very useful to also get the Kubernetes information: Namespace and Pod.

#### Current view
```bash
$ local-gadget list-containers
myContainer1 
shell01     
shell01     
```

#### Future view
```bash
$ local-gadget list-containers --k8s-metadata
CONTAINER RUNTIME    ID               NAME            K8S-POD    K8S-NAMESPACE
cri-o                6af6dd37ab878    myContainer1    myPod      myNamepsace      # Container created with k8s  
containerd           4c45eb2fb0211    shell01                                     # Rouge container
docker               0dbab37ba6429    shell01                                     # Rouge container
```

### Additional improvements

Once https://github.com/kinvolk/inspektor-gadget/issues/734 is merged, we could also add the container runtime namespace. It is supported by Containerd and a user may want to see only the containers created via Kubernetes and not the other ones. To do that it could use the runtime namespace `k8s.io` that is used by Containerd.

**Comment by blanquicet** [comment]
https://github.com/inspektor-gadget/inspektor-gadget/pull/1702 added the k8s information to the events, but it can be displayed only in json/yaml format, not in columns yet. So this issue can't be closed yet.

**Comment by mqasimsarfraz** [comment]
https://github.com/inspektor-gadget/inspektor-gadget/pull/2056 added support for columns but we are still missing shortcuts to append them to existing columns. As discussed in the [slack here](https://kubernetes.slack.com/archives/CSYL75LF6/p1695373263964389), I will take the approach of having `-o cloumns=[+|-]k8s|systemd|runtime` with the initial idea regarding https://github.com/inspektor-gadget/inspektor-gadget/issues/1881 drafted [here already](https://github.com/inspektor-gadget/inspektor-gadget/commit/6cce5674cf1f345d4ffa7d24694f3bc3c397c2ac).

**Comment by mqasimsarfraz** [comment]
Completed by https://github.com/inspektor-gadget/inspektor-gadget/pull/2080
