### ISSUE TITLE
[RFE] ebpftop: Show all pids/comms when multiple processes reference an ebpf program

### ISSUE THREAD

**Issue by flyth** [inspektor-gadget/inspektor-gadget#793]
## Current situation

Right now, the ebpftop gadget only shows a single pid/comm of a process that has an open fd to a bpf program.

## Impact

The user can't see whether there is more than one process with an open fd to the ebpf program at the same time.

## Ideal future situation

The user can see all processes (pid, comm) that reference an ebpf program.

## Implementation options

I suggest adding a line in the output for every process that references the program, with only their `pid` and `comm` information filled. This would look something like this:

```
NODE             PROGID   TYPE             NAME             PID     COMM                      RUNTIME   RUNCOUNT
minikube         6071     Tracing          gadget_ebpftop   540621  gadgettracerman         103.873µs       1057
                                                            12345   anotherprocess                              
minikube         62       CGroupDevice                      2378    systemd                        0s          0
minikube         48       CGroupSKB                         2378    systemd                        0s          0
minikube         49       CGroupSKB                         2378    systemd                        0s          0
minikube         50       CGroupDevice                      2378    systemd                        0s          0
```

## Additional information

This should be done after #782 is done.

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/1361.
