### ISSUE TITLE
pkg/gadgets: Implement unit tests for top tcp

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#842]

**Comment by ghinks** [comment]
@eiffel-fl hello again I thought I would have a try at the some of these unit test issues. I may need some pointers and so will open a draft PR in the hope of getting some pointers [Draft PR 2434](https://github.com/inspektor-gadget/inspektor-gadget/pull/2434)

**Comment by ghinks** [comment]
OK , that's good to know. I'll stop. Maybe close those good first issue unit test issues? I was just looking at good first issue items and you have plenty of other ones. I always look at these things as learning exercises and I picked up a couple of things on the way.

**Comment by mauriciovasquezbernal** [comment]
I'll close this one as well. Sorry for the misunderstanding.
