### ISSUE TITLE
top gadgets: output flickers with empty results

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#852]
## Description

The output is refreshed every second but some of the seconds have an empty output. See this video:

https://user-images.githubusercontent.com/27575/186199963-8cc8b9de-2bd0-4332-ad14-688f54067bef.mp4

## Impact

It does not feel reliable. I don't know if the CLI misses some events or if they are accumulated to the next second's output.

## Environment and steps to reproduce

1. **Set-up**:
 a. AKS cluster (1 node)
 b. Install Falco with ebpf driver:
```
git clone https://github.com/falcosecurity/charts.git
vim falco/values.yaml # replace "kind: module" by "kind: ebpf"
vim falco/Chart.yaml # delete dependency on falcosidekick
helm upgrade --install \
        falco ./falco \
        --create-namespace \
        --namespace falco \
        --values ./falco/values.yaml
```
3. **Task**: 
4. **Action(s)**:
  a. `./kubectl-gadget top ebpf -o custom-columns=node,progid,type,name,runtime,runcount,totalruncount,totalruntime --sort totalruntime`
5. **Error**: See video above

## Expected behavior

The output does not get empty results from time to time.

**Comment by flyth** [comment]
This is probably also a more generic issue that the `top` gadgets have; this could happen whenever stats are not reported exactly within the same interval specified from all the nodes (so most likely a timing/latency issue).

See https://github.com/kinvolk/inspektor-gadget/blob/main/cmd/kubectl-gadget/top/block-io.go#L215

When printing the stats, the previously received stats will be cleared (https://github.com/kinvolk/inspektor-gadget/blob/main/cmd/kubectl-gadget/top/block-io.go#L215) - if the next PrintStats() happens, before new stats are received, it will result in this "flickering". A possible solution would be to not clear the map on printing (or maybe cache the results for one interval) - however, that could actually lead to more unreliable stats, even if it feels more reliable ;)

@mauriciovasquezbernal Any other ideas?

**Comment by mauriciovasquezbernal** [comment]
> This is probably also a more generic issue that the top gadgets have

That's correct. It's a generic issue for all of them.

It's a problem with the top gadgets design itself where each gadget pod sends an update and kubectl-gadget collects all of them. Since there is not any synchronization amount the client and the gadget pods, some times the client receives two updates from a pod in a single interval, causing this effect. This is same cause of https://github.com/kinvolk/inspektor-gadget/issues/716. 

I think a possibility is to switch to a "pull" approach where the kubectl-gadget asks the gadgets pods for an update instead of them pushing it. In this way, the client handles all the synchronization and we avoid missing or receiving two updates on the same interval.

**Comment by flyth** [comment]
> I think a possibility is to switch to a "pull" approach where the kubectl-gadget asks the gadgets pods for an update instead of them pushing it. In this way, the client handles all the synchronization and we avoid missing or receiving two updates on the same interval.

I don't think it's worth switching to the pull approach, as you would run into the same issue when there's more than one node. At one point you have to decide when to output the stats and that may be a time when node 1 answered but node 2 has not yet. For UX reasons, I would suggest that we cache times for one interval - if there's no new data, we would use the old values (for one more interval).

**Comment by blanquicet** [comment]
> I don't think it's worth switching to the pull approach, as you would run into the same issue when there's more than one node. At one point you have to decide when to output the stats and that may be a time when node 1 answered but node 2 has not yet.
>
I don't know if I am missing something but I don't understand why it should be a problem. If at that time only node 1 answered, then we simply output its stats. It is not mandatory to have stats from both nodes to output them, or is it? Am I missing something?

In any case, the problem persists if no nodes generate stats. In such a situation, we will have a "flickering" and that's where `StatsCombiner` could help. See [my comment](https://github.com/kinvolk/inspektor-gadget/pull/898#discussion_r959686190) on the PR.

**Comment by mauriciovasquezbernal** [comment]
Reopening as https://github.com/inspektor-gadget/inspektor-gadget/pull/898 only contains the "snapshotcombiner" but it's not used yet.

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/1396
