### ISSUE TITLE
CLI: Combine `columns` and `custom-columns` output mode

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#908]
## Current situation

After implementing the `parser` approach on all the gadgets (where it makes sense) and defining a default list of columns to be printed when `-o custom-columns=a,b,c` is not provided, it came out that [`OutputModeColumns`](https://github.com/kinvolk/inspektor-gadget/blob/3a31bca668f37a7c0cf04ee83a697f91b81446a1/cmd/common/utils/flags.go#L26) is not needed anymore.  

In fact, in all the places where `OutputModeColumns` is used, it is applied the same strategy as `OutputModeCustomColumns`. Examples:

- https://github.com/kinvolk/inspektor-gadget/blob/3a31bca668f37a7c0cf04ee83a697f91b81446a1/cmd/kubectl-gadget/trace/trace.go#L77-L80
- https://github.com/kinvolk/inspektor-gadget/blob/3a31bca668f37a7c0cf04ee83a697f91b81446a1/cmd/common/utils/parser.go#L111-L114
- https://github.com/kinvolk/inspektor-gadget/blob/3a31bca668f37a7c0cf04ee83a697f91b81446a1/cmd/common/snapshot/snapshot.go#L99-L101

## Impact

Still keeping `OutputModeColumns` creates confusion in the code as it is being used identically to `OutputModeCustomColumns`. 

## Ideal future situation

Remove `OutputModeColumns` option. Notice it has to be done in the common package so that the result is applied to `kubectl-gadget` and `local-gadget`.

**Comment by burak-ok** [comment]
Do we want to additionally rename `OutputModeCustomColumns` to `OutputModeColumns`, after the "original" version is deleted?

Advantage would probably be a better descriptive name imo
Disadvantage is that `OutputModeColumns` is still tied to the old behavior in our heads

**Comment by burak-ok** [comment]
Their default seems to be an empty string `-o, --output=''`
I can implement that in the same way then. As you said it would be nice if kubectl and the gadgets have similar options
