### ISSUE TITLE
CLI: Ensure gadgets are using correctly `AddCommonFlags`

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#909]
## Current situation

Gadgets are adding the common flags in `kubectl-gadget` and `local-gadget` using `AddCommonFlags` (it is diff for each). However, some options could not have a sense on some gadgets. For instance, the option `-o / --option` is always being added, but it is not applicable for some gadgets like `advise/network-policy`, `advise/seccomp-profile` and `profile/block-io`.

## Impact

The CLI is showing flags that are not actually being used on some gadgets.

## Ideal future situation

Ensure the available flags for each gadget are coherent.

**Comment by mauriciovasquezbernal** [comment]
This was fixed for local-gadget in https://github.com/inspektor-gadget/inspektor-gadget/pull/1281, a follow up PR will fix it for kubectl-gadget.

**Comment by mauriciovasquezbernal** [comment]
Will be fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/1396.
