### ISSUE TITLE
top ebpf is half working on AKS amd64 Ubuntu18

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#931]
## Description

When running `top ebpf` on AKS running on amd64 hardware with Ubuntu 18.04 as OS SKU (i.e. default option as time of writing), some eBPF programs are not printed.
Particularly, the `ig_top_ebpf_it` is not printed so integration test fails.

## Impact

The `top eBPF` does not display all the loaded eBPF programs.

## Environment and steps to reproduce

```bash
$ bash az-aks.sh -o Ubuntu -n you-aks-ubuntu
...
$ kubectl gadget deploy
...
$ kubectl gadget top ebpf -A
NODE             PROGID   TYPE             NAME             PID     COMM                      RUNTIME   RUNCOUNT      MAPMEMORY MAPCOUNT 
aks-nodepool1-10169380-vmss000000 277      CGroupSKB                         1       systemd                        0s          0            44B        2 
aks-nodepool1-10169380-vmss000000 278      CGroupSKB                         1       systemd                        0s          0            44B        2 
aks-nodepool1-10169380-vmss000000 279      CGroupSKB                         1       systemd                        0s          0            44B        2 
aks-nodepool1-10169380-vmss000000 280      CGroupSKB                         1       systemd                        0s          0            44B        2 
aks-nodepool1-10169380-vmss000000 281      CGroupSKB                         1       systemd                        0s          0            44B        2 
aks-nodepool1-10169380-vmss000000 282      CGroupSKB                         1       systemd                        0s          0            44B        2 
^C
Terminating...
```

## Expected behavior

All the loaded eBPF programs should be displayed.

**Comment by retpolanne** [comment]
That may be the reason, I guess

https://discourse.ubuntu.com/t/unprivileged-ebpf-disabled-by-default-for-ubuntu-20-04-lts-18-04-lts-16-04-esm/27047

**Comment by flyth** [comment]
Could you please check whether `/proc/kallsyms` is available and that it has the addresses set when read as root? Because if that's not the case, we fall back to iterating over `/proc/$pid/fdinfo/$fd` instead of using the `iter/task_file` ebpf program.
