### ISSUE TITLE
gadgets/types: Analize usage of `omitempty` tag 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#964]
We're using the json `omitempty` tag for most of the members of the gadgets types. According to the [documentation](https://pkg.go.dev/encoding/json):

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string. 

It's not clear to me if we should use that tag in all members, for instance, I found a misleading situation with the uid flag, as `0` is a valid value and IMO should not be omitted:

```$ sudo ./local-gadget trace exec -o json | jq 
WARN[0000] Runtime enricher (cri-o): couldn't get current containers 
# event generated with docker run -it --rm --user 1000 --name test-container busybox /bin/sh -c "cat /dev/null 
{
  "namespace": "default",
  "pod": "test-container",
  "container": "test-container",
  "type": "normal",
  "pid": 440839,
  "ppid": 440028,
  "uid": 1000,
  "mountnsid": 4026534489,
  "pcomm": "cat",
  "args": [
    "/bin/cat",
    "/dev/null"
  ]
}

[...]
# event generated with docker run -it --rm --user 0 --name test-container busybox /bin/sh -c "cat /dev/null
{
  "namespace": "default",
  "pod": "test-container",
  "container": "test-container",
  "type": "normal",
  "pid": 445212,
  "ppid": 445161,
  "mountnsid": 4026534495,
  "pcomm": "cat",
  "args": [
    "/bin/cat",
    "/dev/null"
  ]
}
```

Notice how in the second test the uid is missing from the json.

**Comment by alban** [comment]
I think we should remove omitempty everywhere. This is confusing for users, harms discoverability and I doubt it would impact performances.

**Comment by flyth** [comment]
Tbh, users shouldn't get access to _those_ JSON structs anymore but instead we should use the `jsonformatter` package for user facing JSON output. That will follow the layout defined for the "columns" and will become the standard way to serialize to JSON after migrating to the image based gadgets. The only issue with that is that some fields are treated differently right now, so this would be a breaking change and we certainly need to discuss a couple of things around that.

Having said that, removing the `omitempty` could have a negative impact on consumed bandwidth, but I also doubt that it will affect performance much.

**Comment by mauriciovasquezbernal** [comment]
I agree with you both that we can / should remove `omitempty`, but I'm not sure if this is relevant anymore now that we're moving to "image based / containerized gadgets".

**Comment by mauriciovasquezbernal** [comment]
> I agree with you both that we can / should remove `omitempty`, but I'm not sure if this is relevant anymore now that we're moving to "image based / containerized gadgets".

I don't think it's relevant anymore. Closing it.
